'use client'

import ProductDoc from '@/components/ProductDoc'

export default function WhatsAppBotDocPage() {
  return (
    <ProductDoc
      name="Echo WhatsApp Bot"
      tagline="AI-powered WhatsApp Business automation — message templates, interactive flows, catalog integration, payments, and CRM sync."
      accent="#25d366"
      productUrl="/bots"
      workerUrl="https://echo-whatsapp.bmcii1976.workers.dev"
      version="2.4.0"
      overview={[
        'Echo WhatsApp Bot is an enterprise-grade WhatsApp Business API automation platform running on Cloudflare Workers. It handles the full spectrum of WhatsApp Business capabilities: approved message templates for outbound campaigns, interactive button and list messages for guided flows, product catalog integration for in-chat shopping, payment link generation, and AI-powered conversational agents that resolve customer inquiries without human intervention.',
        'The platform connects to the WhatsApp Cloud API (Meta Business Platform) and manages the complete message lifecycle — from template submission and approval tracking, through real-time webhook processing and delivery receipts, to conversation analytics and compliance archival. Every conversation session is persisted in D1 with full message history, enabling the AI to maintain context across the 24-hour customer service window and beyond through template-initiated re-engagement.',
        'Business operations are deeply integrated. The CRM sync module pushes every contact, conversation, and transaction to your Echo CRM instance in real time. Appointment booking flows let customers select dates, times, and services through interactive list menus without leaving WhatsApp. Broadcast lists segment your audience by tags, purchase history, and engagement score, then deliver personalized template messages with dynamic variables. All of this runs on the global Cloudflare edge, processing webhook events in under 15ms.',
      ]}
      gettingStarted={[
        { step: 1, title: 'Connect Your WhatsApp Business Account', desc: 'Register your business on the Meta Business Platform and create a WhatsApp Business Account. Generate a permanent access token and phone number ID. Store both in the Echo Vault — the Worker pulls them at runtime and never exposes them in logs.' },
        { step: 2, title: 'Configure the Webhook', desc: 'Set the webhook URL in Meta Business Platform to https://echo-whatsapp.bmcii1976.workers.dev/webhook. Enter the verify token from your bot settings. The Worker handles the verification challenge automatically and begins processing incoming messages immediately.' },
        { step: 3, title: 'Create Message Templates', desc: 'Design message templates for outbound campaigns via the /api/templates endpoint or the dashboard. Templates require Meta approval (typically 1-24 hours). Include header (text/image/document), body with dynamic variables {{1}}, {{2}}, and optional footer and buttons.' },
        { step: 4, title: 'Set Up Auto-Reply Rules', desc: 'Configure keyword-triggered auto-replies and AI conversation mode. Define exact-match and fuzzy-match keywords with associated responses. Enable AI mode for freeform conversations — the bot uses your business context document to answer questions accurately and route complex inquiries to human agents.' },
        { step: 5, title: 'Connect CRM and Go Live', desc: 'Enable the CRM sync module to push contacts and conversations to Echo CRM. Configure business hours, away messages, and escalation rules. Send a test message to your WhatsApp number to verify the end-to-end flow. Monitor the analytics dashboard for delivery rates and response times.' },
      ]}
      features={[
        { title: 'Message Templates', desc: 'Create, submit, and manage WhatsApp-approved message templates for outbound campaigns. Support for text, image, video, and document headers. Dynamic variables ({{1}}, {{2}}) personalize each send. Track approval status and rejection reasons. Template library with versioning.' },
        { title: 'Interactive Buttons', desc: 'Send messages with up to 3 quick-reply buttons or a single URL button. Button taps trigger callback handlers that route to conversation branches, API calls, or payment flows. Button state is tracked per user for flow continuity. List messages support up to 10 selectable sections with descriptions.' },
        { title: 'Catalog Integration', desc: 'Sync your product catalog from the Meta Commerce Manager. Send single products or multi-product messages directly in chat. Customers browse, select quantities, and add to cart without leaving WhatsApp. Cart events trigger order confirmation flows and payment processing.' },
        { title: 'Payment Links', desc: 'Generate secure payment links for products, services, invoices, and subscriptions. Links are sent as interactive button messages. Payment confirmation webhooks update order status in real time. Supports Stripe, PayPal, and direct bank transfer with auto-reconciliation.' },
        { title: 'Group Management', desc: 'Create and manage WhatsApp groups programmatically. Add/remove participants, update group metadata, send group announcements, and moderate content. Group messages are processed through the same AI and keyword engine as direct messages.' },
        { title: 'Broadcast Lists', desc: 'Segment contacts by tags, purchase history, engagement score, and custom attributes. Send personalized template messages to thousands of contacts with throttled delivery that respects Meta rate limits. Track delivery, read, and reply rates per campaign with exportable reports.' },
        { title: 'Media Messaging', desc: 'Send and receive photos, videos, documents, audio, stickers, and location pins. Media received from customers is stored in R2 with configurable retention. Outbound media supports caption text, filename customization, and automatic format conversion for compatibility.' },
        { title: 'Auto-Replies', desc: 'Keyword-triggered auto-replies with exact match, fuzzy match, and regex support. Prioritized rule chains — first match wins. Time-based rules for business hours vs. after-hours responses. Fallback to AI conversation when no keyword matches. Quick-reply suggestions generated from conversation context.' },
        { title: 'CRM Sync', desc: 'Real-time bidirectional sync with Echo CRM. New contacts auto-create CRM records with WhatsApp profile data. Conversation transcripts attach to contact timeline. CRM tags and segments push back to WhatsApp for targeted campaigns. Deal stage changes trigger automated WhatsApp follow-ups.' },
        { title: 'Appointment Booking', desc: 'Interactive booking flow: customers select a service from a list message, pick an available date, choose a time slot, and confirm — all within WhatsApp. Calendar integration syncs availability in real time. Automated reminders send 24 hours and 1 hour before the appointment. Rescheduling and cancellation handled through button callbacks.' },
        { title: 'Conversation Analytics', desc: 'Track message volumes, response times, resolution rates, customer satisfaction scores, and agent performance. Breakdown by conversation type (sales, support, booking, general). Peak hour analysis and staffing recommendations. Real-time dashboard with historical trend lines.' },
        { title: 'Compliance and Archival', desc: 'All conversations are archived in D1 with 7-year retention for regulatory compliance. PII is encrypted at rest. Conversation exports in JSON and PDF format for audits. Opt-out handling automatically processes STOP messages and updates the suppression list.' },
      ]}
      apiEndpoints={[
        { method: 'POST', path: '/webhook', desc: 'WhatsApp Cloud API webhook endpoint. Processes incoming messages, delivery receipts, read receipts, and status updates. Validates X-Hub-Signature-256 header.', auth: false },
        { method: 'POST', path: '/api/send', desc: 'Send a message to a WhatsApp number. Supports text, template, image, video, document, interactive buttons, and list messages. Returns wamid (WhatsApp message ID).', auth: true },
        { method: 'POST', path: '/api/broadcast', desc: 'Send a template message to a list of contacts. Parameters: template_name, language, variables per recipient, segment_filter. Throttled to respect Meta rate limits.', auth: true },
        { method: 'POST', path: '/api/templates', desc: 'Create or update a message template. Submits to Meta for approval. Parameters: name, language, category (MARKETING/UTILITY/AUTHENTICATION), components (header, body, footer, buttons).', auth: true },
        { method: 'GET', path: '/api/templates', desc: 'List all message templates with approval status, rejection reasons, and usage statistics. Filter by category and status.', auth: true },
        { method: 'GET', path: '/api/conversations/:phone', desc: 'Retrieve conversation history for a specific phone number. Returns messages with timestamps, delivery status, and metadata. Supports pagination.', auth: true },
        { method: 'GET', path: '/api/analytics', desc: 'Retrieve analytics data: message counts, delivery rates, response times, conversation outcomes, revenue attribution. Supports date range and grouping filters.', auth: true },
        { method: 'GET', path: '/health', desc: 'Health check returning webhook status, Meta API connectivity, message queue depth, D1 health, and recent error counts.' },
      ]}
      userGuide={[
        { id: 'templates', title: 'Message Templates Deep Dive', content: [
          'WhatsApp requires pre-approved message templates for any business-initiated conversation (outside the 24-hour customer service window). Templates have three categories: Marketing (promotions, offers), Utility (order updates, appointment reminders), and Authentication (OTP codes). Each category has different approval criteria and pricing.',
          'A template consists of components: an optional header (text up to 60 chars, or an image/video/document), a body (up to 1024 chars with {{variable}} placeholders), an optional footer (up to 60 chars), and optional buttons (up to 3 quick-reply or 2 call-to-action). Variables are filled dynamically when sending — this is how you personalize "Hi {{1}}, your order {{2}} ships on {{3}}" for each recipient.',
          'Submit templates through the /api/templates endpoint with the full component structure. Meta typically approves within 1-24 hours. If rejected, the response includes the rejection reason (usually policy violations in body text or image content). Approved templates can be sent immediately. Track template performance — open rates, button click rates, and reply rates — through the analytics endpoint to optimize messaging.',
        ]},
        { id: 'conversations', title: 'Managing Customer Conversations', content: [
          'WhatsApp conversations follow a 24-hour window model. When a customer messages your business, a free-tier customer service conversation opens for 24 hours. During this window, you can send unlimited free-form messages (text, media, interactive). After the window closes, you must use an approved template to re-initiate, which starts a new billable conversation.',
          'The bot manages this automatically. It tracks the last customer message timestamp and switches from freeform to template mode when the window expires. AI conversations persist across windows — when a customer returns days later and you send a template to re-engage, the AI loads the previous context from D1 and continues naturally. Customers experience a seamless conversation despite the technical window boundaries.',
          'For complex inquiries that require human intervention, the escalation system routes conversations to live agents. Agents receive a notification with the full conversation transcript and customer profile. The handoff is transparent to the customer — they stay in the same WhatsApp chat. When the agent resolves the issue, they release the conversation back to the bot. All escalation events are tracked for quality analysis.',
        ]},
        { id: 'commerce', title: 'In-Chat Commerce and Payments', content: [
          'WhatsApp Commerce lets customers browse and purchase products without leaving the chat. Start by syncing your product catalog from the Meta Commerce Manager — the bot pulls product IDs, names, descriptions, images, and prices automatically. When a customer asks about a product, the bot sends a rich product message with image, description, price, and an "Add to Cart" action.',
          'Multi-product messages showcase up to 30 items in a scrollable catalog view. Customers tap items to see details and add them to their WhatsApp cart. When they are ready, the cart summary triggers your checkout flow — you generate a payment link (Stripe, PayPal, or custom) and send it as a button message. Payment confirmation webhooks update the order status and trigger fulfillment notifications.',
          'For service businesses, payment links work without a catalog. Generate an invoice with line items, tax calculation, and a payment button. Recurring billing creates subscription records in D1 with auto-renewal reminders sent via template messages. Payment disputes are flagged in the analytics dashboard with the full transaction timeline for resolution.',
        ]},
        { id: 'automation', title: 'Automation Rules and Workflows', content: [
          'The automation engine processes every incoming message through a priority-ordered rule chain. Rules match on keyword (exact, fuzzy, regex), message type (text, image, location, contact), conversation state, contact tags, and time-of-day. When a rule fires, it executes one or more actions: send reply, set contact tag, trigger API webhook, start booking flow, escalate to human, or update CRM.',
          'Workflow sequences chain multiple messages with delays. A post-purchase workflow might send an order confirmation immediately, a shipping update template after 24 hours, a delivery confirmation request after 72 hours, and a review solicitation after 7 days. Each step checks conditions — if the customer already replied negatively, the workflow pauses and escalates instead of blindly proceeding.',
          'Advanced automations use the AI decision engine. Instead of rigid keyword matching, the AI classifies intent and routes to the appropriate workflow. A message like "I need to change my appointment" is classified as a reschedule intent and triggers the booking modification flow, even though it does not contain any predefined keywords. The AI continuously improves classification accuracy from conversation outcomes logged in D1.',
        ]},
      ]}
      aiCapabilities={[
        { capability: 'Conversational Commerce AI', desc: 'Understands purchase intent from natural language. Recommends products based on conversation context and purchase history. Handles objections, compares options, and guides customers through checkout — all within the chat. Conversion rate 3x higher than static catalog browsing.' },
        { capability: 'Intent Classification', desc: 'Classifies every message into business-relevant intents: inquiry, complaint, purchase, booking, cancellation, feedback, escalation. Routes to specialized handlers that resolve most requests without human involvement. Accuracy exceeds 94% across 30+ intent categories.' },
        { capability: 'Smart Auto-Reply Generation', desc: 'When no keyword rule matches, the AI generates contextually appropriate responses using your business knowledge base. It references product specs, policies, FAQs, and prior conversations to produce accurate, on-brand replies. Human agents review AI responses in a feedback loop that improves quality over time.' },
        { capability: 'Sentiment and Urgency Detection', desc: 'Analyzes customer sentiment in real time. Detects frustration, confusion, anger, and satisfaction. Urgent or negative-sentiment conversations are prioritized in the queue and flagged for immediate human review. Sentiment trends are tracked per customer for relationship health scoring.' },
        { capability: 'Language Adaptation', desc: 'Detects the customer language automatically and responds in kind. Supports 25+ languages with natural fluency. Handles code-switching (mixing languages within a conversation) and regional dialect variations. Template messages are sent in the customer preferred language when translations are available.' },
        { capability: 'Predictive Engagement', desc: 'Analyzes customer behavior patterns to predict optimal re-engagement timing. Identifies customers likely to churn and triggers retention campaigns. Recommends the best template, time of day, and offer for each customer segment based on historical response data.' },
      ]}
      troubleshooting={[
        { issue: 'Webhook not receiving messages', solution: 'Verify the webhook URL and verify token in Meta Business Platform settings. The Worker responds to the GET verification challenge with the hub.challenge value — check Cloudflare Worker logs for verification attempts. Ensure the app has the whatsapp_business_messaging permission. Test with a curl POST to the webhook URL to confirm the Worker is reachable.' },
        { issue: 'Template messages rejected by Meta', solution: 'Common rejection reasons: promotional content in UTILITY category, missing opt-out option in MARKETING templates, URL shorteners in buttons, or policy-violating language. Review Meta template guidelines. Resubmit with corrections — each resubmission resets the review queue. Use the /api/templates endpoint to check rejection reasons programmatically.' },
        { issue: 'Messages sent but not delivered', solution: 'Check the message status via the analytics endpoint — look for "sent" vs "delivered" vs "read" statuses. Undelivered messages usually mean the recipient phone number is not on WhatsApp or has blocked your business number. Verify the phone number format includes country code without the + prefix (e.g., 14325551234). Check your Meta API rate limit status — exceeding limits returns 429 errors.' },
        { issue: 'CRM sync missing contacts or conversations', solution: 'The CRM sync runs asynchronously after message processing. Check the sync queue in D1 for pending or failed entries. Verify CRM API credentials in the vault are current. If contacts appear in WhatsApp analytics but not in CRM, check for duplicate phone number normalization issues — the sync deduplicates on E.164 formatted numbers.' },
      ]}
      faq={[
        { q: 'What is the WhatsApp 24-hour conversation window?', a: 'When a customer messages your business, you have 24 hours to reply with free-form messages at no per-message cost. After 24 hours of customer inactivity, the window closes and you must use an approved template message to re-initiate. Templates start a new conversation with category-based pricing (Marketing, Utility, or Authentication rates).' },
        { q: 'How many messages can I send per day?', a: 'New business accounts start with a 250 unique contacts/day limit for business-initiated messages (templates). This increases to 1K, then 10K, then 100K as Meta verifies your message quality. Customer-initiated conversations (replies within the 24-hour window) have no limit. The bot auto-throttles to stay within your current tier.' },
        { q: 'Is WhatsApp end-to-end encrypted with the bot?', a: 'Messages between customers and the WhatsApp Cloud API are encrypted in transit but not end-to-end encrypted in the same way personal WhatsApp messages are. Meta processes messages on their servers before forwarding to your webhook. All messages stored in Echo D1 are encrypted at rest. For regulated industries, the compliance archival feature ensures full audit trails.' },
        { q: 'Can the bot handle multiple WhatsApp numbers?', a: 'Yes. Each WhatsApp Business number is registered as a separate phone_number_id in Meta Business Platform. The Worker routes incoming webhooks by phone_number_id to the correct bot configuration. You can run multiple brands or departments on a single Worker deployment with isolated settings per number.' },
        { q: 'How does the AI know about my business to answer questions?', a: 'Upload your business knowledge base (FAQ document, product specs, policies, pricing) through the /api/knowledge endpoint. The AI retrieves relevant sections when answering customer questions. It never fabricates information — if the answer is not in your knowledge base, it responds with a polite redirect to human support. Knowledge updates take effect immediately.' },
      ]}
    />
  )
}
