'use client'

import ProductDoc from '@/components/ProductDoc'
import type { ProductDocProps } from '@/components/ProductDoc'

const data: ProductDocProps = {
  name: 'Sentinel AI',
  tagline: 'Engine-backed intelligence — 5,486 engines, 611K+ doctrines, domain-expert answers with authority citations.',
  accent: '#14b8a6',
  productUrl: '/sentinel',
  workerUrl: 'https://echo-chat.bmcii1976.workers.dev',
  version: '3.0.0',

  overview: [
    'Sentinel AI is the flagship intelligence interface of Echo Prime Technologies, backed by 5,486 specialized engines spanning law, tax, oilfield, landman, security, medical, financial, and engineering domains. Unlike conventional chatbots that generate plausible-sounding text, Sentinel queries domain-specific doctrine blocks and returns answers grounded in authoritative sources — IRC sections, case law, NIST frameworks, API standards, and regulatory codes.',
    'Every response from Sentinel includes authority citations so professionals can verify the answer against the original source. Confidence levels are stratified into four tiers — DEFENSIBLE, AGGRESSIVE, DISCLOSURE, and HIGH_RISK — giving users a clear picture of how much weight each conclusion carries. For landman and title work, Sentinel connects directly to the async investigation pipeline for full chain-of-title analysis with run sheets, ownership history, and gap detection.',
    'Sentinel is not a toy and not a general-purpose assistant. It is a professional intelligence system designed for domain experts who need accurate, citable answers backed by real doctrine. With 611,000+ indexed doctrines, real-time engine routing, and multi-domain correlation, Sentinel delivers the kind of analysis that previously required a team of specialists and days of research.',
  ],

  gettingStarted: [
    { step: 1, title: 'Navigate to Sentinel', desc: 'Go to /sentinel from the main navigation or click "Try Sentinel AI" from any product page. Sign in with your Echo Prime account to access full engine-backed capabilities.' },
    { step: 2, title: 'Ask a Domain Question', desc: 'Type a question in any supported domain — tax law, oilfield regulations, cybersecurity frameworks, title chain analysis, or financial compliance. Sentinel automatically routes your query to the correct engine cluster.' },
    { step: 3, title: 'Review Authority Citations', desc: 'Every response includes inline citations referencing IRC sections, case law, NIST controls, API specifications, or other authoritative sources. Click any citation to see the full source context and doctrine block.' },
    { step: 4, title: 'Use Title Chain Analysis', desc: 'For landman and title work, ask Sentinel to investigate a property or chain of title. This triggers the async investigation pipeline, which produces a 5-tab report: Summary, Run Sheet, Ownership History, Gaps, and Full Report.' },
    { step: 5, title: 'Configure Confidence Levels', desc: 'Adjust your confidence threshold in settings to filter responses by stratification tier. DEFENSIBLE shows only conclusions backed by strong authority, while AGGRESSIVE includes reasonable interpretations that may carry more risk.' },
  ],

  features: [
    { title: 'Engine-Backed Answers', desc: 'Every response is generated by querying one or more of 5,486 specialized engines, each loaded with domain-specific doctrine blocks. No hallucination — answers are grounded in indexed source material.' },
    { title: 'Authority Citations', desc: 'Inline citations for every claim, referencing IRC sections, case law, NIST frameworks, OSHA standards, API specifications, and other authoritative sources. Fully traceable and verifiable.' },
    { title: 'Title Chain Analysis', desc: 'Automated chain-of-title investigation powered by the Landman Pipeline. Produces professional run sheets, ownership history, gap analysis, and full narrative reports for any property.' },
    { title: 'Confidence Stratification', desc: 'Four-tier confidence system — DEFENSIBLE, AGGRESSIVE, DISCLOSURE, and HIGH_RISK — so users know exactly how much weight each conclusion carries and can make informed decisions.' },
    { title: 'Multi-Domain Intelligence', desc: 'Covers law, tax, oilfield, landman, security, medical, financial, and engineering domains. Sentinel routes queries to the correct engine cluster automatically based on content analysis.' },
    { title: 'IRC/Case Law Citations', desc: 'Deep integration with Internal Revenue Code sections, Tax Court decisions, Revenue Rulings, and Private Letter Rulings. Every tax answer includes the specific IRC section and supporting case law.' },
    { title: 'Real-Time Doctrine Lookup', desc: 'Queries are matched against 611,000+ indexed doctrine blocks in real time. The engine runtime selects the most relevant blocks, ranks them by authority weight, and synthesizes a cited response.' },
    { title: 'Markdown Rendering', desc: 'All responses are rendered with professional markdown formatting including headers, tables, code blocks, lists, and inline citations. The sentinel-md CSS class ensures consistent, readable output.' },
    { title: 'Async Investigation Pipeline', desc: 'Complex queries like title chain analysis run asynchronously with real-time progress updates every 3 seconds. Results are delivered in a structured multi-tab report when complete.' },
    { title: '5-Tab Report View', desc: 'Investigation results are presented in five professional tabs: Summary, Run Sheet, Ownership History, Gaps & Exceptions, and Full Report. Each tab is formatted for direct use in professional deliverables.' },
    { title: 'Session History', desc: 'All conversations are persisted across sessions. Return to any previous investigation, continue a research thread, or export a conversation for team review and collaboration.' },
    { title: 'Export Reports', desc: 'Export any response or investigation report as formatted markdown, PDF-ready output, or structured JSON for integration with downstream systems and professional workflows.' },
  ],

  apiEndpoints: [
    { method: 'POST', path: '/api/chat', desc: 'Send a message to Sentinel AI. Automatically routes to the correct engine cluster based on domain detection. Returns engine-backed response with authority citations.', auth: true },
    { method: 'GET', path: '/api/engines/search', desc: 'Search the engine registry by domain, keyword, or capability. Returns matching engines with metadata, doctrine count, and authority tier.', auth: true },
    { method: 'POST', path: '/api/investigate', desc: 'Start an async investigation (title chain, deep research, multi-source analysis). Returns a job ID for progress polling.', auth: true },
    { method: 'GET', path: '/api/job/:id', desc: 'Poll the status of an async investigation job. Returns progress percentage, current stage, and partial results when available.', auth: true },
    { method: 'GET', path: '/api/engines/stats', desc: 'Retrieve engine statistics — total engines, doctrine count, domain distribution, and query volume. No authentication required for public stats.', auth: false },
    { method: 'POST', path: '/api/query', desc: 'Direct engine query bypassing chat context. Specify engine ID or domain explicitly. Returns raw doctrine matches with authority scores.', auth: true },
    { method: 'GET', path: '/api/doctrines/:engineId', desc: 'List doctrine blocks for a specific engine. Returns block IDs, authority tiers, source references, and indexing timestamps.', auth: true },
    { method: 'GET', path: '/health', desc: 'Health check endpoint. Returns service status, engine count, doctrine index health, and upstream dependency availability.', auth: false },
  ],

  userGuide: [
    {
      title: 'Asking Questions',
      id: 'asking-questions',
      content: [
        'Sentinel works best with specific, domain-focused questions. Instead of "tell me about taxes," ask "What are the IRC Section 1031 requirements for a delayed like-kind exchange involving mineral rights in Texas?" The more specific your question, the more precisely Sentinel can match engine doctrines.',
        'You can ask follow-up questions in the same session and Sentinel will maintain context. If you want to switch domains entirely, start a new conversation thread for the cleanest results.',
        'Natural language works well — you do not need to use legal or technical jargon. Sentinel\'s domain router analyzes intent and routes to the correct engines regardless of how the question is phrased.',
      ],
    },
    {
      title: 'Understanding Confidence Levels',
      id: 'confidence-levels',
      content: [
        'Every Sentinel response includes a confidence stratification tier. DEFENSIBLE means the answer is backed by strong, well-established authority — settled case law, clear IRC provisions, or widely-accepted standards. This is the tier you want for client deliverables and formal opinions.',
        'AGGRESSIVE indicates a reasonable interpretation that pushes the boundaries of established authority. These positions may be supportable but carry higher audit or challenge risk. DISCLOSURE flags positions that require explicit disclosure to clients or regulators. HIGH_RISK identifies conclusions with thin authority support that should be used with extreme caution.',
        'You can filter responses by confidence tier in your account settings. For most professional use, DEFENSIBLE and AGGRESSIVE provide the best balance of utility and reliability.',
      ],
    },
    {
      title: 'Title Chain Investigations',
      id: 'title-chain',
      content: [
        'To start a title chain investigation, simply describe the property or ask Sentinel to investigate a chain of title. Sentinel detects title-related queries automatically and routes them to the Landman Pipeline.',
        'Investigations run asynchronously because they involve querying multiple county records, cross-referencing ownership transfers, and building a complete chain. Progress updates appear every 3 seconds, and the full report is delivered in a 5-tab view when complete.',
        'The Run Sheet tab provides a chronological list of instruments. The Ownership tab shows current and historical ownership. The Gaps tab identifies any breaks or exceptions in the chain. The Full Report tab provides a narrative summary suitable for professional deliverables.',
      ],
    },
    {
      title: 'Reading Authority Citations',
      id: 'authority-citations',
      content: [
        'Authority citations appear inline within Sentinel responses, formatted as bracketed references. Each citation links to the specific doctrine block, IRC section, case, or standard that supports the claim.',
        'Citations include the source type (IRC, case law, NIST, API, OSHA), the specific section or identifier, and an authority weight score. Higher authority weight means stronger precedential value.',
        'When multiple citations support the same conclusion, Sentinel ranks them by authority weight and presents the strongest first. Conflicting authority is flagged explicitly with counter-argument analysis.',
      ],
    },
    {
      title: 'Using Multiple Domains',
      id: 'multi-domain',
      content: [
        'Sentinel excels at cross-domain questions. For example, asking about the tax implications of an oilfield mineral rights transfer will trigger both the tax and landman engine clusters, producing a response that addresses IRC provisions and title chain requirements simultaneously.',
        'The domain router handles multi-domain queries automatically. You can also explicitly reference multiple domains in your question to ensure all relevant engines are consulted.',
        'Cross-domain correlation is one of Sentinel\'s most powerful features — it can identify connections between regulatory frameworks that a single-domain expert might miss.',
      ],
    },
    {
      title: 'Exporting Results',
      id: 'exporting',
      content: [
        'Any Sentinel response or investigation report can be exported for external use. Click the export icon on any message to download it as formatted markdown or structured JSON.',
        'For title chain reports, the export includes all five tabs in a single document formatted for professional deliverables. The markdown output is designed to be directly usable in client reports, memos, and filings.',
        'Exported JSON includes full metadata — engine IDs, doctrine block references, authority scores, and confidence tiers — enabling integration with downstream analysis tools and document management systems.',
      ],
    },
  ],

  aiCapabilities: [
    { capability: 'Domain Routing', desc: 'Automatic query classification and routing to the correct engine cluster. Sentinel analyzes the intent, domain keywords, and context of each question to select from 5,486 specialized engines across 8+ domains.' },
    { capability: 'Doctrine Matching', desc: 'Real-time matching of queries against 611,000+ indexed doctrine blocks. The matching algorithm considers semantic similarity, authority weight, recency, and domain relevance to surface the most applicable doctrines.' },
    { capability: 'Authority Ranking', desc: 'Cited sources are ranked by authority weight — primary authority (statutes, regulations) outranks secondary authority (case law, rulings), which outranks tertiary sources (treatises, guidance). Every citation carries a visible authority score.' },
    { capability: 'Confidence Stratification', desc: 'Four-tier system — DEFENSIBLE (strong authority, low risk), AGGRESSIVE (reasonable interpretation, moderate risk), DISCLOSURE (requires explicit disclosure), and HIGH_RISK (thin authority, use with caution). Applied to every conclusion in every response.' },
    { capability: 'Cross-Domain Correlation', desc: 'Identifies connections across different regulatory and technical frameworks. When a tax question has oilfield implications, or a security question touches on compliance, Sentinel automatically pulls in relevant doctrines from adjacent domains.' },
    { capability: 'Counter-Argument Generation', desc: 'For AGGRESSIVE and higher-risk positions, Sentinel automatically generates counter-arguments and identifies the strongest opposing authority. This ensures users see the full picture before relying on a conclusion.' },
    { capability: 'Chain of Title Analysis', desc: 'Full automated chain-of-title investigation including instrument identification, ownership transfer tracking, gap detection, exception flagging, and professional run sheet generation via the async Landman Pipeline.' },
    { capability: 'Legal Research Synthesis', desc: 'Combines multiple doctrine blocks, IRC sections, case law holdings, and regulatory provisions into a coherent, professionally-written analysis with proper citation formatting and logical structure.' },
  ],

  troubleshooting: [
    { issue: 'No citations appearing in responses', solution: 'Ensure your question is domain-specific enough for Sentinel to route to an engine cluster. Very broad or off-topic questions may fall back to general response mode without engine-backed citations. Try rephrasing with specific legal, tax, or technical terms.' },
    { issue: 'Title chain investigation timeout', solution: 'Title chain investigations run asynchronously and complex chains may take 30-60 seconds. If a job appears stalled, check the progress indicator — some counties have slower record access. If a job fails after 2 minutes, retry with a more specific property description or legal description.' },
    { issue: 'Wrong domain routing', solution: 'If Sentinel routes your question to the wrong engine cluster, add explicit domain keywords to your query. For example, prefix with "Tax question:" or "Landman:" to force correct routing. You can also specify the domain directly in the API query endpoint.' },
    { issue: 'Confidence level seems too low', solution: 'Low confidence (HIGH_RISK or DISCLOSURE) means Sentinel found limited authority support for the conclusion. This is by design — it protects you from over-relying on thin authority. Check if your question is about an emerging area of law or a genuinely unsettled issue where limited authority is expected.' },
  ],

  faq: [
    { q: 'What domains does Sentinel AI cover?', a: 'Sentinel covers 8+ professional domains: tax law (IRC, Tax Court, Revenue Rulings), oilfield operations (API standards, OSHA), landman (title chain, mineral rights, county records), cybersecurity (NIST, CIS, MITRE ATT&CK), medical (clinical guidelines, FDA), financial (SEC, FINRA, compliance), engineering (codes, standards), and general legal research. Each domain is powered by hundreds of specialized engines.' },
    { q: 'How do authority citations work?', a: 'Every claim in a Sentinel response is backed by one or more doctrine blocks from the engine runtime. Each doctrine block references a specific authoritative source — an IRC section, a court case, a NIST control, etc. These references are formatted as inline citations with authority weight scores, allowing you to trace any conclusion back to its source material.' },
    { q: 'How accurate is Sentinel compared to a human expert?', a: 'Sentinel does not replace human expertise — it augments it. The confidence stratification system tells you exactly how reliable each conclusion is. DEFENSIBLE answers are grounded in strong, well-established authority. Sentinel excels at comprehensive research, cross-referencing, and identifying relevant authority that a human researcher might miss. Always apply professional judgment to Sentinel output.' },
    { q: 'Can I use Sentinel offline?', a: 'Sentinel requires an internet connection to query the engine runtime and doctrine index in real time. Exported reports can be saved locally for offline reference, but live querying, investigation pipelines, and real-time doctrine matching all require connectivity to the Echo Prime cloud infrastructure.' },
    { q: 'Is enterprise licensing available?', a: 'Yes. Enterprise plans include dedicated engine capacity, custom domain training, private doctrine ingestion, team management, audit logging, and SLA guarantees. Contact sales@echo-op.com or visit the pricing page for enterprise tier details and volume pricing.' },
    { q: 'How often are the doctrine blocks updated?', a: 'Doctrine blocks are continuously updated as new regulations, case law, standards, and guidance are published. The ingestion pipeline monitors authoritative sources and indexes new material within hours of publication. Engine version history tracks every update so you can see when a doctrine was last refreshed.' },
  ],
}

export default function SentinelDocsPage() {
  return <ProductDoc {...data} />
}
