'use client';

import { useState, useEffect, useCallback } from 'react';
import { ACCENT, GOLD, GOLD_BRIGHT, BG_CARD, BG_INSET, BORDER, HAIR, IVORY, MUTED, BG_DARK } from '../lib/constants';
import { getUser, getFamilyMembers, getMemories, synthesizeSpeech, getGamificationStats, getPersonalityProfile, getDailyBriefing, type Memory, type GamificationStats, type PersonalityProfileResponse, type DailyBriefing } from '../lib/vault-api';
import { playAudioBlob } from '../lib/media';
import VaultIcon from './VaultIcon';

interface Props {
  userId: string;
  onNavigate: (panel: string) => void;
}

interface BriefingSection {
  id: string;
  icon: string;
  title: string;
  content: string;
}

function getGreeting(): string {
  const h = new Date().getHours();
  if (h < 12) return 'Good morning';
  if (h < 17) return 'Good afternoon';
  return 'Good evening';
}

function getDateStr(): string {
  return new Date().toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' });
}

const INSPIRING = [
  "Every story you share is a gift to the future. Keep building your legacy.",
  "The memories you preserve today will bring comfort to generations tomorrow.",
  "Your voice, your wisdom, your love \u2014 all being captured for eternity.",
  "You are creating something truly timeless. Keep going.",
  "Each interview brings you closer to digital immortality.",
];

export default function BriefingPanel({ userId, onNavigate }: Props) {
  const [sections, setSections] = useState<BriefingSection[]>([]);
  const [current, setCurrent] = useState(0);
  const [userName, setUserName] = useState('');
  const [loading, setLoading] = useState(true);
  const [playing, setPlaying] = useState(false);
  const [briefing, setBriefing] = useState<DailyBriefing | null>(null);

  useEffect(() => {
    const load = async () => {
      let name = 'Friend';
      let familyCount = 0;
      let memoryOfDay: Memory | null = null;
      let gamification: GamificationStats | null = null;
      let personality: PersonalityProfileResponse | null = null;

      try {
        const user = await getUser(userId);
        name = user.name || user.email?.split('@')[0] || 'Friend';
        setUserName(name);
      } catch { /* empty */ }

      try {
        const fam = await getFamilyMembers(userId);
        familyCount = fam.members.length;
      } catch { /* empty */ }

      try {
        const mems = await getMemories(userId, undefined, 10);
        if (mems.memories?.length > 0) {
          memoryOfDay = mems.memories[Math.floor(Math.random() * mems.memories.length)];
        }
      } catch { /* empty */ }

      try { gamification = await getGamificationStats(userId); } catch { /* empty */ }
      try { personality = await getPersonalityProfile(userId); } catch { /* empty */ }

      // Sovereign backend briefing: today's nudge questions, generated
      // follow-up, streak, and the memory-care note (graceful if unavailable)
      let serverBriefing: DailyBriefing | null = null;
      try {
        serverBriefing = await getDailyBriefing(userId);
        setBriefing(serverBriefing);
      } catch { /* older backend without briefing */ }

      const built: BriefingSection[] = [
        {
          id: 'greeting',
          icon: 'briefing',
          title: `${getGreeting()}, ${name}`,
          content: serverBriefing?.greeting
            ? `${serverBriefing.greeting} Today is ${getDateStr()}.${serverBriefing.streak_days ? ` You've shared stories on ${serverBriefing.streak_days} day${serverBriefing.streak_days !== 1 ? 's' : ''} this month.` : ''}`
            : `Welcome to your Immortality Vault. Today is ${getDateStr()}. Let's make it count.`,
        },
      ];

      // Follow-up from your last answer (generated by the consciousness engine)
      if (serverBriefing?.follow_up) {
        built.push({
          id: 'follow_up',
          icon: 'chat',
          title: 'Picking up where you left off',
          content: `Last time you talked about "${serverBriefing.follow_up.about.slice(0, 120)}". ${serverBriefing.follow_up.question}`,
        });
      }

      // Vault Progress section (from gamification)
      if (gamification) {
        const score = gamification.consciousness_score ?? 0;
        const unlocked = gamification.achievements?.length ?? 0;
        const total = gamification.available_achievements?.length ?? 0;
        const level = gamification.level ?? 'Newcomer';
        built.push({
          id: 'progress',
          icon: 'progress',
          title: `Vault Progress \u2014 ${level}`,
          content: `Consciousness: ${score}% complete. ${gamification.total_memories ?? 0} memories preserved, ${gamification.total_interviews ?? 0} interviews recorded. ${unlocked}/${total} achievements unlocked, ${gamification.total_points ?? 0} XP earned. ${score < 50 ? 'Keep going \u2014 every story brings you closer to digital immortality!' : score < 80 ? 'Great progress! Your digital self is taking shape.' : 'Impressive! Your consciousness is richly preserved.'}`,
        });
      }

      // Personality Snapshot (from personality profile)
      if (personality && personality.confidence_score > 0) {
        const topTraits: string[] = [];
        for (const [category, traits] of Object.entries(personality.traits || {})) {
          for (const t of traits) {
            if (t.confidence >= 0.5 && t.value >= 0.6) {
              topTraits.push(t.trait_name);
            }
          }
        }
        const traitStr = topTraits.length > 0
          ? `Your top traits: ${topTraits.slice(0, 5).join(', ')}. `
          : '';
        const mood = personality.emotional_profile?.baseline_mood;
        const moodStr = mood ? `Baseline mood: ${mood}. ` : '';
        const pace = personality.voice_pattern?.speech_pace;
        const paceStr = pace ? `Speech style: ${pace} pace${personality.voice_pattern?.uses_contractions ? ', casual' : ', formal'}. ` : '';
        built.push({
          id: 'personality',
          icon: 'personality',
          title: 'Personality Snapshot',
          content: `${traitStr}${moodStr}${paceStr}Based on ${personality.sample_count} analyzed samples with ${Math.round(personality.confidence_score * 100)}% confidence.`,
        });
      }

      built.push(
        {
          id: 'family',
          icon: 'family_vault',
          title: 'Family Summary',
          content: familyCount > 0
            ? `You have ${familyCount} family member${familyCount !== 1 ? 's' : ''} in your vault. Consider adding more to enrich your legacy.`
            : 'Your family vault is waiting. Adding family members unlocks ancestor chat and enriches your consciousness.',
        },
        {
          id: 'memory',
          icon: 'education',
          title: 'Memory of the Day',
          content: memoryOfDay
            ? memoryOfDay.content.slice(0, 300) + (memoryOfDay.content.length > 300 ? '...' : '')
            : 'No memories yet. Start an interview or add a memory to see your daily highlight here.',
        },
        {
          id: 'inspiring',
          icon: 'spark',
          title: 'Daily Inspiration',
          content: serverBriefing?.care_note || INSPIRING[Math.floor(Math.random() * INSPIRING.length)],
        },
      );

      setSections(built);
      setLoading(false);
    };

    load();
  }, [userId]);

  const speakSection = useCallback(async () => {
    if (playing || !sections[current]) return;
    setPlaying(true);
    try {
      const text = `${sections[current].title}. ${sections[current].content}`;
      const blob = await synthesizeSpeech(text, 'warmth');
      await playAudioBlob(blob);
    } catch { /* silent */ }
    setPlaying(false);
  }, [playing, sections, current]);

  if (loading) {
    return (
      <div className="text-center py-12">
        <div className="w-8 h-8 rounded-full animate-spin mx-auto" style={{ border: `2px solid ${HAIR}`, borderTopColor: ACCENT }} />
      </div>
    );
  }

  const section = sections[current];

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="text-center">
        <h2 className="text-3xl font-semibold mb-1" style={{ color: IVORY, fontFamily: 'Cormorant Garamond, Georgia, serif' }}>{getGreeting()}, {userName || 'Friend'}</h2>
        <p className="text-sm" style={{ color: MUTED }}>{getDateStr()}</p>
      </div>

      {/* Briefing Card */}
      {section && (
        <div className="p-8 rounded-2xl text-center" style={{ background: BG_CARD, border: `1px solid ${BORDER}` }}>
          <div className="mb-4 flex justify-center">
            <span className="flex items-center justify-center rounded-full" style={{ width: 60, height: 60, color: ACCENT, background: 'rgba(245,196,81,0.08)', border: `1px solid ${HAIR}` }}>
              <VaultIcon name={section.icon} size={28} />
            </span>
          </div>
          <h3 className="text-lg font-semibold mb-3" style={{ color: IVORY }}>{section.title}</h3>
          <p className="text-base leading-relaxed max-w-lg mx-auto" style={{ color: '#d6cbb6' }}>{section.content}</p>

          {/* Section dots */}
          <div className="flex justify-center gap-2 mt-6">
            {sections.map((_, i) => (
              <button
                key={i}
                onClick={() => setCurrent(i)}
                className="rounded-full transition-all"
                style={{ width: i === current ? 20 : 10, height: 10, background: i === current ? ACCENT : 'rgba(245,196,81,0.22)' }}
              />
            ))}
          </div>

          {/* Navigation */}
          <div className="flex justify-center items-center gap-4 mt-4">
            <button
              onClick={() => setCurrent(Math.max(0, current - 1))}
              disabled={current === 0}
              className="px-3 py-1.5 rounded-full text-xs font-semibold disabled:opacity-30"
              style={{ border: `1px solid ${BORDER}`, color: MUTED }}
            >
              &larr; Prev
            </button>
            <button
              onClick={speakSection}
              disabled={playing}
              className="px-5 py-2.5 rounded-full text-sm font-semibold inline-flex items-center gap-2"
              style={{ background: `linear-gradient(135deg, ${GOLD}, ${GOLD_BRIGHT})`, color: '#20160a' }}
            >
              <VaultIcon name="speaker" size={15} /> {playing ? 'Playing...' : 'Hear This Aloud'}
            </button>
            <button
              onClick={() => setCurrent(Math.min(sections.length - 1, current + 1))}
              disabled={current === sections.length - 1}
              className="px-3 py-1.5 rounded-full text-xs font-semibold disabled:opacity-30"
              style={{ border: `1px solid ${BORDER}`, color: MUTED }}
            >
              Next &rarr;
            </button>
          </div>
        </div>
      )}

      {/* Today's Questions — nudge-selected by the sovereign backend */}
      {briefing && briefing.questions.length > 0 && (
        <div className="p-6 rounded-2xl" style={{ background: BG_CARD, border: `1px solid ${BORDER}` }}>
          <div className="flex items-center justify-between mb-4">
            <h3 className="text-sm font-semibold inline-flex items-center gap-2" style={{ color: IVORY }}><span style={{ color: ACCENT, display: 'flex' }}><VaultIcon name="interview" size={16} /></span> Today&apos;s Questions</h3>
            <span className="text-[10px] uppercase tracking-wider" style={{ color: MUTED }}>picked for your story</span>
          </div>
          <div className="space-y-3">
            {briefing.questions.map(q => (
              <button
                key={q.question_id}
                onClick={() => onNavigate('interview')}
                className="w-full text-left p-4 rounded-xl transition hover:-translate-y-0.5"
                style={{ background: BG_INSET, border: `1px solid ${BORDER}` }}
              >
                <div className="text-sm" style={{ color: '#e6ddcc' }}>{q.question}</div>
                <div className="text-[10px] mt-1" style={{ color: ACCENT }}>
                  {q.category.replace('_', ' ')} · tap to record your answer {'→'}
                </div>
              </button>
            ))}
          </div>
        </div>
      )}

      {/* Quick Actions */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
        {[
          { panel: 'memories', icon: 'crystal', label: 'View Memories' },
          { panel: 'ancestor', icon: 'ancestor', label: 'Talk to Family' },
          { panel: 'interview', icon: 'interview', label: 'Record Stories' },
          { panel: 'chat', icon: 'chat', label: 'Chat with Self' },
        ].map(a => (
          <button
            key={a.panel}
            onClick={() => onNavigate(a.panel)}
            className="p-4 rounded-xl text-center transition hover:-translate-y-0.5"
            style={{ background: BG_CARD, border: `1px solid ${BORDER}` }}
          >
            <div className="mb-1.5 flex justify-center" style={{ color: ACCENT }}><VaultIcon name={a.icon} size={22} /></div>
            <div className="text-xs font-semibold" style={{ color: IVORY }}>{a.label}</div>
          </button>
        ))}
      </div>
    </div>
  );
}
