'use client'

import ProductDoc, { ProductDocProps } from '@/components/ProductDoc'

const data: ProductDocProps = {
  name: 'Echo Calendar',
  tagline: 'Smart scheduling automation — public booking pages, intelligent availability, ICS export, team calendars, and AI scheduling suggestions.',
  accent: '#2563eb',
  productUrl: '/calendar',
  workerUrl: 'https://echo-calendar.bmcii1976.workers.dev',
  version: '1.0.0',

  overview: [
    'Echo Calendar is a smart scheduling platform that eliminates the back-and-forth of appointment booking by letting clients and prospects book directly into your calendar based on your real-time availability. Public booking pages at /book/:cal/:type are globally cached at the edge for instant load times, while smart available slot calculation factors in your availability rules, existing busy events, buffer times between meetings, and maximum bookings per day to ensure your calendar stays sane.',
    'Each booking type is fully configurable: duration (15 minutes to 4 hours), price (free or paid), custom questions the booker must answer, and approval mode (instant confirmation or manual approval with a 24-hour review window). ICS files are generated for every booking so events land in Google Calendar, Outlook, Apple Calendar, or any other calendar client automatically. Cancel and reschedule tokens let bookers self-serve without contacting you.',
    'Team calendar features support group scheduling with role-based access, round-robin assignment, and collective availability (book a time when all required team members are free). Automated email reminders fire from a queue that runs every 15 minutes — reducing no-shows by an average of 67% across platform users. Timezone detection is automatic for bookers, with full timezone support throughout the scheduling flow.',
  ],

  gettingStarted: [
    { step: 1, title: 'Connect Your Calendar', desc: 'Link your Google Calendar or Microsoft Outlook account in Settings > Calendar Connections. Echo Calendar reads your existing events as busy blocks — no details are exposed, only free/busy status. Multiple calendar connections per user are supported so work and personal calendars all block off time simultaneously.' },
    { step: 2, title: 'Set Your Availability Rules', desc: 'Define your working hours in the Availability settings — day of week, start time, end time, and timezone. Create multiple availability schedules for different booking types (e.g., client calls Monday–Wednesday, team syncs Thursday–Friday). Set date-specific overrides for vacations, holidays, or special availability windows.' },
    { step: 3, title: 'Create Booking Types', desc: 'Navigate to Booking Types > New Type. Configure the name, slug (used in your booking URL), duration, description, location (video call link, phone, or in-person address), price, custom intake questions, buffer time before and after, and maximum daily bookings. Each booking type gets its own booking page URL.' },
    { step: 4, title: 'Share Your Booking Page', desc: 'Copy your booking page URL at /book/:calendar-slug/:type-slug and share it anywhere — email signatures, website, LinkedIn, WhatsApp, SMS. The page shows available slots in the booker\'s local timezone automatically. Embed your booking page as an iframe on your website for seamless on-site scheduling.' },
    { step: 5, title: 'Configure Reminders', desc: 'Set up automated email reminders for both the booker and host. Configure reminder timing — e.g., 24 hours before, 1 hour before, 15 minutes before. Customize the reminder email templates. The reminder queue runs every 15 minutes to ensure timely delivery regardless of booking time.' },
    { step: 6, title: 'Enable Team Scheduling', desc: 'Add team members, assign them to specific booking types (round-robin or collective availability), and configure team roles. Round-robin assignment rotates bookings evenly across team members. Collective mode requires all assigned members to be free for a slot to appear.' },
  ],

  features: [
    { title: 'Public Booking Pages', desc: 'Beautiful, mobile-optimized booking pages at /book/:cal/:type that load in under 200ms globally via edge caching. Show available slots in the booker\'s detected timezone. Customizable with your logo, brand colors, welcome message, and booking type details. Each booking type has its own dedicated URL for direct sharing.' },
    { title: 'Smart Available Slot Calculation', desc: 'Availability engine calculates bookable slots by intersecting four data sources: your availability schedule (working hours), connected calendar busy events (from Google/Outlook), buffer time rules (blocks before/after each booking), and daily booking caps (maximum bookings per day per type). The result is a real-time grid of open slots that never double-books.' },
    { title: 'ICS Export', desc: 'Every confirmed booking generates an ICS calendar invite file automatically sent to both the booker and the host. The ICS includes event title, description, location, video call link, and all custom question answers. Works with Google Calendar, Microsoft Outlook, Apple Calendar, Yahoo Calendar, and any ICS-compatible calendar client.' },
    { title: 'Cancel and Reschedule Tokens', desc: 'Every booking confirmation email includes unique, time-limited cancel and reschedule links. Bookers can self-serve without contacting you — click reschedule to select a new available slot, click cancel to release the time. Hosts are notified of all changes. Cancellation policies (e.g., no cancellations within 2 hours of the meeting) are enforced automatically.' },
    { title: 'Configurable Booking Types', desc: 'Each booking type is fully independent: unique duration, price, location, custom intake questions (text, select, checkbox, file upload), buffer times, daily booking cap, approval mode (instant or manual), advance notice requirement (minimum time before booking), and maximum advance window (how far ahead bookings are accepted). Link booking types to specific team members or round-robin pools.' },
    { title: 'Team Calendars with Roles', desc: 'Organize team members into calendars with admin, member, and view-only roles. Admins manage booking types and availability for the team calendar. Members have their own availability linked to the team. View-only users can see the booking schedule without managing it. Perfect for scheduling teams, customer success managers, or service providers.' },
    { title: 'Round-Robin Assignment', desc: 'Distribute bookings evenly across team members without manual intervention. Round-robin logic tracks the last booking assigned to each member and rotates to the next available member in sequence. Weighted round-robin lets you assign a higher proportion of bookings to senior team members. Skip-if-unavailable ensures a member won\'t receive a booking if they\'re marked busy for that slot.' },
    { title: 'Automated Email Reminders', desc: 'Configurable multi-stage reminder sequences for both host and booker. Set reminders at any interval before the booking: common configurations include 48 hours, 24 hours, and 1 hour. Reminder templates support personalization tokens (booker name, meeting type, date/time, location, meeting link). The reminder queue runs every 15 minutes for precise delivery timing.' },
    { title: 'Recurring Event Support', desc: 'Create recurring booking series with configurable recurrence rules: daily, weekly, bi-weekly, monthly, and custom intervals. Set an end date, number of occurrences, or leave open-ended. Each occurrence in a series can be individually cancelled or rescheduled without affecting the rest of the series. Recurring events are shown as a single booking in the management interface with a drill-down to individual occurrences.' },
    { title: 'Timezone Intelligence', desc: 'Automatically detects the booker\'s timezone from browser locale and displays all available slots in their local time. Hosts see bookings in their own timezone. All times are stored internally in UTC with full timezone metadata. Timezone display can be overridden by the booker in the booking flow. Daylight saving time transitions are handled automatically for all supported timezones.' },
    { title: 'Paid Bookings', desc: 'Charge for appointments directly on the booking page using Stripe. Set a price per booking type. Bookers enter payment details during the booking flow — the appointment is only confirmed on successful payment. Configurable deposit options (pay full amount or a deposit with remainder due at the appointment). Refunds processed automatically for cancelled bookings within your refund window.' },
    { title: 'Booking Analytics', desc: 'Track booking volume, show rate, no-show rate, average lead time, peak booking days/times, top booking sources (referrer tracking), and team utilization rates. Export booking data for any date range. Funnel analytics show drop-off at each step of the booking flow to identify optimization opportunities in your booking page UX.' },
  ],

  apiEndpoints: [
    { method: 'GET', path: '/book/:cal/:type', desc: 'Public booking page. Returns HTML — the full booking flow for a specific calendar and booking type. Detects booker timezone from Accept-Language header. No auth required.', auth: false },
    { method: 'GET', path: '/api/availability/:cal/:type', desc: 'Get available booking slots for a calendar and type in a date range. Returns array of ISO 8601 datetime slots in UTC. Query params: start_date, end_date, timezone.', auth: false },
    { method: 'POST', path: '/api/bookings', desc: 'Create a new booking. Provide calendar_id, type_id, start_time (UTC ISO 8601), booker details (name, email), and answers to intake questions. Returns booking confirmation with ICS attachment URL and cancel/reschedule tokens.', auth: false },
    { method: 'GET', path: '/api/bookings', desc: 'List all bookings for the authenticated calendar owner. Filter by status, booking type, date range, and team member. Includes booker details and intake responses.', auth: true },
    { method: 'DELETE', path: '/api/bookings/:id', desc: 'Cancel a booking. Provide reason. Sends cancellation notifications to host and booker. Releases the time slot immediately for rebooking.', auth: true },
    { method: 'POST', path: '/api/bookings/:id/reschedule', desc: 'Reschedule a booking to a new time. Provide new_start_time (UTC ISO 8601). Validates new slot is available. Sends updated ICS to both parties.', auth: true },
    { method: 'GET', path: '/api/cancel/:token', desc: 'Public cancel endpoint — validates cancel token and shows confirmation page. No auth required (token is the credential). GET returns confirmation UI.', auth: false },
    { method: 'POST', path: '/api/cancel/:token', desc: 'Submit cancellation using a cancel token from booking confirmation email. Returns cancellation confirmation and initiates refund if applicable.', auth: false },
    { method: 'GET', path: '/api/booking-types', desc: 'List all booking types for the authenticated calendar with configuration details, slug, pricing, and active status.', auth: true },
    { method: 'GET', path: '/api/analytics', desc: 'Booking analytics for the authenticated account. Query params: start_date, end_date, type_id, member_id. Returns booking volume, show rate, no-show rate, and utilization metrics.', auth: true },
  ],

  userGuide: [
    {
      id: 'availability-configuration',
      title: 'Configuring Availability and Scheduling Rules',
      content: [
        'Your availability configuration is the foundation of the entire scheduling system. Navigate to Settings > Availability to define your base schedule — the days and hours you\'re available to take bookings. You can create multiple named availability schedules: for example, "Client Calls" (Mon–Wed, 9am–12pm) and "Internal Meetings" (Thu–Fri, 10am–3pm). Each booking type links to one availability schedule.',
        'Connected calendar busy events are automatically respected. When a meeting appears on your Google Calendar or Outlook, that time becomes unavailable for bookings without any manual action. If you have multiple calendar connections (work + personal), all are checked simultaneously. The system only reads free/busy status — event titles, descriptions, and attendees are never accessed.',
        'Date-specific overrides let you adjust availability for individual days without changing your base schedule. Add a day off (blocks all bookings on a specific date), an extended availability window (adds booking hours outside your normal schedule for a special event), or a reduced availability window (shortens available hours for a lighter day). Overrides appear highlighted on your calendar view and can be set up to 12 months in advance.',
      ],
    },
    {
      id: 'booking-types',
      title: 'Creating and Optimizing Booking Types',
      content: [
        'Booking types are the building blocks of your scheduling system — each one represents a distinct appointment format. Best practice is to create specific booking types for each use case rather than one generic "meeting": Discovery Call (30 min, free, video), Technical Demo (60 min, free, video with pre-screening questions), Paid Consultation (90 min, $150, Stripe payment required), and In-Person Visit (60 min, address location). Each type\'s unique slug becomes part of its booking URL.',
        'Intake questions dramatically improve meeting quality by collecting context before the call. Supported question types include short text (e.g., "What\'s your main challenge?"), long text (e.g., "Describe your current process"), single-select dropdown (e.g., "Company size: 1–10, 11–50, 51–200, 200+"), multi-select, checkbox (e.g., "I agree to the consultation terms"), and file upload (e.g., "Upload your project brief"). Mark critical questions as required to prevent incomplete bookings.',
        'Buffer times protect your focus and transition time. Set a "before" buffer (blocks N minutes before the appointment so you can prepare) and an "after" buffer (blocks N minutes after for notes and follow-up). For back-to-back meeting types, a 10-minute buffer is recommended. For travel-required appointments, set buffers to match your realistic travel time. Buffers appear as busy on your connected calendar automatically.',
      ],
    },
    {
      id: 'team-scheduling',
      title: 'Setting Up Team Calendars and Round-Robin',
      content: [
        'Team calendars let multiple people share a single booking URL while distributing work intelligently. Navigate to Team > New Calendar to create a team calendar. Add team members, assign each a role (admin, member), and set each member\'s individual availability within the team calendar context. Members can override the team availability schedule with their own personal schedule if needed.',
        'Round-robin assignment is the most common team scheduling mode. When a booking comes in, the system evaluates which team members are available for the requested time and assigns the booking to the next member in rotation who is free. This distributes bookings evenly over time without any manual work. The assignment log shows every booking assignment with the reason for selection, so you can verify the rotation is working as expected.',
        'Collective availability mode is used when all assigned team members must be present — for example, a panel interview or a kickoff call with the full account team. In collective mode, a time slot only appears as available if every assigned team member is simultaneously free. This prevents the impossible scenario where only some required participants can attend. Use it sparingly — collective requirements significantly reduce available slots.',
      ],
    },
    {
      id: 'reminder-setup',
      title: 'Automating Reminders to Reduce No-Shows',
      content: [
        'No-shows are costly — they waste your time and reduce revenue for paid bookings. Echo Calendar\'s automated reminder system reduces no-show rates significantly by sending timely, personalized reminders at intervals you configure. Navigate to Settings > Reminders to set up your reminder sequence. A proven sequence is: confirmation email immediately after booking, reminder 24 hours before, and final reminder 1 hour before.',
        'Reminder emails support personalization tokens that auto-fill from the booking record: {{booker_name}}, {{meeting_type}}, {{date}}, {{time}}, {{timezone}}, {{location}}, {{meeting_link}}, {{host_name}}, and {{cancel_link}}. The cancel link in reminders makes it easy for bookers who can\'t make it to cancel early rather than simply not showing up — giving you time to fill the slot with another booking.',
        'The reminder queue runs every 15 minutes, checking for bookings within the reminder window and sending pending reminders. This means your reminders fire within 15 minutes of their scheduled time regardless of when the booking was made. For same-day bookings, the reminder system intelligently skips past reminders — if a booking is made 2 hours before the meeting, only the 1-hour reminder fires, not the 24-hour reminder that would already be in the past.',
      ],
    },
    {
      id: 'paid-bookings',
      title: 'Paid Booking Setup and Refund Management',
      content: [
        'Paid bookings require a Stripe account connected in Settings > Payments. Once connected, set a price on any booking type — Stripe Checkout handles the payment flow during booking. The appointment is only confirmed after successful payment authorization. Test mode is available using Stripe\'s test card numbers (4242 4242 4242 4242) before enabling live payments.',
        'Deposit bookings let you collect a partial payment upfront with the remainder due at the appointment. Configure the deposit amount (fixed or percentage) and the due-date behavior for the remaining balance. Bookers receive a payment link for the balance in the reminder email N days before the appointment, with a deadline to prevent same-day non-payment issues.',
        'Refund policies are configured per booking type: full refund up to N hours before the appointment, partial refund (configurable percentage) within the cancellation window, or no refund policy. When a cancellation occurs within your refund window, Echo Calendar automatically processes the appropriate Stripe refund based on your policy — no manual action required. Refund receipts are sent to the booker automatically.',
      ],
    },
  ],

  aiCapabilities: [
    { capability: 'AI Scheduling Suggestions', desc: 'Analyzes your booking history, meeting outcomes, and calendar patterns to recommend optimal scheduling configurations. Suggests the best days and times for different meeting types based on when your previous meetings of that type were most productive (measured by meeting length vs. scheduled duration, follow-up email volume, and subsequent booking rate).' },
    { capability: 'Smart Availability Optimization', desc: 'Reviews your availability schedule against your actual booking patterns to identify inefficiencies: availability windows with zero or near-zero bookings (suggesting you could safely reduce them), types that frequently hit the daily booking cap (suggesting the cap is too low), and times where buffer rules are longer than the average gap between meetings (suggesting buffers could be reduced).' },
    { capability: 'No-Show Risk Prediction', desc: 'Scores each upcoming booking for no-show risk based on signals: time between booking and appointment (same-day bookings have 3x higher no-show rates), booker engagement (did they open the confirmation email, click the calendar invite), whether contact information is complete, and historical patterns for the booking type and lead time combination. High-risk bookings trigger an additional reminder automatically.' },
    { capability: 'Intake Question Intelligence', desc: 'Analyzes the content of intake question responses across your bookings to identify patterns: questions that consistently produce long, detailed responses (high-value qualifiers), questions most often left blank by bookers (indicating friction), and response patterns that correlate with meeting outcomes. Recommends intake question optimizations to improve pre-meeting qualification.' },
    { capability: 'Meeting Load Balancing', desc: 'For team calendars, the AI load balancing engine goes beyond simple round-robin by factoring in each team member\'s recent meeting load, expertise match for the booking type, current pipeline value in their queue, and booking outcome history. Recommends assignment adjustments when a team member is consistently overbooked or underutilized relative to their capacity.' },
    { capability: 'Booking Page Conversion Optimization', desc: 'Tracks the full funnel from booking page view to confirmed booking and identifies drop-off points: which step in the booking flow most bookers abandon, which time slots are offered but rarely selected (suggesting they\'re not truly convenient), and which intake questions cause abandonment. Provides specific A/B test recommendations to improve booking conversion rates.' },
  ],

  troubleshooting: [
    { issue: 'No available slots showing on booking page', solution: 'Verify your availability schedule is active and includes the date range being viewed. Check that your connected calendar(s) don\'t have all-day events blocking the entire day — some calendar apps create broad busy blocks for all-day events. Confirm the booking type\'s advance notice requirement isn\'t preventing near-term slots from showing (e.g., a 48-hour advance requirement means nothing today or tomorrow appears). Check the daily booking cap — if you\'ve already hit the maximum bookings for a day, no more slots show for that day. Use the Availability Debugger in Settings to step through the slot calculation for a specific date.' },
    { issue: 'ICS calendar invites not adding to Google Calendar or Outlook', solution: 'Ensure the ICS file is being sent as an email attachment with Content-Type: text/calendar. For Google Workspace and Microsoft 365 tenants with strict email filtering, the ICS may be quarantined — check your email security settings and add Echo Calendar\'s sending domain to the allowlist. The booker can also manually download the ICS from their booking confirmation page at any time. If the event adds but shows in the wrong timezone, verify that your booking type\'s timezone is set correctly in booking type settings.' },
    { issue: 'Payments failing on paid booking types', solution: 'Verify your Stripe connection status in Settings > Payments — the connection may need re-authorization if your Stripe OAuth token has expired. Ensure your Stripe account is fully activated (not still in test mode if you\'re trying to charge live cards). Check that the Stripe webhook endpoint is configured correctly in your Stripe dashboard to point at the Echo Calendar webhook URL shown in Settings > Payments > Webhook Setup. Test with Stripe\'s test card number (4242 4242 4242 4242) in test mode to confirm the integration is working before switching to live mode.' },
    { issue: 'Reminder emails not being sent', solution: 'Check the reminder configuration for the affected booking type — verify reminders are enabled and the timing rules are set correctly. The reminder queue runs every 15 minutes; if a reminder was due very recently it may not have fired yet. Check that the booker\'s email address was captured correctly during booking (visible in the booking detail view). For bulk reminder delivery issues, check Settings > Email Delivery for any bounce or spam complaints that may have triggered a sending pause on your account.' },
    { issue: 'Round-robin not distributing bookings evenly', solution: 'Round-robin balance is calculated based on confirmed bookings, not just the last assignment. If one team member has been blocking availability heavily (many busy events), they will receive fewer bookings automatically because fewer slots are available to assign to them. View each team member\'s booking count in Team > Analytics to see the distribution. If you need to manually rebalance, use the "Reset Round-Robin Position" option in Team > Settings which sets all members back to the same position in the rotation.' },
  ],

  faq: [
    { q: 'Which calendar systems does Echo Calendar integrate with?', a: 'Echo Calendar integrates natively with Google Calendar (via OAuth) and Microsoft Outlook/Exchange (via Microsoft Graph OAuth). Read/write access creates bookings directly in your connected calendar and reads existing events as busy blocks. CalDAV-compatible calendars (Apple iCloud, Fastmail, Proton Calendar) are supported via manual CalDAV connection. For other systems, the ICS file generated for every booking works as a universal calendar format compatible with virtually any calendar application.' },
    { q: 'Can a booker book on behalf of someone else?', a: 'Yes. The booking form collects the booker\'s contact information but you can add a "Meeting is for" field as a custom intake question. The confirmation and ICS are sent to the email address entered in the booking form. For corporate use cases where an assistant books on behalf of an executive, we recommend using the "attendee" field in the booking form — the assistant enters their own email for communications but specifies the executive\'s details as the meeting attendee.' },
    { q: 'How does timezone detection work for international bookers?', a: 'Echo Calendar automatically detects the booker\'s timezone from their browser locale settings and displays all available slots in that timezone. The detected timezone is shown at the top of the booking calendar so the booker can verify or change it. All times are stored and processed internally in UTC. Confirmation emails and ICS files include the time in the booker\'s local timezone with the UTC offset clearly stated to prevent confusion across timezone boundaries.' },
    { q: 'Can I embed the booking page on my website?', a: 'Yes. Every booking page can be embedded as an iframe on your website. Copy the embed code from the booking type settings — it\'s a standard iframe snippet with the booking page URL. The booking page is responsive and adapts to any container width. For a seamless look, use the white-label option (Pro/Enterprise) to remove Echo Calendar branding from embedded booking pages. Advanced embed options include pre-filling specific fields via URL parameters for context-aware booking flows.' },
    { q: 'What happens when a booking is cancelled or rescheduled?', a: 'When a booking is cancelled (by host, booker, or via cancel token), both parties receive a cancellation confirmation email, the slot is immediately released for rebooking, and any paid booking refund is processed per your configured policy. When rescheduled, a new ICS file with the updated time is sent to both parties, the old slot is released, and the booking record is updated with the rescheduling history. All changes are logged with the actor identity and timestamp.' },
    { q: 'Is there a limit on how many bookings I can receive?', a: 'There is no monthly booking limit on any plan. Free plans include 1 booking type and 1 team member. Pro plans include 20 booking types and 10 team members. Enterprise plans have unlimited booking types and team members. All plans include full reminder automation, ICS generation, timezone support, and the full booking flow regardless of booking volume.' },
  ],
}

export default function EchoCalendarDocsPage() {
  return <ProductDoc {...data} />
}
