'use client'

import ProductDoc from '@/components/ProductDoc'

export default function PriceAlertsDocPage() {
  return (
    <ProductDoc
      name="Echo Price Alerts"
      tagline="AI-powered price monitoring — track commodities, crypto, stocks, competitors, and custom data sources with real-time multi-channel alerts."
      accent="#ea580c"
      productUrl="/price-alerts"
      workerUrl="https://echo-price-alerts.bmcii1976.workers.dev"
      version="2.2.0"
      overview={[
        'Echo Price Alerts is a comprehensive market monitoring platform that tracks prices across commodities (WTI crude, natural gas, gold, silver, copper), cryptocurrencies (BTC, ETH, SOL, and 500+ altcoins), equities (US stocks, ETFs, indices), and competitor products. When prices cross your configured thresholds — above, below, percentage change, or custom conditions — the system fires alerts instantly via SMS, email, Telegram, WhatsApp, Slack, webhook, or any combination.',
        'The monitoring engine runs on Cloudflare Workers with Cron Triggers polling data sources at configurable intervals from 1 minute to 24 hours. Price data is sourced from multiple providers for reliability: CoinGecko and Binance for crypto, Alpha Vantage and Yahoo Finance for equities, EIA and Quandl for commodities. When a primary source fails, the system falls back automatically to secondary sources with no gap in coverage. All price data is stored in D1 with full historical depth for charting and trend analysis.',
        'Beyond simple threshold alerts, the AI layer adds intelligent capabilities: trend detection identifies emerging patterns before they hit your thresholds, anomaly detection flags unusual price movements that deviate from historical norms, correlation analysis shows how your watched assets move together, and predictive alerts estimate when a price is likely to hit your target based on current momentum. The platform serves both individual traders watching personal portfolios and businesses monitoring input costs, competitor pricing, and market conditions.',
      ]}
      gettingStarted={[
        { step: 1, title: 'Create Your Watchlist', desc: 'Add assets to your watchlist by searching for ticker symbols, commodity names, or competitor product URLs. Each asset shows the current price, 24-hour change, and a sparkline chart. You can organize assets into groups (My Portfolio, Competitors, Commodities) for easy management.' },
        { step: 2, title: 'Set Up Alert Rules', desc: 'For each watched asset, create alert rules. Choose the condition type: price above/below a threshold, percentage change within a time window, or crossing a moving average. Set the notification channels (SMS, email, Telegram, Slack, webhook) and frequency (once, every occurrence, or daily digest).' },
        { step: 3, title: 'Configure Notification Channels', desc: 'Connect your notification channels: verify your phone number for SMS, confirm your email, link your Telegram account via @EchoPriceBot, add the Slack app to your workspace, or enter webhook URLs for custom integrations. Each channel can be enabled or disabled per alert rule.' },
        { step: 4, title: 'Review Historical Data', desc: 'Open the chart view for any watched asset to see historical price data with your alert thresholds overlaid. Zoom from 1-hour to 5-year views. Technical indicators (SMA, EMA, RSI, MACD, Bollinger Bands) are available as overlays. Historical alert triggers are marked on the timeline.' },
        { step: 5, title: 'Enable AI Insights', desc: 'Toggle AI Insights to receive proactive analysis: trend detection alerts when a watched asset enters an uptrend or downtrend, anomaly alerts for unusual volume or price spikes, and predictive alerts estimating when assets will hit your target prices. AI insights are delivered alongside your regular alerts.' },
      ]}
      features={[
        { title: 'Price Tracking', desc: 'Real-time and near-real-time price tracking for 500+ crypto tokens, 8,000+ US equities, 50+ commodities, and unlimited custom data sources. Polling intervals from 1 minute (crypto) to 15 minutes (equities) to 1 hour (commodities). Current price, 24h change, 7d change, and 30d change displayed per asset.' },
        { title: 'Threshold Alerts', desc: 'Set alerts for price above, price below, percentage change up, percentage change down, and crossing moving averages (SMA/EMA 20, 50, 100, 200). Alerts fire once or on every occurrence. Cooldown periods (1 min to 24 hours) prevent alert storms. Compound conditions combine multiple rules with AND/OR logic.' },
        { title: 'Competitor Monitoring', desc: 'Track competitor product pricing by providing product URLs. The scraper engine checks prices on a configurable schedule and alerts on changes. Supports Amazon, Walmart, eBay, Shopify stores, and custom e-commerce sites. Price history is charted alongside your own product pricing for margin analysis.' },
        { title: 'Commodity Prices', desc: 'Specialized tracking for energy (WTI crude, Brent crude, natural gas, heating oil), metals (gold, silver, platinum, copper, aluminum), agriculture (corn, wheat, soybeans, cotton, coffee), and livestock. Data from EIA, USDA, and commodity exchanges. Futures contract pricing with expiration date tracking.' },
        { title: 'Crypto Alerts', desc: 'Coverage for 500+ cryptocurrencies with data from CoinGecko, Binance, and Coinbase. Track spot prices, 24h volume, market cap, and circulating supply. DeFi token support includes DEX prices and liquidity pool depth. Gas price tracking for Ethereum, Polygon, and Arbitrum networks.' },
        { title: 'Stock Tracking', desc: 'US equities from NYSE, NASDAQ, and AMEX. Pre-market and after-hours price monitoring. Earnings date alerts and earnings surprise notifications. Dividend tracking with ex-date and payment date alerts. Sector-level index tracking (S&P 500, NASDAQ 100, Dow 30, Russell 2000).' },
        { title: 'Historical Charts', desc: 'Interactive price charts with adjustable timeframes: 1H, 4H, 1D, 1W, 1M, 3M, 1Y, 5Y, and ALL. Candlestick and line chart modes. Technical indicator overlays: SMA, EMA, RSI, MACD, Bollinger Bands, Volume, VWAP. Alert thresholds displayed as horizontal lines. Export charts as PNG or CSV data.' },
        { title: 'SMS and Email Notifications', desc: 'SMS alerts via Twilio deliver to any mobile number worldwide with sub-10-second latency. Email alerts include price details, chart thumbnail, and direct links to the dashboard. Both channels support HTML and plain-text formatting. Delivery receipts tracked for reliability monitoring.' },
        { title: 'API Webhooks', desc: 'Fire webhooks to any URL when alerts trigger. Payload includes asset symbol, price, condition met, timestamp, and custom metadata you define. Retry logic with exponential backoff (3 attempts). Webhook signatures (HMAC-SHA256) for payload verification. Ideal for connecting to trading bots, spreadsheets, and custom dashboards.' },
        { title: 'Custom Conditions', desc: 'Advanced alert builder for complex conditions: price of Asset A relative to Asset B (ratio alerts), spread between two prices, volume spike detection, RSI overbought/oversold, and custom formula evaluation. Conditions are evaluated server-side at the polling interval without requiring a browser session.' },
        { title: 'Portfolio Valuation', desc: 'Enter your holdings (quantity per asset) and track total portfolio value in real time. Set alerts on portfolio-level thresholds: total value above/below, daily P&L exceeding a threshold, and allocation drift from target percentages. Portfolio performance compared against benchmarks (S&P 500, BTC).' },
        { title: 'Multi-Asset Dashboards', desc: 'Customizable dashboards showing all watched assets in a grid view with real-time price tiles, sparkline charts, and alert status indicators. Drag-and-drop layout. Multiple dashboard tabs for different contexts (Trading, Commodities, Competitors). Auto-refresh every 60 seconds or on-demand.' },
      ]}
      apiEndpoints={[
        { method: 'GET', path: '/api/prices/:symbol', desc: 'Get current price, 24h change, 7d change, volume, and market cap for any tracked asset. Symbol format: BTC, AAPL, CL=F (crude oil). Returns the most recent data point.', auth: false },
        { method: 'GET', path: '/api/history/:symbol', desc: 'Get historical price data. Parameters: interval (1m, 5m, 1h, 1d), from, to. Returns OHLCV data. Max 1000 data points per request. Supports pagination.', auth: true },
        { method: 'POST', path: '/api/alerts', desc: 'Create a new alert rule. Parameters: symbol, condition (above/below/pct_change/cross_sma), threshold, channels (sms/email/telegram/slack/webhook), cooldown, metadata.', auth: true },
        { method: 'GET', path: '/api/alerts', desc: 'List all configured alerts with status (active/triggered/paused), last triggered timestamp, trigger count, and configuration details. Supports filtering by symbol and status.', auth: true },
        { method: 'DELETE', path: '/api/alerts/:id', desc: 'Delete an alert rule by ID. Returns confirmation. Triggered history for the alert is preserved in the audit log.', auth: true },
        { method: 'GET', path: '/api/portfolio', desc: 'Get portfolio valuation with per-asset breakdown: quantity, current price, value, daily P&L, allocation percentage. Total portfolio value and benchmark comparison.', auth: true },
        { method: 'POST', path: '/api/webhook-test', desc: 'Send a test payload to a webhook URL to verify connectivity and payload format. Returns delivery status and response code from the target.', auth: true },
        { method: 'GET', path: '/health', desc: 'Health check returning service status, data source connectivity (CoinGecko, Alpha Vantage, EIA), active alert count, last poll timestamp, and queue depth.' },
      ]}
      userGuide={[
        { id: 'watchlist', title: 'Building Your Watchlist', content: [
          'Your watchlist is the foundation of the alert system. Search for any asset by name, ticker symbol, or category. Crypto assets use their standard symbols (BTC, ETH, SOL). Equities use exchange symbols (AAPL, MSFT, TSLA). Commodities use futures codes (CL=F for crude oil, GC=F for gold, NG=F for natural gas). Once added, the asset appears on your dashboard with live pricing.',
          'Organize assets into custom groups for clarity. A common setup: one group for your investment portfolio, one for commodities relevant to your business (a drilling company might track WTI, natural gas, steel, and diesel), one for competitor products, and one for macro indicators (DXY dollar index, 10-year Treasury yield, VIX). Groups can be reordered and renamed at any time.',
          'For competitor product monitoring, paste the product URL directly into the watchlist search. The scraper identifies the price element on the page and begins tracking it. Supported platforms include Amazon, Walmart, eBay, Best Buy, and most Shopify-powered stores. For unsupported sites, use the custom scraper configuration to specify a CSS selector or XPath for the price element.',
        ]},
        { id: 'alerts', title: 'Configuring Alert Rules', content: [
          'Each watchlist asset can have multiple independent alert rules. The simplest rule is a price threshold: alert me when BTC drops below $60,000 or when crude oil goes above $85/barrel. Percentage-change alerts fire when an asset moves more than a specified percentage within a time window — useful for catching sudden spikes or drops without setting a fixed price level.',
          'Moving average crossover alerts fire when the price crosses above or below a selected moving average (SMA or EMA, periods 20/50/100/200). These are popular technical analysis signals. The RSI alert triggers when the Relative Strength Index enters overbought (above 70) or oversold (below 30) territory. Combine multiple conditions with AND/OR logic for sophisticated strategies — for example, alert when RSI is below 30 AND price is above the 200-day SMA.',
          'Cooldown periods prevent alert fatigue. If BTC oscillates around your $60,000 threshold, a 1-hour cooldown means you get at most one alert per hour instead of one every polling cycle. For trading signals, set cooldown to 0 for immediate alerts on every trigger. For informational monitoring, daily digest mode batches all triggered alerts into a single morning email summary.',
        ]},
        { id: 'channels', title: 'Notification Channel Setup', content: [
          'SMS is the fastest channel for critical alerts — messages arrive within 10 seconds of the trigger event via Twilio. Add your phone number in settings, verify the OTP code, and SMS is ready. International numbers are supported. Each SMS includes the asset symbol, current price, condition triggered, and a short URL to the dashboard. SMS costs are included in your plan quota.',
          'Email notifications provide more detail: the alert summary, a price chart thumbnail showing the last 24 hours with the trigger point marked, related asset performance, and direct links to the dashboard. Emails support HTML formatting for clean readability. Configure a dedicated email address or use your account email. Email is the default channel for digest-mode alerts.',
          'Telegram alerts are delivered via @EchoPriceBot — link your Telegram account in settings, start a chat with the bot, and send /connect followed by your account token. Slack integration uses the Echo Price Alerts app — install it to your workspace and select the channel for alert delivery. Webhooks deliver structured JSON payloads to any URL you specify, enabling integration with trading bots, Google Sheets, Zapier, and custom automation systems.',
        ]},
        { id: 'analysis', title: 'Charts and Technical Analysis', content: [
          'The chart view provides interactive price visualization for every tracked asset. Switch between line charts (clean trend view) and candlestick charts (OHLC detail for trading analysis). Timeframes range from 1-hour intraday to 5-year historical. The chart auto-scales to fit the selected range and supports pinch-zoom on mobile and scroll-zoom on desktop.',
          'Overlay technical indicators by clicking the Indicators button: Simple Moving Average (SMA) and Exponential Moving Average (EMA) in periods of 20, 50, 100, and 200 days. Relative Strength Index (RSI) displays as a separate panel below the main chart. MACD shows signal line crossovers. Bollinger Bands overlay standard deviation channels. Volume bars display below the price chart by default.',
          'Your alert thresholds are drawn as horizontal lines on the chart, color-coded by alert type (red for price-below, green for price-above, blue for moving average). Historical trigger points are marked with icons on the timeline, so you can see exactly when past alerts fired in relation to price action. Export the chart as a PNG image or download the underlying data as a CSV file for offline analysis.',
        ]},
      ]}
      aiCapabilities={[
        { capability: 'Trend Detection', desc: 'Identifies emerging uptrends and downtrends before they reach your threshold alerts. Uses a combination of moving average convergence, volume analysis, and momentum indicators. Sends proactive alerts like "BTC entering potential uptrend — price has crossed above the 50-day SMA with increasing volume."' },
        { capability: 'Anomaly Detection', desc: 'Flags unusual price movements that deviate significantly from historical norms. Detects flash crashes, sudden pumps, abnormal volume spikes, and gap openings. Anomaly alerts include severity scoring (minor, moderate, major) and comparison to the asset historical volatility range.' },
        { capability: 'Correlation Analysis', desc: 'Analyzes how your watched assets move relative to each other. Identifies positive correlations (crude oil and energy stocks), negative correlations (gold and dollar index), and breaking correlations that might signal regime changes. Correlation matrix updates daily with 30/90/180-day lookback windows.' },
        { capability: 'Predictive Alerts', desc: 'Estimates when a watched asset is likely to hit your target price based on current momentum, historical volatility, and trend direction. Sends alerts like "At current rate, ETH is projected to reach your $4,000 target within 3-5 days." Confidence intervals and assumptions are disclosed.' },
        { capability: 'Market Sentiment Scoring', desc: 'Aggregates sentiment signals from social media, news headlines, and on-chain data (for crypto) to produce a sentiment score per asset. Extreme fear or greed scores trigger alerts. Sentiment divergence from price action (price rising while sentiment drops) generates contrarian signal alerts.' },
        { capability: 'Smart Digest Generation', desc: 'AI composes a daily market digest summarizing price movements, triggered alerts, emerging trends, and noteworthy anomalies across your entire watchlist. The digest is personalized — it prioritizes the assets and conditions most relevant to your alert history and adjusts its detail level based on market volatility.' },
      ]}
      troubleshooting={[
        { issue: 'Alert not firing when price hits threshold', solution: 'Verify the alert is active (not paused) in /api/alerts. Check the polling interval for your asset class — equities update every 15 minutes during market hours, crypto every 1-5 minutes, commodities every 30-60 minutes. If the price spiked and recovered between polls, the system may have missed it. Reduce the polling interval or switch to a streaming data source (available for crypto on premium plans).' },
        { issue: 'SMS notifications not arriving', solution: 'Verify your phone number is confirmed in settings (check for the green verified badge). Ensure SMS is enabled on the specific alert rule. Check the notification log in the dashboard for delivery status — "delivered" means Twilio confirmed handoff to the carrier. If status shows "undelivered," the carrier may be blocking short-code messages. Try enabling the long-code number option in settings.' },
        { issue: 'Competitor price scraper showing incorrect prices', solution: 'Product page layouts change frequently. Open the asset detail page and check the "last scraped" timestamp and price. If the price looks wrong, the scraper may be reading the wrong element. Use the custom selector override to specify the correct CSS selector for the price element. Some sites require JavaScript rendering — enable the "headless mode" toggle for those sources.' },
        { issue: 'Historical chart data has gaps', solution: 'Gaps in chart data occur when the data source was temporarily unavailable during that period. The system does not interpolate missing data to avoid misleading charts. For equities, gaps on weekends and holidays are normal. For crypto (which trades 24/7), gaps indicate source outages — the fallback provider usually fills these, but brief outages under 5 minutes may still produce a gap at 1-minute granularity.' },
      ]}
      faq={[
        { q: 'How many assets can I track simultaneously?', a: 'Free plan: 10 assets with 2 alerts each. Starter plan: 50 assets with 5 alerts each. Professional plan: 500 assets with unlimited alerts. Enterprise plan: unlimited assets and alerts with dedicated data feeds and sub-second polling. All plans include all asset classes (crypto, equities, commodities, custom).' },
        { q: 'What data sources do you use?', a: 'Crypto: CoinGecko (primary), Binance API, Coinbase API. Equities: Alpha Vantage (primary), Yahoo Finance (fallback). Commodities: EIA (energy), USDA (agriculture), LBMA (precious metals). Competitor pricing: Custom scraper engine with headless browser fallback. Each asset uses at least 2 sources with automatic failover.' },
        { q: 'Is there a mobile app?', a: 'The dashboard is fully responsive and works as a progressive web app (PWA) on mobile. Add it to your home screen for an app-like experience. Push notifications work via SMS and Telegram on mobile. A native iOS and Android app is on the roadmap for Q3 2026 with native push notifications and Apple Watch complications.' },
        { q: 'Can I use alerts to trigger automated trades?', a: 'The webhook channel delivers structured JSON payloads to any URL, which can trigger trading bot actions. The payload includes the asset symbol, current price, alert condition, and custom metadata. Many users connect alerts to trading bots via Zapier, custom scripts, or direct API calls. Echo does not execute trades directly — the alert is the signal, your automation handles execution.' },
        { q: 'How far back does historical data go?', a: 'Crypto: full history from CoinGecko (varies by token, most major tokens have 5+ years). Equities: 20 years of daily data, 2 years of hourly data, 30 days of minute-level data. Commodities: 10 years of daily data. Custom scraped prices: from the date you added the asset. All data is stored in D1 and never purged.' },
      ]}
    />
  )
}
