'use client'

import ProductDoc, { ProductDocProps } from '@/components/ProductDoc'

const data: ProductDocProps = {
  name: 'Echo Commerce',
  tagline: 'AI-powered e-commerce platform with product catalog, cart, and order management.',
  accent: '#059669',
  productUrl: '/ecommerce',
  workerUrl: 'https://echo-shopify.bmcii1976.workers.dev',
  version: '1.0.0',
  overview: [
    'Echo Commerce is a full-stack e-commerce engine that provides product catalog management, shopping cart functionality, checkout workflows, and order fulfillment tracking through a single unified API. Built on Cloudflare Workers, it delivers sub-50ms response times globally and integrates natively with Shopify, WooCommerce, and standalone storefronts. The platform handles everything from product listing creation to post-purchase analytics, eliminating the need for multiple disconnected e-commerce tools.',
    'What sets Echo Commerce apart is its AI-driven intelligence layer. Product recommendations are generated using collaborative filtering and behavioral analysis, not generic "customers also bought" rules. Dynamic pricing suggestions, inventory demand forecasting, and automated product descriptions reduce the operational burden on store owners while increasing average order value. The AI learns from your specific catalog and customer base, improving accuracy over time.',
    'The platform supports multi-channel selling across your own storefront, marketplace integrations, and social commerce channels from one centralized inventory. Orders from all channels merge into a single fulfillment queue with intelligent routing to the nearest warehouse or supplier. Real-time inventory sync prevents overselling, and automated reorder triggers ensure stock levels stay optimal without manual intervention.',
  ],
  gettingStarted: [
    { step: 1, title: 'Set Up Your Store', desc: 'Create your Echo Commerce account and configure your store settings including business name, currency, tax jurisdiction, and shipping zones. The setup wizard walks you through each configuration step and pre-populates sensible defaults based on your location.' },
    { step: 2, title: 'Import Your Catalog', desc: 'Import products via CSV upload, Shopify sync, or the product creation API. Each product supports variants (size, color), multiple images, SEO metadata, inventory tracking, and custom attributes. Bulk import handles up to 50,000 products in a single operation.' },
    { step: 3, title: 'Configure Checkout', desc: 'Set up your checkout flow including accepted payment methods (via Echo Payments integration), shipping rate calculation, tax rules, and order confirmation emails. Enable guest checkout or require account creation based on your business needs.' },
    { step: 4, title: 'Connect Sales Channels', desc: 'Link your Shopify store, Amazon seller account, or social commerce channels for multi-channel inventory sync. Echo Commerce maintains a single source of truth for stock levels and pushes updates to all connected channels in real time.' },
    { step: 5, title: 'Launch and Monitor', desc: 'Publish your storefront and monitor performance through the analytics dashboard. Track conversion rates, average order value, top products, and customer acquisition costs. AI recommendations activate automatically once you accumulate 100+ orders.' },
  ],
  features: [
    { title: 'Product Catalog', desc: 'Comprehensive product management with support for simple products, variants (up to 100 per product), digital downloads, subscription items, and bundled products. Each product includes rich text descriptions, multiple images with CDN delivery, SEO metadata, and custom attribute fields.' },
    { title: 'Inventory Sync', desc: 'Real-time inventory synchronization across all connected sales channels. Stock levels update within seconds of a sale, preventing overselling. Supports multi-warehouse inventory with location-based allocation and automatic transfer suggestions between locations.' },
    { title: 'Order Management', desc: 'Centralized order processing with status tracking from placement through delivery. Orders from all channels appear in a unified queue with filtering, bulk actions, and priority flagging. Supports split shipments, backorders, and pre-orders with automated customer notifications.' },
    { title: 'Cart System', desc: 'Persistent server-side shopping cart with automatic session recovery. Abandoned cart detection triggers configurable email sequences. Cart supports discount codes, quantity limits, minimum order thresholds, and real-time shipping estimate calculation.' },
    { title: 'Checkout Flow', desc: 'Optimized single-page checkout with address autocomplete, saved payment methods, express checkout (Apple Pay, Google Pay), and order summary with tax and shipping calculated in real time. Conversion rate tracking identifies and alerts on drop-off points.' },
    { title: 'Shipping Integration', desc: 'Native integrations with USPS, UPS, FedEx, and DHL for real-time rate calculation, label generation, and tracking number injection. Supports flat rate, weight-based, and zone-based shipping rules with free shipping thresholds.' },
    { title: 'Tax Calculation', desc: 'Automated sales tax and VAT calculation based on customer location, product category, and applicable nexus rules. Integrates with tax authority databases for up-to-date rates. Supports tax-exempt customers and generates tax summary reports for filing.' },
    { title: 'Product Recommendations AI', desc: 'Machine learning recommendation engine that analyzes purchase history, browsing behavior, and product affinities to generate personalized "recommended for you", "frequently bought together", and "trending in your area" suggestions that increase average order value.' },
    { title: 'Customer Reviews', desc: 'Built-in review and rating system with verified purchase badges, photo uploads, and automated review request emails. AI-powered sentiment analysis flags potentially fake or abusive reviews for moderation before publication.' },
    { title: 'Analytics Dashboard', desc: 'Real-time e-commerce analytics covering revenue, orders, conversion rate, average order value, customer lifetime value, and product performance. Cohort analysis tracks customer retention over time. All metrics are exportable and available via API.' },
    { title: 'Multi-Channel Selling', desc: 'Sell across your own site, Shopify, Amazon, eBay, Instagram Shopping, and Facebook Marketplace from a single inventory pool. Orders from all channels are processed through the same fulfillment pipeline with channel-specific packing slips and branding.' },
    { title: 'Discount & Coupon Engine', desc: 'Flexible promotion system supporting percentage discounts, fixed amount off, buy-one-get-one, tiered pricing, bundle deals, and free shipping codes. Coupons can be limited by usage count, date range, minimum order value, specific products, or customer segments.' },
  ],
  apiEndpoints: [
    { method: 'GET', path: '/products', desc: 'List all products with pagination, filtering by category, price range, availability, and custom attributes. Supports full-text search across product titles and descriptions. Returns product objects with variants, images, and inventory counts.', auth: true },
    { method: 'POST', path: '/orders', desc: 'Create a new order from a completed checkout session. Accepts line items, customer details, shipping address, payment reference, and optional discount codes. Returns the order object with calculated totals and fulfillment status.', auth: true },
    { method: 'GET', path: '/cart/:id', desc: 'Retrieve the current state of a shopping cart including line items, quantities, applied discounts, subtotal, tax estimate, and shipping options. Cart IDs are generated on first item addition and persist for 30 days.', auth: false },
    { method: 'POST', path: '/checkout', desc: 'Initiate the checkout process for a cart. Validates inventory availability, calculates final tax and shipping, applies discount codes, and creates a payment intent via Echo Payments. Returns a checkout session with payment confirmation details.', auth: true },
    { method: 'GET', path: '/analytics/sales', desc: 'Sales analytics endpoint returning order count, gross revenue, net revenue, average order value, and top-selling products for the specified date range. Supports grouping by day, week, month, channel, or product category.', auth: true },
    { method: 'POST', path: '/inventory/sync', desc: 'Trigger a manual inventory sync across all connected sales channels. Compares local stock levels with channel-reported levels, resolves discrepancies, and pushes corrected counts. Returns a sync report with any conflicts detected.', auth: true },
  ],
  userGuide: [
    { title: 'Setting Up Your Product Catalog', id: 'catalog-setup', content: [
      'Start by organizing your products into categories and collections. Categories provide the hierarchical structure (e.g., Clothing > Mens > Shirts) while collections are curated groups used for merchandising (e.g., "Summer Sale", "New Arrivals"). A product can belong to multiple collections but typically has one primary category.',
      'For each product, provide a title, description, at least one image, a price, and an SKU. If your product has variants (sizes, colors, materials), define the variant options and their individual prices and stock levels. The system generates URL-friendly slugs automatically from product titles, but you can customize them for SEO purposes.',
      'Use the bulk import feature to migrate an existing catalog. Upload a CSV with columns matching the product schema (title, description, price, sku, category, image_url, variant_options). The importer validates each row, reports errors, and creates products for all valid entries in a single batch operation.',
    ] },
    { title: 'Managing Orders and Fulfillment', id: 'order-fulfillment', content: [
      'New orders appear in the Orders dashboard with a status of "confirmed" after payment capture. From here, orders move through "processing" (being picked and packed), "shipped" (carrier has the package), and "delivered" (tracking confirms delivery). Each status change triggers a customer notification email.',
      'For orders requiring split shipment, mark individual line items as shipped separately with their own tracking numbers. The customer receives separate shipping notifications for each shipment. Backorder items are held in a pending queue and automatically move to processing when stock arrives.',
      'Returns and exchanges are initiated from the order detail page. Generate a return shipping label, specify the reason code, and choose whether to issue a refund or store credit. Returned inventory is automatically restocked once the return is received and inspected.',
    ] },
    { title: 'Running Promotions and Discounts', id: 'promotions', content: [
      'Create discount codes from the Promotions dashboard. Each code has a type (percentage, fixed amount, free shipping), value, and optional constraints such as minimum order value, maximum uses, valid date range, and eligible products or categories.',
      'For site-wide sales, use automatic discounts that apply at checkout without a code. These appear as crossed-out original prices on product pages and in the cart. Stack multiple automatic discounts by setting priority levels — higher priority discounts apply first, and you control whether additional discounts can combine.',
    ] },
  ],
  aiCapabilities: [
    { capability: 'Personalized Recommendations', desc: 'Collaborative filtering and content-based algorithms analyze each customer\'s browsing history, purchase patterns, and product affinities to generate real-time recommendations. The model retrains nightly on your store\'s data, achieving a 15-25% lift in average order value for stores with 1,000+ orders.' },
    { capability: 'Demand Forecasting', desc: 'Time-series prediction models forecast product demand 30, 60, and 90 days ahead based on historical sales velocity, seasonal patterns, promotional calendars, and external signals. Forecasts drive automated reorder suggestions and help prevent both stockouts and overstock situations.' },
    { capability: 'Dynamic Pricing Intelligence', desc: 'AI analyzes competitor pricing, demand elasticity, inventory levels, and margin targets to suggest optimal price points for each product. Pricing suggestions are advisory — you review and approve before any price changes go live. A/B testing support measures the revenue impact of price adjustments.' },
    { capability: 'Automated Product Descriptions', desc: 'Generate SEO-optimized product descriptions from product attributes, images, and category context. The AI produces unique, natural-language descriptions that highlight key features and benefits. Bulk generation handles hundreds of products at once, with human review queues for quality control.' },
  ],
  troubleshooting: [
    { issue: 'Inventory counts out of sync across channels', solution: 'Run a manual sync from POST /inventory/sync to reconcile discrepancies. If the issue persists, check the Channel Sync Logs for error responses from connected platforms (expired OAuth tokens are the most common cause). Re-authorize the affected channel connection from Settings > Channels. For ongoing reliability, ensure webhook endpoints for each channel are receiving inventory update events.' },
    { issue: 'Checkout failing with "inventory unavailable" error', solution: 'This occurs when a product sells out between cart addition and checkout initiation. The checkout process performs a real-time inventory check and rejects items with zero stock. Enable the "Allow Backorders" setting for products you can fulfill from suppliers, or configure the "Low Stock Alert" threshold to notify you before products run out completely.' },
    { issue: 'Product images loading slowly or not appearing', solution: 'All product images are served through the Cloudflare CDN with automatic WebP conversion and responsive sizing. If images are slow, verify the original upload was not corrupt (re-upload if needed). For missing images, check that the image URL in the product record is still valid — if hosted externally, the source may have moved. Migrate to R2-hosted images for guaranteed availability.' },
    { issue: 'Discount code not applying at checkout', solution: 'Verify the discount code status in Promotions — it may be expired, used up (max redemptions reached), or restricted to products not in the cart. Check the minimum order value threshold against the cart subtotal. If the code is valid but still not applying, clear the cart and re-add items — a stale cart session can sometimes cache old pricing.' },
  ],
  faq: [
    { q: 'How many products can I list on Echo Commerce?', a: 'There is no hard limit on product count. The catalog is stored in Cloudflare D1 with R2 for images, both of which scale automatically. Stores with 100,000+ products operate normally. Bulk operations (import, price update, inventory sync) process up to 50,000 items per batch.' },
    { q: 'Does Echo Commerce handle sales tax automatically?', a: 'Yes. Tax rates are calculated automatically based on the customer\'s shipping address, your nexus registrations, and the product tax category. The system maintains up-to-date tax rates for all US states and territories, EU VAT rates, and Canadian GST/HST/PST. Tax-exempt customers can be flagged with a certificate on file.' },
    { q: 'Can I use Echo Commerce with my existing Shopify store?', a: 'Yes. The Shopify integration performs a bidirectional sync of products, inventory, orders, and customers. You can manage everything from Echo Commerce while keeping your Shopify storefront live. Changes made in either system propagate to the other within 60 seconds.' },
    { q: 'How does the AI recommendation engine work?', a: 'The recommendation engine uses a hybrid collaborative filtering and content-based approach. It analyzes purchase co-occurrence (customers who bought X also bought Y), product attribute similarity, and individual browsing behavior to generate ranked suggestions. The model requires a minimum of 100 orders to activate and improves continuously as more data accumulates.' },
    { q: 'What payment methods are supported at checkout?', a: 'Echo Commerce integrates with Echo Payments to support credit/debit cards (Visa, Mastercard, Amex, Discover), PayPal, Apple Pay, Google Pay, and ACH bank transfers. Cryptocurrency payments via Coinbase Commerce are available in beta. You can enable or disable specific methods from the Checkout Settings page.' },
  ],
}

export default function Page() { return <ProductDoc {...data} /> }
