'use client'

import ProductDoc from '@/components/ProductDoc'
import FaqSchema from '@/components/FaqSchema'
import BreadcrumbSchema from '@/components/BreadcrumbSchema'

const data = {
  name: 'Echo Knowledge Scout',
  tagline: 'Autonomous knowledge discovery agent that scans Reddit, HackerNews, ArXiv, RSS feeds, and GitHub — finding 5-15 AI and tech breakthroughs every day before the rest of the world notices.',
  accent: '#10b981',
  productUrl: '/knowledge-scout',
  workerUrl: 'https://echo-knowledge-scout.bmcii1976.workers.dev',
  version: '2.1.0',
  overview: [
    'Echo Knowledge Scout is an always-on autonomous discovery engine that continuously monitors seven high-signal sources — Reddit (r/MachineLearning, r/LocalLLaMA, r/artificial, r/netsec, r/programming, and 40+ subreddits), Hacker News top stories, ArXiv preprints, curated RSS feeds from research labs and industry blogs, and GitHub trending repositories. It runs on a configurable cron schedule (default every 4 hours), scoring every candidate item against a relevance model tuned for the Echo ecosystem\'s knowledge domains: AI models, developer tools, research papers, protocols, MCP servers, memory systems, and robotics.',
    'Every discovery that clears the relevance threshold is domain-classified, deduplication-checked against the prior 30 days of findings, and broadcast simultaneously to Echo Shared Brain (tagged for retrieval by all AI instances) and OmniSync (for cross-system propagation). The daily report aggregates top findings by domain with quality scores, enabling the Commander and all active CC instances to start each session already briefed on what changed overnight in the fields they care about.',
    'Knowledge Scout is designed around a zero-false-negative philosophy: it is better to surface a marginally relevant item than to miss a genuine breakthrough. Relevance scores are transparent — every discovery record includes the raw score, the matching keyword watchlist entries, and the source metadata so downstream systems and human reviewers can apply their own thresholds. The watchlist is fully configurable per deployment, and new keyword sets activate on the next scheduled scan without a redeploy.',
  ],
  gettingStarted: [
    { step: 1, title: 'Review the Daily Report', desc: 'Hit GET /report/daily to retrieve the most recent aggregated discovery report. It returns top findings organized by domain (model, tool, paper, protocol, mcp_server, memory_system, robotics) with quality scores and source links.' },
    { step: 2, title: 'Browse Recent Discoveries', desc: 'Use GET /discoveries with optional filters for domain, source, min_score, and date range. Results are paginated and sorted by relevance score descending. Each record includes title, URL, summary, domain classification, score, and broadcast timestamps.' },
    { step: 3, title: 'Trigger a Manual Scan', desc: 'POST to /scan to run an immediate scan outside the cron schedule. Useful after configuring a new keyword watchlist or when you need up-to-the-minute coverage before a planning session. The scan runs asynchronously; poll /scan/:job_id for status.' },
    { step: 4, title: 'Configure Keyword Watchlists', desc: 'POST to /watchlist with your keyword arrays per domain category. Keywords use simple string matching plus optional regex patterns. Changes take effect on the next scan cycle. GET /watchlist returns the current active configuration.' },
    { step: 5, title: 'Connect Downstream Systems', desc: 'Discoveries are automatically broadcast to Shared Brain and OmniSync, making them available to all CC instances and AI agents without manual polling. For custom integrations, use GET /discoveries with a since parameter to pull incremental updates.' },
  ],
  features: [
    { title: 'Multi-Source Scanning', desc: 'Simultaneous monitoring of Reddit (40+ subreddits), Hacker News, ArXiv preprints, GitHub trending, curated RSS feeds from OpenAI, Anthropic, Hugging Face, DeepMind, and 30+ research blogs. All sources run in parallel on each scan cycle.' },
    { title: 'Relevance Scoring Engine', desc: 'Each candidate item is scored 0-100 against a multi-factor model: keyword match density, domain alignment, source authority weight, engagement signals (upvotes, comments, stars), and recency. Only items scoring above the configurable threshold (default 65) enter the discovery record.' },
    { title: 'Domain Classification', desc: 'Automatic classification into seven primary domains: model (new AI models and weights), tool (developer tools and frameworks), paper (research publications), protocol (new standards and APIs), mcp_server (Model Context Protocol servers), memory_system (AI memory architectures), and robotics. Multi-label classification supported.' },
    { title: 'Broadcast to Shared Brain', desc: 'Every qualifying discovery is immediately ingested into Echo Shared Brain with domain tags, quality score, and full metadata. All active CC instances retrieve these at SessionStart, meaning the fleet wakes up already aware of overnight developments.' },
    { title: 'OmniSync Propagation', desc: 'Concurrent broadcast to OmniSync ensures discoveries reach all connected systems — Engine Runtime, Knowledge Forge, Memory Prime — without requiring each system to poll independently. One scan, one broadcast, universal awareness.' },
    { title: 'Deduplication Engine', desc: 'URL-based and content-hash deduplication across a 30-day rolling window prevents the same discovery from flooding the feed. Cross-source deduplication catches the same ArXiv paper appearing on both HN and Reddit.' },
    { title: 'Daily Report Generation', desc: 'Automated daily summary compiled at 06:00 UTC covering all discoveries from the past 24 hours, ranked by score within each domain. Includes counts by source and domain, top items with excerpts, and a quality distribution histogram.' },
    { title: 'Configurable Keyword Watchlists', desc: 'Per-domain keyword arrays with optional regex support. Watchlist changes via API take effect on the next scan without redeploy. Separate watchlists for inclusion keywords (must match) and exclusion keywords (disqualifies item).' },
    { title: 'ArXiv Integration', desc: 'Dedicated ArXiv scraper targeting cs.AI, cs.LG, cs.CL, cs.CR, stat.ML, and eess.IV categories. Extracts abstract, authors, submission date, and citation count. Papers with >50 citations in the first 48 hours get a priority score boost.' },
    { title: 'GitHub Trending Tracker', desc: 'Daily scan of GitHub Trending for repositories in Python, TypeScript, Rust, and Go with star growth rate as a secondary scoring signal. Repositories matching AI/ML/security keywords with >50 new stars per day are auto-classified and broadcast.' },
    { title: 'RSS Feed Management', desc: 'Manage a library of RSS feeds via API. Add, remove, or pause individual feeds without affecting the rest of the scan pipeline. Each feed has its own quality weight that scales the relevance score for items originating from that source.' },
    { title: 'Scan History & Analytics', desc: 'Full scan history with per-scan stats: items evaluated, items accepted, rejection reasons, latency by source, and broadcast confirmation receipts. Use GET /sources to see per-source health, last successful fetch, and rolling acceptance rate.' },
  ],
  apiEndpoints: [
    { method: 'GET', path: '/discoveries', desc: 'List recent discoveries. Supports filters: domain (model|tool|paper|protocol|mcp_server|memory_system|robotics), source (reddit|hn|arxiv|rss|github), min_score (0-100), since (ISO timestamp), limit (max 100). Returns paginated array with relevance scores and broadcast status.', auth: false },
    { method: 'GET', path: '/sources', desc: 'List all monitored sources with current health status. Returns name, type, URL, last_fetch timestamp, items_found_today, acceptance_rate_7d, and quality_weight. Use to diagnose slow or failing source scrapers.', auth: false },
    { method: 'POST', path: '/scan', desc: 'Trigger an immediate out-of-schedule scan. Optionally pass a sources array to limit which sources run. Returns a job_id for async polling. The scan broadcasts to Shared Brain and OmniSync on completion exactly as a scheduled scan would.', auth: true },
    { method: 'GET', path: '/report/daily', desc: 'Retrieve the most recent daily discovery report. Returns domain breakdowns, top-10 items per domain with excerpts and scores, source contribution stats, and total discovery count. Accepts a date parameter (YYYY-MM-DD) to retrieve historical reports.', auth: false },
    { method: 'GET', path: '/watchlist', desc: 'Get the current active keyword watchlist configuration. Returns per-domain inclusion and exclusion keyword arrays, last modified timestamp, and next scheduled scan time.', auth: true },
    { method: 'POST', path: '/watchlist', desc: 'Update the keyword watchlist. POST a JSON body with domain keys and keyword arrays. Supports partial updates — only the domains included in the request are modified. Changes activate on the next scan cycle.', auth: true },
    { method: 'GET', path: '/discoveries/:id', desc: 'Retrieve a single discovery record by ID. Returns full metadata: title, URL, source, domain array, relevance_score, score_breakdown (keyword density, engagement, recency, source_weight), summary, broadcast_timestamps, and dedup_hash.', auth: false },
    { method: 'GET', path: '/health', desc: 'Returns worker health, last successful scan timestamp, next scheduled scan time, total discoveries in the rolling 30-day window, and per-source health indicators. Safe for public monitoring integrations.', auth: false },
  ],
  userGuide: [
    { id: 'how-scanning-works', title: 'How Scanning Works', content: [
      'Each scan cycle begins with a parallel fetch across all enabled sources. Reddit scrapers pull the top 100 posts from each monitored subreddit sorted by hot, extracting title, URL, body text, score, and comment count. The HN scraper pulls the top 200 stories via the official Firebase API. ArXiv fetches the latest 50 papers from each monitored category. RSS feeds are fetched sequentially with a 5-second timeout per feed. GitHub Trending is scraped via the public web interface.',
      'Raw items flow into the relevance scoring pipeline where each is evaluated against the keyword watchlist, assigned a domain classification, and scored on five factors: keyword match density (40%), domain alignment strength (25%), source authority weight (15%), engagement signal (10%), and recency decay (10%). Items scoring below the threshold (default 65) are discarded. Items above threshold are checked against the deduplication index.',
      'Surviving items are written to the discovery store, broadcast to Shared Brain with domain and score tags, and queued for OmniSync propagation. The entire pipeline from fetch start to broadcast confirmation runs in under 90 seconds for a full 7-source scan cycle. Failed source fetches are retried twice with exponential backoff before being marked as errors and excluded from the cycle result.',
    ]},
    { id: 'domain-classification', title: 'Domain Classification System', content: [
      'Every discovery is classified into one or more of seven domains. model covers new AI model releases, weight updates, fine-tunes, and benchmark results — anything about a specific AI system\'s capabilities. tool covers developer tools, libraries, frameworks, CLIs, and IDEs that practitioners use to build AI systems. paper covers research publications from ArXiv, conference proceedings, and lab technical reports.',
      'protocol covers new API standards, communication protocols, data formats, and interoperability specifications — including new MCP tool definitions when they appear in GitHub repos. mcp_server is a sub-classification specifically for Model Context Protocol server implementations, given their direct relevance to the Echo fleet. memory_system covers innovations in AI memory architectures, context management, and retrieval systems.',
      'robotics covers physical embodiment research, motor control advances, and hardware-software integration for autonomous systems. Multi-label classification is supported — an item about a new robotics LLM fine-tune would be tagged both model and robotics. The classification is performed by a lightweight embedding model running inside the Worker, comparing item text against domain exemplar vectors stored in KV.',
    ]},
    { id: 'configuring-watchlists', title: 'Configuring Keyword Watchlists', content: [
      'The keyword watchlist is the primary lever for tuning what Scout finds. Each domain has an independent list of inclusion keywords (at least one must match) and exclusion keywords (any match disqualifies the item). Keywords are case-insensitive and matched against the full text of title plus the first 500 characters of body or abstract.',
      'Regex patterns are supported by wrapping the keyword in forward slashes: "/claude-\\d+/" matches "claude-3", "claude-4", etc. Phrase matching is supported with quoted strings: the keyword "chain of thought" matches the exact phrase, not individual words. Keyword hits are weighted by position — a title match scores 3x a body match.',
      'When adding keywords for a new topic area, start broad and narrow based on the acceptance rate. POST /watchlist with the updated domain arrays, then trigger POST /scan to see results immediately. If the acceptance rate for a new keyword is low, the keyword may be too specific or the topic may not appear frequently in monitored sources — consider adding additional sources via the RSS management API.',
    ]},
    { id: 'broadcast-and-retrieval', title: 'Broadcast and Retrieval', content: [
      'Every qualifying discovery is broadcast to Echo Shared Brain at the moment it is accepted. The Shared Brain entry includes the full discovery record plus the tags: "knowledge-scout", the domain classification, and "discovery". All active CC instances retrieve tagged entries from Shared Brain at SessionStart, meaning every new Claude Code session wakes up pre-loaded with the latest discoveries.',
      'OmniSync propagation runs concurrently with the Shared Brain write. OmniSync distributes the discovery to all connected downstream systems — Engine Runtime for potential doctrine updates, Knowledge Forge for indexing into the searchable knowledge base, and Memory Prime for long-term retention. This single broadcast fan-out means the discovery reaches the entire Echo intelligence stack without any system needing to poll.',
      'For external integrations outside the Echo ecosystem, use GET /discoveries with the since parameter set to your last poll timestamp. This incremental pull pattern works well for Slack bots, email digests, or custom dashboards. The discovery records are stable — IDs and content do not change after creation, so downstream systems can safely cache and deduplicate by ID.',
    ]},
    { id: 'monitoring-and-ops', title: 'Monitoring and Operations', content: [
      'The /health endpoint exposes operational metrics suitable for external uptime monitors. Key fields to watch: last_scan_at (should be within 5 hours of now), scan_errors_24h (should be 0 or 1 — isolated source failures are expected), and discoveries_today (should be >0 by 10:00 UTC). The sources endpoint provides per-source health indicators including last_fetch, fetch_duration_ms, and rolling 7-day acceptance_rate.',
      'If a source shows repeated fetch failures, the most common causes are: rate limiting (particularly Reddit and GitHub), SSL certificate changes, or site structure changes that break the scraper. Reddit rate limiting is mitigated by the OAuth-authenticated API client; if it recurs, check that the Reddit OAuth token in the vault is current. GitHub scraping failures usually indicate a CSS selector change on the Trending page.',
      'Daily report generation runs at 06:00 UTC via a Cloudflare Cron Trigger. If the daily report is missing, check the Worker Cron Trigger status in the Cloudflare dashboard. Reports older than 90 days are archived to R2 (echo-prime-cold-archive bucket) and remain retrievable via the /report/daily?date= parameter with the historical date.',
    ]},
  ],
  aiCapabilities: [
    { capability: 'Relevance Scoring', desc: 'Multi-factor scoring model combining keyword match density, domain alignment via embedding similarity, source authority weight, engagement signals (upvotes, stars, comment velocity), and recency decay. Scores are deterministic and fully auditable via the score_breakdown field on each discovery record.' },
    { capability: 'Domain Classification', desc: 'Lightweight embedding model classifies each item against seven domain exemplar vectors stored in KV. Classification runs in <10ms per item inside the Worker without external API calls. Multi-label classification catches items relevant to multiple domains simultaneously.' },
    { capability: 'Content Summarization', desc: 'For ArXiv papers and long-form blog posts, Scout calls Engine Runtime\'s summarization engine to generate a 2-3 sentence abstract in plain language. This summary is stored with the discovery record and included in the daily report for quick human review.' },
    { capability: 'Deduplication Intelligence', desc: 'Beyond exact URL deduplication, Scout uses a content-hash fingerprint of the normalized title to catch the same story appearing under different URLs (cross-posts, mirrors, aggregators). The 30-day rolling window ensures the same paper appearing on multiple platforms is recorded once.' },
    { capability: 'Engagement Signal Analysis', desc: 'Scout tracks not just current engagement (score, comments) but rate of change — a post accumulating 500 upvotes in 2 hours scores higher than one accumulating 500 upvotes over 2 days. This velocity signal helps surface genuinely viral discoveries before they become mainstream knowledge.' },
    { capability: 'Source Quality Learning', desc: 'Per-source acceptance rates are tracked over time. Sources consistently producing high-relevance items have their quality weight increased automatically, amplifying their contribution to the scoring model. Sources with declining acceptance rates are flagged for watchlist review.' },
  ],
  troubleshooting: [
    { issue: 'Daily report is empty or missing', solution: 'Check GET /health for last_scan_at and scan_errors_24h. If scans are running but discoveries_today is 0, the keyword watchlist may be too restrictive — try lowering the relevance threshold or broadening inclusion keywords. If last_scan_at is stale by >6 hours, the Cloudflare Cron Trigger may need to be re-enabled in the dashboard.' },
    { issue: 'Reddit source showing repeated fetch failures', solution: 'The Reddit OAuth token in the vault may have expired. Retrieve the token from the Cloudflare KV namespace (key: reddit_oauth_token) and check expiry. If expired, the token_refresher Worker should have renewed it automatically — check token_refresher logs for errors. As a fallback, POST /scan with sources: ["hn","arxiv","rss","github"] to run a partial scan while Reddit is restored.' },
    { issue: 'Discoveries not appearing in Shared Brain after scan', solution: 'Check GET /discoveries for recent items and verify their broadcast_status field. If broadcast_status is "failed", the Shared Brain Worker may be temporarily down. Scout uses a retry queue with 3 attempts per discovery. Check echo-shared-brain health endpoint and retry broadcast by re-triggering POST /scan with force_rebroadcast: true.' },
    { issue: 'Too many low-quality discoveries flooding the feed', solution: 'Raise the relevance threshold via the watchlist configuration (POST /watchlist with threshold: 75 or higher). Additionally, review GET /sources acceptance rates — sources with >80% acceptance rates may have quality weights that are too high. Add exclusion keywords for noise topics that consistently score high but are not relevant to your use case.' },
    { issue: 'ArXiv papers not being found', solution: 'ArXiv enforces rate limits of 1 request/3 seconds. If the scan cycle is running too frequently or multiple Workers are scanning simultaneously, ArXiv will return 429 errors. Check scan logs for HTTP 429 responses on the arxiv source. The default 4-hour cron interval is well within ArXiv\'s limits for single-instance deployments.' },
  ],
  faq: [
    { q: 'How many discoveries does Scout find per day?', a: 'Typical throughput is 5-15 discoveries per day across all 7 sources when using the default relevance threshold of 65. Higher-activity periods (major model releases, conference weeks) can produce 20-30 discoveries. Lowering the threshold to 50 roughly doubles volume but increases noise.' },
    { q: 'How quickly are discoveries broadcast to the fleet?', a: 'From source publication to Shared Brain availability is typically 2-4 hours for scheduled scans (depending on where in the cron cycle the item was published). Trigger POST /scan for near-real-time detection when monitoring an active event. OmniSync propagation to downstream systems completes within 30 seconds of Shared Brain write.' },
    { q: 'Can Scout monitor private or internal sources?', a: 'Yes. The RSS feed management API supports authenticated feeds via bearer token or basic auth credentials stored in the vault. Internal Confluence wikis, private GitHub repos (via personal access token), and authenticated RSS endpoints are all supported.' },
    { q: 'How is deduplication handled across sources?', a: 'Scout uses a two-layer deduplication strategy. The first layer is exact URL normalization (stripping UTM params, trailing slashes, etc.) with a 30-day TTL in KV. The second layer is a content fingerprint of the normalized title, catching cross-posts and mirrors. Both layers are checked before a new item enters the scoring pipeline.' },
    { q: 'Does Scout support custom domain categories beyond the seven built-in ones?', a: 'Not in the current release. The seven domains (model, tool, paper, protocol, mcp_server, memory_system, robotics) cover the core Echo intelligence stack. Custom domain support is planned for v3.0, where domain exemplar vectors will be configurable via API.' },
    { q: 'Are discovery records stored permanently?', a: 'The hot store (KV + D1) retains the last 30 days of discoveries with full metadata. After 30 days, records are archived to R2 (echo-prime-cold-archive) and remain retrievable via GET /discoveries with historical date filters. The archive has no expiry.' },
  ],
}

export default function KnowledgeScoutDocPage() {
  return (
    <>
      <FaqSchema faqs={data.faq} name={data.name} />
      <BreadcrumbSchema items={[
        { name: 'Home', href: '/' },
        { name: 'Docs', href: '/docs' },
        { name: data.name, href: '/docs/knowledge-scout' },
      ]} />
      <ProductDoc {...data} />
    </>
  )
}
