import type { Metadata } from 'next';
import './globals.css';
import { AuthProvider } from '../lib/auth-context';
import { ThemeProvider } from '../lib/theme-context';
import EchoPrimeChat from '../components/echo-prime-chat';
import { ParticleBackground } from '../components/ParticleBackground';
import ComingSoonGuard from '../components/ComingSoonGuard';
import { GuidedTutorialProvider } from '../lib/guided-tutorial-context';
import GuidedOverlay from '../components/guided-overlay';
import { Analytics } from '@vercel/analytics/react';
import { SpeedInsights } from '@vercel/speed-insights/next';

export const metadata: Metadata = {
  title: 'Echo Prime Technologies | AI Intelligence Engines, Sales Agents & Enterprise AI',
  description: '5,486+ AI engines across 940+ domains. AI sales agents, title intelligence, data pipelines, tax preparation, cybersecurity, and autonomous systems. Production-grade AI for industries that demand precision.',
  keywords: ['AI engines', 'AI sales agent', 'title intelligence', 'data pipelines', 'enterprise AI', 'autonomous systems', 'tax AI', 'cybersecurity AI', 'Echo Prime Technologies', 'oil and gas AI'],
  metadataBase: new URL('https://echo-ept.com'),
  alternates: { canonical: '/' },
  icons: {
    icon: [
      { url: '/icon.png', type: 'image/png', sizes: '192x192' },
    ],
    apple: '/icon.png',
  },
  openGraph: {
    title: 'Echo Prime Technologies — AI Engines, Sales Agents & Enterprise Intelligence',
    description: '5,486+ AI engines, autonomous sales agents, title intelligence, data pipelines, tax prep, and cybersecurity. Production-grade AI.',
    type: 'website',
    url: 'https://echo-ept.com',
    siteName: 'Echo Prime Technologies',
    images: [{ url: '/logo-day.png', width: 600, height: 400, alt: 'Echo Prime Technologies' }],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Echo Prime Technologies — AI Engines & Enterprise Intelligence',
    description: '5,486+ AI engines across 940+ domains. Sales agents, title intelligence, data pipelines, tax prep, and cybersecurity.',
    images: ['/logo-day.png'],
  },
  robots: { index: true, follow: true },
  other: { 'theme-color': '#0a0e17', 'site-id': 'echo-ept.com' },
};

const jsonLd = {
  '@context': 'https://schema.org',
  '@graph': [
    {
      '@type': 'Organization',
      '@id': 'https://echo-ept.com/#organization',
      name: 'Echo Prime Technologies',
      url: 'https://echo-ept.com',
      logo: 'https://echo-ept.com/logo-day.png',
      description: 'AI-powered title intelligence, autonomous systems, and enterprise AI infrastructure for oil & gas, legal, and engineering industries.',
      foundingDate: '2024',
      founder: { '@type': 'Person', name: 'Bobby Don McWilliams II' },
      areaServed: 'US',
      contactPoint: [
        { '@type': 'ContactPoint', contactType: 'sales', url: 'https://echo-ept.com/pricing', telephone: '+1-432-527-6112' },
        { '@type': 'ContactPoint', contactType: 'customer service', email: 'contact@echo-op.com', telephone: '+1-432-527-6112' },
      ],
      address: { '@type': 'PostalAddress', addressLocality: 'Midland', addressRegion: 'TX', addressCountry: 'US' },
      sameAs: ['https://github.com/ECHO-OMEGA-PRIME', 'https://www.linkedin.com/company/echo-prime-tech'],
    },
    {
      '@type': 'WebSite',
      '@id': 'https://echo-ept.com/#website',
      url: 'https://echo-ept.com',
      name: 'Echo Prime Technologies',
      publisher: { '@id': 'https://echo-ept.com/#organization' },
    },
    {
      '@type': 'SoftwareApplication',
      name: 'ShadowGlass Title Intelligence',
      applicationCategory: 'BusinessApplication',
      operatingSystem: 'Web',
      description: 'AI-powered chain of title search across 80+ Texas counties with 259,000+ indexed deed records. Automated mineral rights analysis, gap detection, and fractional interest calculations.',
      url: 'https://echo-ept.com/title-intelligence',
      offers: {
        '@type': 'AggregateOffer',
        lowPrice: '199',
        highPrice: '1500',
        priceCurrency: 'USD',
        offerCount: 3,
      },
      provider: { '@id': 'https://echo-ept.com/#organization' },
    },
    {
      '@type': 'SoftwareApplication',
      name: 'Sentinel AI',
      applicationCategory: 'BusinessApplication',
      operatingSystem: 'Web',
      description: 'Multi-domain AI intelligence system with 5,486+ engines, web search, knowledge retrieval, and real-time analysis across 940+ domains.',
      url: 'https://echo-ept.com/sentinel',
      provider: { '@id': 'https://echo-ept.com/#organization' },
    },
    {
      '@type': 'SoftwareApplication',
      name: 'AI Sales Agent (Closer AI)',
      applicationCategory: 'BusinessApplication',
      operatingSystem: 'Web',
      description: 'Autonomous AI voice closer with real-time STT, LLM reasoning, and natural TTS. Script engine with state machine, CRM with full lead pipeline.',
      url: 'https://echo-ept.com/closer',
      offers: { '@type': 'AggregateOffer', lowPrice: '299', highPrice: '999', priceCurrency: 'USD', offerCount: 3 },
      provider: { '@id': 'https://echo-ept.com/#organization' },
    },
    {
      '@type': 'SoftwareApplication',
      name: 'Data Pipelines',
      applicationCategory: 'BusinessApplication',
      operatingSystem: 'Web',
      description: 'Autonomous data extraction systems that find, extract, normalize, and deliver structured data from 50+ source types running 24/7.',
      url: 'https://echo-ept.com/pipelines',
      offers: { '@type': 'AggregateOffer', lowPrice: '199', highPrice: '499', priceCurrency: 'USD', offerCount: 3 },
      provider: { '@id': 'https://echo-ept.com/#organization' },
    },
    {
      '@type': 'SoftwareApplication',
      name: 'Intelligence Engines',
      applicationCategory: 'BusinessApplication',
      operatingSystem: 'Web',
      description: 'Purpose-built AI reasoning systems with deep domain expertise across 940+ verticals. 5,486+ engines with embedded knowledge blocks.',
      url: 'https://echo-ept.com/engines',
      offers: { '@type': 'AggregateOffer', lowPrice: '199', highPrice: '499', priceCurrency: 'USD', offerCount: 3 },
      provider: { '@id': 'https://echo-ept.com/#organization' },
    },
    {
      '@type': 'Service',
      name: 'AI Tax Return Preparation',
      description: 'AI-powered professional tax preparation with 14 Tax Intelligence Engines. IRS 1040, MACRS depreciation, QBI deduction, oil & gas IDC.',
      url: 'https://echo-ept.com/tax-returns',
      offers: { '@type': 'AggregateOffer', lowPrice: '150', highPrice: '750', priceCurrency: 'USD', offerCount: 5 },
      provider: { '@id': 'https://echo-ept.com/#organization' },
    },
    {
      '@type': 'Service',
      name: 'Penetration Testing',
      description: 'Full-scope offensive security: network, web, wireless, mobile, cloud, and Active Directory penetration testing with 300+ attack tools.',
      url: 'https://echo-ept.com/pentesting',
      offers: { '@type': 'AggregateOffer', lowPrice: '2500', highPrice: '7500', priceCurrency: 'USD', offerCount: 3 },
      provider: { '@id': 'https://echo-ept.com/#organization' },
    },
    {
      '@type': 'Service',
      name: 'Cyber Defense & Security Monitoring',
      description: 'Enterprise security operations: 24/7 threat monitoring, incident response, security architecture review, compliance assessment, and vulnerability management.',
      url: 'https://echo-ept.com/security',
      offers: { '@type': 'AggregateOffer', lowPrice: '499', highPrice: '2999', priceCurrency: 'USD', offerCount: 3 },
      provider: { '@id': 'https://echo-ept.com/#organization' },
    },
    {
      '@type': 'SoftwareApplication',
      name: 'Echo SDK Gateway',
      applicationCategory: 'DeveloperApplication',
      operatingSystem: 'Web',
      description: 'One API, 5,486+ intelligence engines. Query domain-specific AI reasoning, search infinite memory, and access 12,000+ knowledge documents through a single authenticated endpoint.',
      url: 'https://echo-ept.com/sdk',
      offers: {
        '@type': 'AggregateOffer',
        lowPrice: '0',
        highPrice: '299',
        priceCurrency: 'USD',
        offerCount: 3,
      },
      provider: { '@id': 'https://echo-ept.com/#organization' },
    },
    {
      '@type': 'SoftwareApplication',
      name: 'AI Collectibles Grading (EPOCGS)',
      applicationCategory: 'BusinessApplication',
      operatingSystem: 'Web',
      description: 'AI-powered collectibles grading with 25+ LLM ensemble, 50-agent research swarm, vision analysis, Comics Price Guide integration, and voice commentary.',
      url: 'https://echo-ept.com/grading',
      provider: { '@id': 'https://echo-ept.com/#organization' },
    },
    {
      '@type': 'SoftwareApplication',
      name: 'Immortality Vault',
      applicationCategory: 'LifestyleApplication',
      operatingSystem: 'Web',
      description: 'Digital consciousness preservation platform with guided interviews, voice cloning, and AI-powered conversational recall for families.',
      url: 'https://echo-ept.com/immortality-vault',
      provider: { '@id': 'https://echo-ept.com/#organization' },
    },
    {
      '@type': 'SoftwareApplication',
      name: 'AI CRM',
      applicationCategory: 'BusinessApplication',
      operatingSystem: 'Web',
      description: 'AI-powered customer relationship management with intelligent lead scoring, automated follow-ups, pipeline analytics, and multi-channel communication.',
      url: 'https://echo-ept.com/crm',
      offers: { '@type': 'AggregateOffer', lowPrice: '49', highPrice: '399', priceCurrency: 'USD', offerCount: 3 },
      provider: { '@id': 'https://echo-ept.com/#organization' },
    },
    {
      '@type': 'SoftwareApplication',
      name: 'AI Helpdesk',
      applicationCategory: 'BusinessApplication',
      operatingSystem: 'Web',
      description: 'Multi-tenant AI helpdesk with intelligent ticket routing, auto-resolution, SLA tracking, knowledge base integration, and omnichannel support.',
      url: 'https://echo-ept.com/helpdesk',
      offers: { '@type': 'AggregateOffer', lowPrice: '29', highPrice: '299', priceCurrency: 'USD', offerCount: 3 },
      provider: { '@id': 'https://echo-ept.com/#organization' },
    },
    {
      '@type': 'SoftwareApplication',
      name: 'AI Project Manager',
      applicationCategory: 'BusinessApplication',
      operatingSystem: 'Web',
      description: 'AI project management with smart task decomposition, resource optimization, risk prediction, timeline forecasting, and team collaboration.',
      url: 'https://echo-ept.com/project-manager',
      offers: { '@type': 'AggregateOffer', lowPrice: '29', highPrice: '199', priceCurrency: 'USD', offerCount: 3 },
      provider: { '@id': 'https://echo-ept.com/#organization' },
    },
    {
      '@type': 'SoftwareApplication',
      name: 'AI Finance Dashboard',
      applicationCategory: 'BusinessApplication',
      operatingSystem: 'Web',
      description: 'AI-powered financial intelligence with real-time P&L tracking, cash flow forecasting, expense categorization, and automated bookkeeping.',
      url: 'https://echo-ept.com/finance-ai',
      offers: { '@type': 'AggregateOffer', lowPrice: '49', highPrice: '499', priceCurrency: 'USD', offerCount: 3 },
      provider: { '@id': 'https://echo-ept.com/#organization' },
    },
    {
      '@type': 'SoftwareApplication',
      name: 'AI Home Automation',
      applicationCategory: 'LifestyleApplication',
      operatingSystem: 'Web',
      description: 'Intelligent home automation with natural language control, predictive scheduling, energy optimization, multi-protocol device management, and security monitoring.',
      url: 'https://echo-ept.com/smart-home',
      provider: { '@id': 'https://echo-ept.com/#organization' },
    },
    {
      '@type': 'SoftwareApplication',
      name: 'Echo Email Sender',
      applicationCategory: 'BusinessApplication',
      operatingSystem: 'Web',
      description: 'Transactional and marketing email platform with AI subject line optimization, drip sequences, bounce handling, delivery analytics, and multi-tenant isolation.',
      url: 'https://echo-ept.com/email-sender',
      offers: { '@type': 'AggregateOffer', lowPrice: '9', highPrice: '99', priceCurrency: 'USD', offerCount: 3 },
      provider: { '@id': 'https://echo-ept.com/#organization' },
    },
    {
      '@type': 'SoftwareApplication',
      name: 'Echo LMS',
      applicationCategory: 'EducationalApplication',
      operatingSystem: 'Web',
      description: 'AI-powered learning management system with course builder, AI quiz generation, certificates, progress tracking, discussion forums, and multi-tenant support.',
      url: 'https://echo-ept.com/lms',
      offers: { '@type': 'AggregateOffer', lowPrice: '19', highPrice: '149', priceCurrency: 'USD', offerCount: 3 },
      provider: { '@id': 'https://echo-ept.com/#organization' },
    },
    {
      '@type': 'SoftwareApplication',
      name: 'Echo Booking',
      applicationCategory: 'BusinessApplication',
      operatingSystem: 'Web',
      description: 'AI scheduling and appointment booking with calendar sync, automated reminders, buffer times, service-based booking, and team availability management.',
      url: 'https://echo-ept.com/booking',
      offers: { '@type': 'AggregateOffer', lowPrice: '19', highPrice: '99', priceCurrency: 'USD', offerCount: 3 },
      provider: { '@id': 'https://echo-ept.com/#organization' },
    },
    {
      '@type': 'SoftwareApplication',
      name: 'Echo Invoice',
      applicationCategory: 'BusinessApplication',
      operatingSystem: 'Web',
      description: 'AI-powered invoicing with auto-generation, payment tracking, recurring billing, multi-currency support, tax calculation, and branded templates.',
      url: 'https://echo-ept.com/invoice',
      offers: { '@type': 'AggregateOffer', lowPrice: '9', highPrice: '79', priceCurrency: 'USD', offerCount: 3 },
      provider: { '@id': 'https://echo-ept.com/#organization' },
    },
    {
      '@type': 'SoftwareApplication',
      name: 'Echo Contracts',
      applicationCategory: 'BusinessApplication',
      operatingSystem: 'Web',
      description: 'AI contract management with e-signatures, risk analysis, clause library, version control, approval workflows, and expiry tracking.',
      url: 'https://echo-ept.com/contracts',
      offers: { '@type': 'AggregateOffer', lowPrice: '19', highPrice: '129', priceCurrency: 'USD', offerCount: 3 },
      provider: { '@id': 'https://echo-ept.com/#organization' },
    },
    {
      '@type': 'SoftwareApplication',
      name: 'Echo HR',
      applicationCategory: 'BusinessApplication',
      operatingSystem: 'Web',
      description: 'AI-powered HR management with employee onboarding, PTO tracking, performance reviews, compliance monitoring, and AI retention risk prediction.',
      url: 'https://echo-ept.com/hr',
      offers: { '@type': 'AggregateOffer', lowPrice: '29', highPrice: '149', priceCurrency: 'USD', offerCount: 3 },
      provider: { '@id': 'https://echo-ept.com/#organization' },
    },
    {
      '@type': 'SoftwareApplication',
      name: 'Echo Inventory',
      applicationCategory: 'BusinessApplication',
      operatingSystem: 'Web',
      description: 'AI inventory management with multi-warehouse tracking, demand forecasting, purchase orders, barcode scanning, and low-stock alerts.',
      url: 'https://echo-ept.com/inventory',
      offers: { '@type': 'AggregateOffer', lowPrice: '0', highPrice: '149', priceCurrency: 'USD', offerCount: 3 },
      provider: { '@id': 'https://echo-ept.com/#organization' },
    },
    {
      '@type': 'SoftwareApplication',
      name: 'Echo Workflow Automation',
      applicationCategory: 'BusinessApplication',
      operatingSystem: 'Web',
      description: 'Visual workflow builder with triggers, conditions, actions, and AI steps. Automate business processes across 18+ Echo services. Zapier alternative.',
      url: 'https://echo-ept.com/workflow-automation',
      offers: { '@type': 'AggregateOffer', lowPrice: '19', highPrice: '149', priceCurrency: 'USD', offerCount: 3 },
      provider: { '@id': 'https://echo-ept.com/#organization' },
    },
    {
      '@type': 'SoftwareApplication',
      name: 'Echo Forms',
      applicationCategory: 'BusinessApplication',
      operatingSystem: 'Web',
      description: 'AI-powered form builder with conditional logic, payment collection, file uploads, webhook integrations, and embeddable widgets.',
      url: 'https://echo-ept.com/forms',
      offers: { '@type': 'AggregateOffer', lowPrice: '0', highPrice: '99', priceCurrency: 'USD', offerCount: 3 },
      provider: { '@id': 'https://echo-ept.com/#organization' },
    },
    {
      '@type': 'SoftwareApplication',
      name: 'Echo Voice AI',
      applicationCategory: 'BusinessApplication',
      operatingSystem: 'Web',
      description: 'Voice cloning, text-to-speech, and speech-to-text with 69+ cloned voices, multi-provider TTS (ElevenLabs, Edge TTS), emotion detection, and persona switching.',
      url: 'https://echo-ept.com/voice',
      offers: { '@type': 'AggregateOffer', lowPrice: '29', highPrice: '299', priceCurrency: 'USD', offerCount: 3 },
      provider: { '@id': 'https://echo-ept.com/#organization' },
    },
    {
      '@type': 'SoftwareApplication',
      name: 'Permian Pulse',
      applicationCategory: 'BusinessApplication',
      operatingSystem: 'Web',
      description: 'AI-powered Permian Basin well data analytics with production decline modeling, lease evaluation, drilling cost optimization, and real-time WITS integration.',
      url: 'https://echo-ept.com/permian',
      offers: { '@type': 'AggregateOffer', lowPrice: '0', highPrice: '499', priceCurrency: 'USD', offerCount: 3 },
      provider: { '@id': 'https://echo-ept.com/#organization' },
    },
    {
      '@type': 'SoftwareApplication',
      name: 'Echo County Records',
      applicationCategory: 'BusinessApplication',
      operatingSystem: 'Web',
      description: 'Texas county deed record search with 259,000+ indexed instruments across 33 counties. OCR, entity resolution, and chain of title assembly.',
      url: 'https://echo-ept.com/county-records',
      offers: { '@type': 'AggregateOffer', lowPrice: '0', highPrice: '399', priceCurrency: 'USD', offerCount: 3 },
      provider: { '@id': 'https://echo-ept.com/#organization' },
    },
    {
      '@type': 'SoftwareApplication',
      name: 'Echo Bot Fleet',
      applicationCategory: 'BusinessApplication',
      operatingSystem: 'Web',
      description: 'Multi-platform AI bot management for Discord, Slack, X/Twitter, LinkedIn, Telegram, Reddit, and Instagram with autonomous posting, engagement, and analytics.',
      url: 'https://echo-ept.com/bots',
      offers: { '@type': 'AggregateOffer', lowPrice: '19', highPrice: '199', priceCurrency: 'USD', offerCount: 3 },
      provider: { '@id': 'https://echo-ept.com/#organization' },
    },
    {
      '@type': 'SoftwareApplication',
      name: 'Echo Live Chat',
      applicationCategory: 'BusinessApplication',
      operatingSystem: 'Web',
      description: 'AI-powered live chat widget with visitor tracking, canned responses, file sharing, chat routing, and CRM integration for websites.',
      url: 'https://echo-ept.com/live-chat',
      offers: { '@type': 'AggregateOffer', lowPrice: '19', highPrice: '149', priceCurrency: 'USD', offerCount: 3 },
      provider: { '@id': 'https://echo-ept.com/#organization' },
    },
    {
      '@type': 'SoftwareApplication',
      name: 'Echo Office AI',
      applicationCategory: 'BusinessApplication',
      operatingSystem: 'Web',
      description: 'Complete AI-powered business operations platform with 22 modules: invoicing, payroll, HR, inventory, CRM, bookkeeping, scheduling, and more.',
      url: 'https://echo-ept.com/office-ai',
      offers: { '@type': 'AggregateOffer', lowPrice: '49', highPrice: '399', priceCurrency: 'USD', offerCount: 3 },
      provider: { '@id': 'https://echo-ept.com/#organization' },
    },
    {
      '@type': 'SoftwareApplication',
      name: 'EchoCAD',
      applicationCategory: 'DesignApplication',
      operatingSystem: 'Web',
      description: 'AI-assisted CAD and design automation for engineering drawings, BOM generation, tolerancing, and manufacturing-ready output.',
      url: 'https://echo-ept.com/echocad',
      offers: { '@type': 'AggregateOffer', lowPrice: '99', highPrice: '499', priceCurrency: 'USD', offerCount: 3 },
      provider: { '@id': 'https://echo-ept.com/#organization' },
    },
    {
      '@type': 'SoftwareApplication',
      name: 'Daedalus Forge',
      applicationCategory: 'BusinessApplication',
      operatingSystem: 'Web',
      description: 'AI manufacturing intelligence: process optimization, quality prediction, supply chain analytics, and predictive maintenance for production environments.',
      url: 'https://echo-ept.com/daedalus-forge',
      offers: { '@type': 'AggregateOffer', lowPrice: '199', highPrice: '999', priceCurrency: 'USD', offerCount: 3 },
      provider: { '@id': 'https://echo-ept.com/#organization' },
    },
    {
      '@type': 'SoftwareApplication',
      name: 'Echo Crypto Trading',
      applicationCategory: 'FinanceApplication',
      operatingSystem: 'Web',
      description: 'AI cryptocurrency trading platform with real-time market analysis, automated trading strategies, portfolio tracking, and multi-exchange support.',
      url: 'https://echo-ept.com/crypto-trading',
      offers: { '@type': 'AggregateOffer', lowPrice: '29', highPrice: '299', priceCurrency: 'USD', offerCount: 3 },
      provider: { '@id': 'https://echo-ept.com/#organization' },
    },
    {
      '@type': 'SoftwareApplication',
      name: 'Echo Report Generator',
      applicationCategory: 'BusinessApplication',
      operatingSystem: 'Web',
      description: 'AI-powered professional report generation from 5,500+ intelligence engines. Doctrine-backed PDFs with authority citations, risk assessments, and adversary positions across 19 domains.',
      url: 'https://echo-ept.com/report-generator',
      offers: { '@type': 'AggregateOffer', lowPrice: '29', highPrice: '349', priceCurrency: 'USD', offerCount: 3 },
      provider: { '@id': 'https://echo-ept.com/#organization' },
    },
    {
      '@type': 'SoftwareApplication',
      name: 'Echo Analytics Engine',
      applicationCategory: 'BusinessApplication',
      operatingSystem: 'Web',
      description: 'Unified fleet analytics for AI infrastructure: engine metrics, doctrine tracking, fleet health scoring, growth trends, and multi-service aggregation across 90+ Cloudflare Workers.',
      url: 'https://echo-ept.com/analytics-engine',
      offers: { '@type': 'AggregateOffer', lowPrice: '19', highPrice: '249', priceCurrency: 'USD', offerCount: 3 },
      provider: { '@id': 'https://echo-ept.com/#organization' },
    },
  ],
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />
        <link rel="alternate" type="application/rss+xml" title="Echo Prime Technologies Changelog" href="/feed.xml" />
      </head>
      <body className="antialiased">
        <AuthProvider>
          <ThemeProvider>
            <ParticleBackground />
            <GuidedTutorialProvider>
              <ComingSoonGuard>
                {children}
              </ComingSoonGuard>
              <GuidedOverlay />
            </GuidedTutorialProvider>
            <EchoPrimeChat />
          </ThemeProvider>
        </AuthProvider>
        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  );
}
