'use client'

import ProductDoc from '@/components/ProductDoc'
import FaqSchema from '@/components/FaqSchema'
import BreadcrumbSchema from '@/components/BreadcrumbSchema'

const data = {
  name: 'Echo Arcanum',
  tagline: 'Sovereign prompt template library with 194+ indexed templates and build plans — the institutional memory of the Echo build system, where every completed build becomes a reusable asset.',
  accent: '#8b5cf6',
  productUrl: '/prompt-forge',
  workerUrl: 'https://echo-arcanum.bmcii1976.workers.dev',
  version: '2.0.0',
  overview: [
    'Echo Arcanum is the institutional knowledge layer of the Echo build system — a searchable library of 194+ sovereign prompt templates, build plans, and engineering specifications accumulated across every major build in the Echo ecosystem. Before any CC instance begins a new build, it searches Arcanum for existing templates that cover the target domain. Matching templates are retrieved and combined into a composite build plan, avoiding rediscovery of patterns that have already been solved and validated. This single protocol has compressed average build time by an estimated 60% compared to starting from scratch on each project.',
    'Templates in Arcanum are organized by quality tier: Sovereign (battle-tested, used in production builds, highest confidence), Gold (validated against real deployments, minor edge cases remain), and Silver (useful starting points, require adaptation). Every template carries domain and category tags, a free-text description, and the full template body. After completing a build, CC instances ingest the resulting specification back into Arcanum with a [BUILT] prefix tag — closing the loop from search to build to institutional memory. Over time, Arcanum accumulates not just abstract patterns but concrete, deployed implementations.',
    'The search interface supports semantic keyword search, exact slug retrieval, category browsing, and tag filtering. All searches are designed for rapid retrieval during active build sessions — the typical search-to-result cycle is <200ms even with the full 194+ template index. Templates can be retrieved individually or in bulk for combined analysis. The POST /prompts endpoint accepts both new templates from post-build ingestion and updated versions of existing templates, with automatic version history maintained in the backing D1 database.',
  ],
  gettingStarted: [
    { step: 1, title: 'Search Before You Build', desc: 'Before starting any build task, run 2-3 searches against Arcanum using different keyword angles: the task type (e.g., "cloudflare worker"), the domain (e.g., "rate limiting"), and the technology (e.g., "KV storage"). Retrieve all matching templates and combine their patterns into your build plan.' },
    { step: 2, title: 'Retrieve by Slug', desc: 'If you know the exact template slug, GET /prompts/by-slug/:slug returns the full template immediately. Slugs are URL-safe identifiers derived from the template name and are stable across updates. Use slugs to bookmark frequently-referenced templates.' },
    { step: 3, title: 'Browse by Category', desc: 'GET /prompts/categories returns the full category taxonomy with template counts. Browse categories like CLOUDFLARE_WORKER, NEXT_JS, AI_ENGINE, DATA_PIPELINE, SECURITY, or LANDMAN to discover templates by domain even when you are not sure what keywords to search.' },
    { step: 4, title: 'Create a Template', desc: 'After completing a build, ingest the result back as a template. POST /prompts with the template name (prefixed with [BUILT]), domain, category, content (the build spec or key patterns discovered), and quality_tier. This closes the build loop and makes your work reusable.' },
    { step: 5, title: 'Combine Templates', desc: 'For complex builds that span multiple domains, retrieve 2-3 matching templates and combine their patterns. A Worker build might combine the CLOUDFLARE_WORKER base template, a RATE_LIMITING pattern template, and an AI_ROUTING template. Synthesize them into a single build plan before starting implementation.' },
  ],
  features: [
    { title: '194+ Sovereign Templates', desc: 'Indexed library covering Cloudflare Workers, Next.js pages, AI engines, data pipelines, security systems, landman tools, tax analysis, bot frameworks, memory systems, and every other major domain in the Echo ecosystem. Every template has been used in at least one real build.' },
    { title: 'Semantic Search', desc: 'Full-text and semantic search across template names, descriptions, tags, and content bodies. Search returns ranked results with relevance scores. Multi-keyword queries use AND logic by default — all keywords must match — with OR mode available via the mode=any parameter.' },
    { title: 'Quality Tiers', desc: 'Three-tier quality system: Sovereign (production-validated, highest confidence), Gold (deployment-validated, minor gaps), Silver (useful starting points, require adaptation). Filter by tier to match your risk tolerance — use Sovereign templates for critical systems, Silver for rapid prototyping.' },
    { title: 'Domain and Category Taxonomy', desc: 'Templates are organized into 20+ categories covering the full Echo technology stack. Each template belongs to one primary category and can have multiple domain tags. Browsing by category surfaces templates you might not find with keyword search.' },
    { title: 'Build Plan Storage', desc: 'Full build plans — not just code snippets but complete implementation specs including architecture decisions, API contracts, deployment steps, and testing checklists — are stored as first-class templates. A build plan retrieved from Arcanum gives a CC instance the full execution roadmap without any planning phase.' },
    { title: 'Post-Build Ingestion Loop', desc: 'The [BUILT] prefix convention marks templates ingested from completed builds. These carry the highest practical value — not just the spec that was planned, but the implementation that actually shipped. [BUILT] templates are automatically ranked higher in search results for the same domain.' },
    { title: 'Slug-Based Retrieval', desc: 'Every template has a stable slug generated from its name. Slugs are URL-safe and persistent across template updates. The /prompts/by-slug/:slug endpoint enables direct linking from session preloads, CC journal entries, and build orchestrator configs.' },
    { title: 'Tag Filtering', desc: 'Each template carries multiple tags for cross-cutting concerns: "deployed", "built", "rate-limiting", "auth", "streaming", "cron", "websocket", "d1", "kv", "r2", and 50+ others. Filter GET /prompts by tag array to find templates matching specific technical requirements.' },
    { title: 'Version History', desc: 'Template updates are stored as new versions, not overwrites. The full version history is maintained in D1, allowing retrieval of prior versions by version number or timestamp. This enables teams to track how patterns evolved and roll back to earlier approaches if a newer version proves less effective.' },
    { title: 'Template Statistics', desc: 'GET /prompts/stats shows library-wide statistics: total templates by tier, most-searched terms, most-retrieved templates, recently added builds, and domain coverage map. Use stats to identify gaps in coverage — domains with few templates are candidates for new ingestion.' },
    { title: 'Bulk Template Retrieval', desc: 'Retrieve multiple templates in a single request by POSTing an array of slugs or IDs to /prompts/bulk. Returns all templates in the order requested. Used by build orchestrators to pre-load a set of templates at session start for offline use during a build session.' },
    { title: 'API Key Authentication for Writes', desc: 'Read operations (search, retrieve) are public — no auth required. Write operations (create, update, bulk-import) require the X-Echo-API-Key header with forge-x scope. This allows all CC instances to read freely while preventing unintentional writes from unauthenticated sources.' },
  ],
  apiEndpoints: [
    { method: 'GET', path: '/prompts/search', desc: 'Search templates by keyword. Query params: q (search text, required), domain, category, tier (sovereign|gold|silver), tags (comma-separated), limit (max 20, default 5), mode (all|any for multi-keyword). Returns ranked array of matching templates with relevance scores.', auth: false },
    { method: 'GET', path: '/prompts/by-slug/:slug', desc: 'Retrieve a single template by its stable slug identifier. Returns full template: id, name, slug, domain, category, tags, quality_tier, content, version, created_at, updated_at, and retrieval_count. 404 if slug does not exist.', auth: false },
    { method: 'POST', path: '/prompts', desc: 'Create a new template or update an existing one. Body: { name, domain, category, content, tags[], quality_tier, description }. If a template with the same name exists, creates a new version. Returns the created template with assigned id and slug.', auth: true },
    { method: 'GET', path: '/prompts/categories', desc: 'List all categories in the taxonomy with template counts per category and per quality tier within each category. Returns categories sorted by template count descending. Use to discover coverage and find relevant categories before searching.', auth: false },
    { method: 'GET', path: '/prompts/stats', desc: 'Library-wide statistics: total_templates, templates_by_tier, most_retrieved (top 10 by retrieval_count), most_searched (top 10 search terms), recently_added (last 10 templates), and domain_coverage (template count per domain).', auth: false },
    { method: 'GET', path: '/prompts/:id', desc: 'Retrieve a template by numeric ID. Returns the same full template object as /by-slug. Also accepts version parameter to retrieve a specific historical version.', auth: false },
    { method: 'POST', path: '/prompts/bulk', desc: 'Retrieve multiple templates in a single request. Body: { ids?: number[], slugs?: string[] }. Returns array of full template objects in the same order as the input array. Missing templates return null at their position.', auth: false },
    { method: 'GET', path: '/health', desc: 'Worker health status including D1 database connectivity, total template count, last ingestion timestamp, and cache hit rate. Returns HTTP 200 for healthy, 503 for degraded.', auth: false },
  ],
  userGuide: [
    { id: 'search-strategy', title: 'Effective Search Strategies', content: [
      'The most reliable Arcanum search strategy is to run 2-3 searches with different keyword angles before concluding a template does not exist. The same template may be indexed under its technology ("cloudflare workers"), its pattern type ("rate limiting"), its domain ("security"), or its implementation outcome ("KV sliding window"). A single search can miss it even if it exists.',
      'Start with the most specific query: the exact technology or pattern you need. If fewer than 3 results come back, broaden the query. Use the domain and category filters to narrow results when a broad keyword returns too many matches. The mode=any parameter is useful for discovery searches where partial matches are acceptable — a search for mode=any&q=auth+jwt+workers will return templates matching any of those three terms.',
      'For builds that span multiple domains — for example, a Worker that handles auth, queues jobs in KV, and calls an AI model — run separate searches for each domain (auth, KV job queue, AI routing). Retrieve the top result from each search and combine their patterns into a single build plan. Arcanum is optimized for this combine-and-synthesize workflow.',
    ]},
    { id: 'quality-tiers', title: 'Working with Quality Tiers', content: [
      'Sovereign-tier templates are the highest-confidence starting points. A Sovereign template has been used as the basis for a production deployment that is currently running. When you retrieve a Sovereign template for a Worker build, you are getting a pattern that has already passed Cloudflare\'s deployment pipeline, handled real traffic, and had any runtime errors resolved. Start with Sovereign templates for any build where reliability matters.',
      'Gold-tier templates have been validated against a real deployment but may have minor gaps — an edge case that was not exercised in the original build, or a configuration option that was not needed at the time. Gold templates require slightly more attention during adaptation but are far better than starting from scratch. Most templates are Gold tier.',
      'Silver-tier templates are useful starting points that have not yet been validated against a complete deployment. They may have been created from design specs, extracted from planning documents, or derived from partial implementations. Silver templates require the most adaptation work but are still faster than pure synthesis. After successfully adapting a Silver template in a production build, update its tier to Gold or Sovereign via POST /prompts.',
    ]},
    { id: 'ingestion-loop', title: 'The Post-Build Ingestion Loop', content: [
      'After completing any significant build — a new Worker, a complex page, a data pipeline, a security system — ingest the result back into Arcanum as a [BUILT] template. This is not documentation; it is institutional memory. The template body should capture: the final architecture decision, the key implementation patterns that worked, any patterns that were tried and abandoned, and the deployment configuration that succeeded in production.',
      'Use the [BUILT] prefix in the template name: "[BUILT] Echo Rate Limiter — KV Sliding Window". The prefix signals to search ranking that this template came from a deployed implementation rather than a design spec, and ranks it higher in search results. Tags should include "built", "deployed", the primary technology stack, and any significant patterns implemented.',
      'Templates do not need to be perfect prose. A [BUILT] template that captures the working wrangler.toml, the key routing pattern, the auth middleware code, and the health endpoint implementation in a single document is more valuable than a polished template that describes the approach in general terms. Future CC instances reading it want to see exactly what shipped — not what was planned.',
    ]},
    { id: 'combining-templates', title: 'Combining Templates into Build Plans', content: [
      'Complex builds typically require pulling from 2-5 Arcanum templates. The synthesis pattern is: retrieve all matching templates, identify the core structural template (usually the most specific match to the primary build target), and layer the supporting patterns from other templates on top of it. The core template provides the skeleton; supporting templates provide the organs.',
      'When two templates conflict on an implementation choice (for example, one uses D1 for rate limiting and another uses KV), prefer the Sovereign-tier template\'s approach and note the alternative in the build plan. If the two templates are the same tier, prefer the more recently created one — it reflects more current knowledge of what works in the Echo ecosystem.',
      'After a successful build that required combining templates, create a new Arcanum template that captures the combined approach. This composite template will save the next builder from having to do the same synthesis. The Echo Arcanum grows most useful when builders contribute composite templates from complex builds — not just the atomic patterns.',
    ]},
    { id: 'api-integration', title: 'Integrating Arcanum into Build Workflows', content: [
      'The Arcanum API is designed for automated consumption by CC instances, build orchestrators, and CI/CD pipelines. The most common automated pattern is: at session start, the build orchestrator retrieves the active task\'s domain tags and fires 2-3 Arcanum searches in parallel, pre-loading the matching templates into the session context before the CC instance begins work.',
      'For CI/CD integration, the post-build ingestion step can be added as a GitHub Actions workflow: after a successful Cloudflare Worker deployment, the workflow calls POST /prompts with the build specification, wrangler configuration, and deployment notes. This ensures ingestion happens automatically even if the CC instance\'s session ends before post-build tasks complete.',
      'The bulk retrieval endpoint (/prompts/bulk) is designed for session preload use cases. At the start of a long build session, retrieve all templates relevant to the planned work in a single call and cache them locally for the duration of the session. This eliminates search latency during the build itself and ensures consistent template content even if Arcanum is updated mid-session.',
    ]},
  ],
  aiCapabilities: [
    { capability: 'Semantic Search Ranking', desc: 'Search results are ranked by a combination of keyword match density, field weight (title matches rank higher than body matches), quality tier bonus (Sovereign ranks higher than Gold which ranks higher than Silver), recency (newer templates rank higher on ties), and retrieval count (frequently-retrieved templates surface higher, indicating community validation).' },
    { capability: 'Slug Generation', desc: 'Template slugs are generated deterministically from the name using URL normalization: lowercase, spaces to hyphens, special characters stripped, [BUILT] prefix to prefix:built tag. Slugs are checked for uniqueness at creation — conflicts add a numeric suffix. The algorithm ensures slugs are both human-readable and stable across updates.' },
    { capability: 'Content Indexing', desc: 'Template content is indexed for full-text search including code blocks, configuration examples, and command sequences within the template body. This means a search for "wrangler.toml" or "X-Echo-API-Key" finds templates that contain those exact strings in their implementation content, not just in their metadata.' },
    { capability: 'Related Template Suggestions', desc: 'GET /prompts/:id returns a related_templates array of 3-5 template IDs that share domain tags, category, or commonly co-retrieved patterns. This surfaces templates that experienced builders tend to retrieve together — indicating natural complementary relationships that automated keyword search might miss.' },
    { capability: 'Usage Analytics', desc: 'Every retrieval is counted per template (retrieval_count field). Templates with high retrieval counts receive a ranking boost in search results, creating a natural quality signal: templates that builders use repeatedly must be delivering value. The stats endpoint exposes retrieval counts for the top 10 most-used templates.' },
    { capability: 'Version Diffing', desc: 'When a template is updated, the system stores the full previous version and can generate a diff between any two versions on request. This enables CC instances and human reviewers to understand how a pattern evolved, which is valuable when a newer version appears to have regressed from an earlier approach.' },
  ],
  troubleshooting: [
    { issue: 'Search returns no results for a topic that should have coverage', solution: 'Try alternative keyword angles: the technology name, the pattern type, the problem being solved, and the target platform separately. Use GET /prompts/categories to see if the relevant domain category exists and has templates. If coverage is genuinely missing, search is working correctly — the template does not exist yet and should be created after the build.' },
    { issue: 'Template content looks outdated compared to current Echo patterns', solution: 'Check the template\'s updated_at timestamp and version number. If it predates recent architectural changes (SDK v3 migration, service binding updates), the template may need refreshing. Retrieve the template, update it for current patterns, and POST the updated version — Arcanum will create a new version while preserving the old one.' },
    { issue: 'POST /prompts returning 401 Unauthorized', solution: 'Write operations require the X-Echo-API-Key header with the forge-x API key (echo-omega-prime-forge-x-2026). Verify the header name is X-Echo-API-Key and the value is the forge-x key, not the vault master key. Read operations do not require auth — if reads are also failing, check the Worker health endpoint.' },
    { issue: 'Slug retrieval returning 404 for a known template', solution: 'Slugs are case-sensitive and space-free. If the template name contains special characters, the slug may differ from a naive URL-safe conversion. Use GET /prompts/search?q=<template name keywords> to find the template and retrieve its correct slug from the response.' },
    { issue: 'Template quality tier appears incorrect for a production-deployed build', solution: 'Update the tier via POST /prompts with the same slug and updated quality_tier field. Arcanum creates a new version, not an overwrite, so the old tier is preserved in version history. After update, the new tier takes effect immediately in search ranking.' },
  ],
  faq: [
    { q: 'What is a sovereign template?', a: 'A Sovereign template is one that has been validated against a production deployment that is currently running in the Echo ecosystem. The template captures patterns that shipped, not just patterns that were designed. Sovereign is the highest quality tier — use these as your starting point for any build where correctness and reliability are important.' },
    { q: 'How many templates are currently indexed?', a: 'Arcanum currently indexes 194+ templates across 20+ categories. The count grows continuously as CC instances ingest completed builds. GET /prompts/stats returns the live count at any time.' },
    { q: 'Should I ingest every build into Arcanum?', a: 'Yes for any build that involved non-trivial decisions or patterns: a new Worker architecture, a novel integration pattern, a complex auth scheme, a data pipeline design. Skip ingestion only for trivial bug fixes or single-line changes. The more signal Arcanum accumulates, the faster future builds go.' },
    { q: 'What format should template content be in?', a: 'Templates can be plain text, markdown, or a mix. The most valuable format for implementation templates is: a one-paragraph architecture summary, key configuration examples (wrangler.toml sections, environment variable names), critical code patterns (auth middleware, error handling, health endpoint), and deployment notes. Do not try to capture every line of code — capture the patterns and decisions that are not obvious.' },
    { q: 'Can I use Arcanum for non-Echo builds?', a: 'Yes. Arcanum is a general-purpose template library. Add templates for any technology or pattern relevant to your work. The domain and category taxonomy is flexible — add custom categories via the POST /prompts endpoint with any domain string. The search and retrieval infrastructure works equally well for any text content.' },
    { q: 'How is Arcanum different from the Knowledge Forge?', a: 'Arcanum stores build patterns, architectural decisions, and implementation templates — engineering knowledge for builders. Knowledge Forge stores factual domain knowledge — tax law, mineral rights doctrine, cybersecurity frameworks, medical standards. They serve different audiences: Arcanum for CC instances building systems, Knowledge Forge for domain engines answering professional questions.' },
  ],
}

export default function ArcanumDocPage() {
  return (
    <>
      <FaqSchema faqs={data.faq} name={data.name} />
      <BreadcrumbSchema items={[
        { name: 'Home', href: '/' },
        { name: 'Docs', href: '/docs' },
        { name: data.name, href: '/docs/arcanum' },
      ]} />
      <ProductDoc {...data} />
    </>
  )
}
