'use client'

import ProductDoc from '@/components/ProductDoc'

const data = {
  name: 'Echo Landman Pipeline',
  tagline: 'AI-powered title intelligence for oil & gas land professionals — chain of title investigation, division order calculation, mineral rights research, and title defect detection backed by 22 LM-series engines and live county record integration.',
  accent: '#f59e0b',
  productUrl: '/title-intelligence',
  workerUrl: 'https://echo-landman-pipeline.bmcii1976.workers.dev',
  version: '3.1.0',
  overview: [
    'Echo Landman Pipeline is a professional-grade title intelligence system built for landmen, oil & gas attorneys, and petroleum engineers who need fast, reliable chain of title analysis in the Permian Basin and surrounding Texas counties. The pipeline connects directly to county clerk systems across 33+ Texas counties via ShadowGlass browser automation, extracting real recorded instruments — deeds, assignments, releases, pooling agreements, and division orders — without manual data entry. Extracted records feed into the LM-series engine cluster (LM01 through LM22) where AI constructs the ownership chain, identifies gaps and defects, calculates mineral interest fractions, and generates professional run sheets.',
    'Each investigation is backed by 22 dedicated Landman Intelligence Engines that carry pre-compiled doctrine blocks from Texas land law: Rule of Capture, Duhig Rule, Mother Hubbard Clause interpretations, the Texas Mineral Interest Pooling Act, Railroad Commission spacing rules, and hundreds of cases from the Texas Supreme Court and Texas Courts of Appeals affecting mineral title. When the pipeline identifies a potential title defect, the relevant engine provides the legal authority for the defect classification, the curative options with their respective risk levels, and the standard cure documents for that defect type.',
    'The pipeline supports multi-tract analysis, allowing a single investigation job to cover an entire lease block or survey section simultaneously. Tract-level results are cross-referenced to identify common grantors across multiple tracts, shared defects, and pooled interest calculations. The run sheet output follows the AAPL standard format with AI-enhanced gap annotations, and is exportable as PDF, Excel, or structured JSON for integration with landman software systems. All investigations are logged with a complete audit trail of every county record fetched and every AI reasoning step taken.',
  ],
  gettingStarted: [
    { step: 1, title: 'Define Your Target Tract', desc: 'Navigate to echo-ept.com/title-intelligence or POST to /investigate with the legal description of the tract: county, abstract or survey, section, block, and township if applicable. For pooled units, provide all contributing tract descriptions.' },
    { step: 2, title: 'Select Investigation Depth', desc: 'Choose the search depth: Surface Only (deed records), Minerals Only (mineral chain), Full (both surface and mineral chains), or Custom (specify which instrument types to pull). Full investigation covers from patent to present.' },
    { step: 3, title: 'Pipeline Runs Automatically', desc: 'The pipeline fetches county records via ShadowGlass, classifies instruments with LM-series engines, constructs the ownership chain, and scores each interest transfer. Investigation jobs typically complete in 8-15 minutes for a single tract.' },
    { step: 4, title: 'Review the Run Sheet', desc: 'GET /run-sheet?job_id=<id> retrieves the complete run sheet with every instrument in chain-of-title order, mineral interest fractions at each transfer, identified gaps and defects with legal authority citations, and current ownership percentages.' },
    { step: 5, title: 'Export and Deliver', desc: 'Export the run sheet as a formatted PDF (AAPL standard layout), Excel workbook with separate tabs for instruments, current ownership, and defects, or JSON for integration with Quorum, Enertia, or custom systems.' },
  ],
  features: [
    { title: 'Chain of Title Investigation', desc: 'Full patent-to-present title chain construction from recorded county instruments. Each instrument in the chain is classified (deed, assignment, release, mortgage, court order, pooling agreement) and linked to its grantor and grantee with date, recording number, and volume/page reference.' },
    { title: 'Division Order Calculation', desc: 'Precise decimal interest calculations following Texas Proportionate Reduction Rule. Handles fractional mineral interests, royalty burdens, ORRI carve-outs, and net revenue interest computation from working interest and lease royalty terms.' },
    { title: 'County Record Integration', desc: 'Live connection to 33+ Texas county clerk systems including Midland, Ector, Andrews, Reeves, Ward, Winkler, Loving, Culberson, Pecos, Upton, Reagan, Crane, Glasscock, Howard, and Martin counties. Records are fetched in real-time via ShadowGlass browser automation against official county portals.' },
    { title: 'Title Defect Detection', desc: 'Automated identification of 40+ defect types: missing links in chain, unresolved mortgages, gap periods, ambiguous property descriptions, marital interest issues, heirship questions, probate gaps, adverse possession claims, and boundary conflicts. Each defect is cited to the relevant legal authority.' },
    { title: 'AI-Powered Gap Analysis', desc: 'LM-series engines analyze gaps in the title chain and classify them by severity: Curative Required (critical, investigation must pause), Curable (standard cure documents available), Minor (footnote quality, low risk), and Historical (pre-statehood, typically insurable).' },
    { title: 'Run Sheet Generation', desc: 'Professional AAPL-format run sheets automatically generated from the title chain. Includes all instruments in chronological order, interest fractions at each transfer, current ownership summary, defect annotations, and curative recommendations. Available in PDF, Excel, and JSON.' },
    { title: 'Multi-Tract Analysis', desc: 'Single investigation job covering multiple tracts simultaneously. Cross-references grantors appearing in multiple tract chains, identifies shared defects, aggregates pooled unit interests, and generates a combined ownership summary for the entire block.' },
    { title: 'Curative Recommendation Engine', desc: 'For each identified title defect, the pipeline recommends the appropriate cure: Affidavit of Heirship, Probate, Quitclaim Deed, Release of Lien, Stipulation of Interest, or other standard cure instruments. Templates for each cure type are available for immediate download.' },
    { title: 'Pooling & Unitization Analysis', desc: 'Analysis of Railroad Commission-approved pooling agreements, voluntary unit designations, and force-pooled units. Calculates participating area interests, computes the allocation factor for each tract, and flags non-participating mineral owners.' },
    { title: 'LM-Series Engine Cluster', desc: 'Twenty-two dedicated LM-series engines covering the full spectrum of Texas land law: LM01 (chain of title), LM04 (mineral interest fractions), LM07 (surface vs. mineral severance), LM12 (oil and gas lease terms), LM18 (Railroad Commission regulations), and 17 additional specialized engines.' },
    { title: 'Audit Trail', desc: 'Complete audit log for every investigation: which county records were fetched and when, which engine processed each instrument, confidence scores for each classification, and the full reasoning chain for every defect identified. Suitable for landman deliverable documentation.' },
    { title: 'Budget Estimation', desc: 'POST /estimate-budget with tract description and investigation depth to get an upfront cost and time estimate before committing to a full investigation. Estimates are based on historical run times for similar tracts and current county portal response times.' },
  ],
  apiEndpoints: [
    { method: 'POST', path: '/investigate', desc: 'Start a new title investigation. Body: { legal_description, county, investigation_depth, tracts[] }. Returns a job_id immediately. The investigation runs asynchronously — poll GET /jobs/:job_id for status and progress updates.', auth: true },
    { method: 'GET', path: '/jobs', desc: 'List all investigation jobs for the authenticated account. Supports filters: status (running|complete|error|queued), county, date range. Returns job metadata with progress percentages and estimated completion times.', auth: true },
    { method: 'GET', path: '/jobs/:id', desc: 'Get detailed status for a specific investigation job. Returns current phase (county_fetch|engine_analysis|run_sheet_generation|complete), progress percentage, instruments processed, defects found so far, and estimated time to completion.', auth: true },
    { method: 'GET', path: '/run-sheet', desc: 'Retrieve the completed run sheet for a job. Query params: job_id (required), format (json|pdf|excel, default json). JSON format returns the full structured run sheet with instruments array, current_ownership, defects, and curative_recommendations.', auth: true },
    { method: 'GET', path: '/title-graph', desc: 'Retrieve the ownership graph for a completed investigation as a directed acyclic graph. Nodes are owners (grantors/grantees), edges are instruments with date and fraction metadata. Useful for rendering visual title chain diagrams.', auth: true },
    { method: 'POST', path: '/estimate-budget', desc: 'Get an upfront cost and time estimate for a proposed investigation. Body: { legal_description, county, investigation_depth }. Returns estimated_cost_usd, estimated_duration_minutes, and county_complexity_score based on historical data.', auth: false },
    { method: 'GET', path: '/pipeline/stats', desc: 'Get pipeline performance statistics: investigations completed, average duration by county, average defects per investigation, most common defect types, and county portal uptime percentages. Useful for understanding expected turnaround before submitting a job.', auth: false },
    { method: 'GET', path: '/health', desc: 'Returns pipeline health including county portal connectivity status for all 33+ integrated counties, LM-engine cluster availability, ShadowGlass browser status, and queue depth. Critical for pre-submission validation.', auth: false },
  ],
  userGuide: [
    { id: 'how-investigations-work', title: 'How Investigations Work', content: [
      'When an investigation job is submitted, the pipeline enters the county_fetch phase. ShadowGlass opens a browser session against the target county\'s official clerk portal, searches by grantor/grantee surname index or legal description, and downloads all responsive instruments as PDFs. OCR extraction runs on each PDF to produce structured text. This phase typically takes 2-5 minutes per county and is the primary source of variance in total job time.',
      'With instruments extracted, the pipeline enters the engine_analysis phase. Each instrument is passed to an LM-series engine for classification and metadata extraction: instrument type, grantor, grantee, effective date, property description, interest conveyed, exceptions and reservations, and mortgage or lien details. LM01 constructs the chain by linking grantors to grantees in chronological order, resolving name variations (maiden names, entity name changes, abbreviated names) using the onomastics module.',
      'The run_sheet_generation phase takes the constructed chain and performs the interest arithmetic: starting from the original patent interest (typically 1/1 or the fraction that went to the patentee), applying each instrument\'s conveyance in sequence, tracking mineral reservations and royalty burdens, and arriving at the current ownership fractions. Interest calculations are presented in exact fractions and decimal equivalents, with intermediate steps shown for verification.',
    ]},
    { id: 'defect-classification', title: 'Understanding Title Defects', content: [
      'The pipeline classifies title defects into four severity tiers. Curative Required defects are fatal to the investigation — the title chain has a gap so material that an opinion cannot be rendered without additional research or curative documents. Examples: missing deed covering a 30-year period, recorded lis pendens against the property, or unresolved federal oil and gas lease that appears to still be in its primary term.',
      'Curable defects are serious but have established cure paths. Missing marital joinders on pre-1966 conveyances are typically cured with a Stipulation of Interest or Affidavit of Heirship. Unchained mortgages are cured with a Release of Lien. Ambiguous property descriptions that clearly reference the intended tract can be cured with a Correction Deed. For each Curable defect, the pipeline identifies the responsible party and the recommended cure document.',
      'Minor defects are note-quality issues: technical deficiencies that do not cloud the title but should be disclosed in a title opinion. Examples: acknowledgment defects on instruments executed outside Texas, improper use of an entity\'s former legal name, or failure to recite marital status on a grantor who was demonstrably single. Historical defects predate recorded history in the county or involve pre-statehood sovereign grants — these are typically noted and treated as waived for practical purposes.',
    ]},
    { id: 'county-integration', title: 'County Record Integration', content: [
      'The pipeline integrates with 33+ Texas county clerk systems using ShadowGlass browser automation. Each county integration is customized to that county\'s specific portal software — CAI Technologies, Tyler Technologies ECRM, Inpro, or county-specific custom systems. The integrations are maintained as individual ShadowGlass automation scripts and tested against live portals on a weekly schedule.',
      'County portal availability varies. Midland, Ector, and Andrews counties (core Permian Basin) have robust portals with 99%+ uptime and records back to the 1920s in digital form. Smaller counties (Loving, Culberson, Jeff Davis) have older systems with more limited digital records, requiring supplemental requests for older instruments. The /health endpoint shows current portal status for every integrated county.',
      'For counties not yet in the integration list, the pipeline can accept manually uploaded instrument PDFs via the /jobs/upload endpoint. Manual uploads are processed through the same OCR extraction and LM-engine analysis pipeline as electronically fetched records. Results are identical — only the county_fetch phase differs for manual uploads.',
    ]},
    { id: 'interest-calculations', title: 'Interest Calculations and Division Orders', content: [
      'Mineral interest arithmetic in Texas follows established rules but becomes complex quickly when interests have been subdivided across generations. The pipeline handles the full range of conveyance types: fee simple deeds conveying the mineral estate, mineral deeds conveying fractional interests expressed as fractions or percentages, royalty deeds conveying only the royalty right without the executive right, and assignments of oil and gas leases conveying working interest and overriding royalty interest.',
      'Division order calculations start from the net revenue interest (NRI) of each working interest owner and compute the decimal interest payable to each party. The Proportionate Reduction Rule is applied when the total working interest conveyed in a lease exceeds the mineral interest owned by the lessor — a common occurrence in Texas due to prior severed royalty interests and fractional mineral ownership across multiple heirs.',
      'The pipeline explicitly handles the Duhig Rule: when a grantor conveys a fractional mineral interest and warrants generally, but at the time of conveyance owns less than the amount conveyed, the grantor\'s retained interest is applied to cure the deficiency in the conveyance before the grantor benefits from any after-acquired title. The pipeline\'s Duhig module is backed by LM-series engine LM09, which carries 40+ Texas cases applying the rule across different factual patterns.',
    ]},
    { id: 'exporting-and-integrating', title: 'Exporting Results and Integration', content: [
      'Run sheets are available in three export formats. The PDF export follows the AAPL (American Association of Professional Landmen) standard run sheet format: instruments listed in chronological order, interest fractions shown at each transfer, a current ownership summary table at the end, and defect annotations in the margin with legal authority citations. The PDF is suitable for direct inclusion in landman title opinion packages.',
      'The Excel export generates a multi-tab workbook: Instruments (full instrument log with recording details), Current Ownership (ownership table with decimal interests), Defects (defect list with severity, description, and cure recommendation), and Pooling (unit interest calculations if applicable). Column formats are compatible with Quorum Land and Enertia import templates.',
      'The JSON export provides the complete investigation graph as a structured document — useful for integration with custom landman software, GIS systems, or internal title management databases. The schema follows the PPDM (Professional Petroleum Data Management) standard for land data where applicable.',
    ]},
  ],
  aiCapabilities: [
    { capability: 'Instrument Classification', desc: 'LM-series engines classify each instrument extracted from county records into 25+ instrument types with >98% accuracy. Classification considers instrument title, operative words of conveyance, legal description specificity, and grantee/grantor patterns. Ambiguous instruments are flagged for human review with alternative classification scores.' },
    { capability: 'Chain Construction', desc: 'LM01 constructs the title chain by resolving grantor-grantee links across instruments with name variations, entity name changes, and abbreviated descriptions. The engine uses a fuzzy match algorithm tuned for Texas land records to connect "J.T. Smith" to "James Thomas Smith" when the instruments reference the same survey.' },
    { capability: 'Defect Pattern Recognition', desc: 'AI identifies 40+ defect patterns by comparing the constructed chain against known defect signatures from Texas case law. The recognition engine is backed by LM-series doctrine blocks containing the case law establishing each defect type — enabling not just detection but immediate legal authority citation.' },
    { capability: 'Interest Arithmetic Verification', desc: 'Every interest calculation is independently verified by a symbolic arithmetic engine that tracks fractions exactly (no floating-point rounding) through the full conveyance chain. Discrepancies between the AI chain analysis and symbolic calculation are flagged as potential errors requiring review.' },
    { capability: 'Name Resolution', desc: 'Onomastics module resolves name variations in grantor/grantee chains: maiden-to-married name changes, entity legal name changes, abbreviations, and transcription errors in county records. Maintains a name synonym database built from resolved chains in prior investigations.' },
    { capability: 'Curative Intelligence', desc: 'For each defect, the curative recommendation engine matches the defect pattern to the appropriate cure instrument type, identifies the responsible party (grantor heir, lien holder, entity successor), and generates a first draft of the cure document using templates from the LM-series engine document library.' },
  ],
  troubleshooting: [
    { issue: 'Investigation job stuck in county_fetch phase for >20 minutes', solution: 'Check GET /health for the specific county\'s portal status. County clerk portals occasionally undergo maintenance or enforce rate limits. If the county is marked degraded, the job will resume automatically when the portal recovers. For urgent investigations, consider submitting manual instrument uploads via /jobs/upload to bypass portal dependency.' },
    { issue: 'Interest fractions in run sheet do not sum to 1/1', solution: 'This typically indicates a genuine gap in the mineral chain — the investigation did not find an instrument covering the entirety of the interest. Review the Defects section of the run sheet for Gap Period entries. If no gap is flagged, run GET /title-graph and verify that all instrument fractions in the chain were captured. Contact support with the job_id for a manual review.' },
    { issue: 'County records showing as unavailable for a specific county', solution: 'The county\'s portal may have changed its URL or login requirements. Check GET /pipeline/stats for that county\'s recent uptime percentage. Portal integrations are tested weekly but county systems update without notice. Submit a support ticket with the county name — portal updates are typically deployed within 24 hours.' },
    { issue: 'Run sheet missing instruments from a known recording', solution: 'The instrument may not yet appear in the county\'s digital index (newly recorded instruments can take 24-72 hours to appear in searchable indexes). If the instrument is old but missing, check that the recording volume and page are within the county portal\'s digitized range — some counties have records only from 1975 onward in digital form.' },
    { issue: 'LM engine flagging a defect that was already cured', solution: 'The cure instrument may not have been fetched from the county portal if it was recorded after the reference period of the title investigation, or if it was indexed under a different grantor name. Add the cure instrument via /jobs/upload and re-run the defect analysis phase by POSTing /jobs/:id/reanalyze.' },
  ],
  faq: [
    { q: 'Which Texas counties are integrated for live record fetching?', a: 'The pipeline integrates with 33+ Texas counties including all major Permian Basin counties: Midland, Ector, Andrews, Reeves, Ward, Winkler, Loving, Culberson, Pecos, Upton, Reagan, Crane, Glasscock, Howard, Martin, and 18 additional counties. The full list with portal status is available at GET /health.' },
    { q: 'How accurate is the interest fraction calculation?', a: 'Interest arithmetic is computed with exact fractions (no floating-point approximation) by a symbolic math engine. The calculation has been verified against manually computed division orders for 500+ test investigations with 100% agreement on valid chains. Discrepancies in real investigations always indicate a genuine gap or defect in the chain.' },
    { q: 'Can the pipeline analyze non-Texas properties?', a: 'The current release is calibrated for Texas law and Texas county record formats. Oklahoma support is planned for v4.0 (OU land court doctrine integration). New Mexico support is in development. The core pipeline architecture is jurisdiction-agnostic but the LM-engine doctrine blocks are Texas-specific.' },
    { q: 'How long does a typical investigation take?', a: 'Single-tract investigations in well-digitized Permian Basin counties (Midland, Ector, Andrews) complete in 8-12 minutes. Investigations covering older instruments, poorly digitized counties, or complex chains with many partial interest conveyances may take 20-30 minutes. Multi-tract jobs scale approximately linearly with tract count.' },
    { q: 'Is the run sheet acceptable for a title opinion?', a: 'The run sheet is professional-quality work product suitable as the factual basis for a landman\'s certification or an attorney\'s title opinion. It cites every instrument by recording reference and every legal authority for each defect classification. Final opinion responsibility remains with the signing landman or attorney.' },
    { q: 'How does the pipeline handle heirship and probate situations?', a: 'Heirship chains are analyzed by LM-series engines trained on Texas Estates Code provisions and Texas heirship case law. The pipeline identifies instruments where a party died while owning an interest, searches for probate records in the county index, and flags gaps where heirship documentation is missing. Affidavit of Heirship templates are available for undivided estate situations.' },
  ],
}

export default function LandmanPipelineDocPage() {
  return <ProductDoc {...data} />
}
