'use client'

import ProductDoc from '@/components/ProductDoc'
import FaqSchema from '@/components/FaqSchema'
import BreadcrumbSchema from '@/components/BreadcrumbSchema'

const data = {
  name: 'Echo News Scraper',
  tagline: 'Automated news and content scraping across RSS feeds, web sources, and social platforms — continuously feeding articles, summaries, and metadata into Knowledge Forge for indexing and discovery.',
  accent: '#ef4444',
  productUrl: '/news',
  workerUrl: 'https://echo-news-scraper.bmcii1976.workers.dev',
  version: '1.4.0',
  overview: [
    'Echo News Scraper is the content acquisition layer of the Echo intelligence stack — a high-throughput scraping system that continuously monitors hundreds of news sources, RSS feeds, industry publications, and social platforms to feed fresh content into the Knowledge Forge indexing pipeline. Unlike manual curation, the News Scraper runs on a Cloudflare Cron schedule, fetching and processing new articles every 2 hours without human intervention. Each article is extracted from its source HTML, stripped of navigation and advertising content, enriched with metadata (author, publication date, reading time, topic tags), and pushed to Knowledge Forge for full-text indexing and semantic embedding.',
    'The scraper handles the full range of content types and anti-scraping countermeasures encountered in the wild. Simple RSS-only sources are processed directly via the RSS parser. JavaScript-rendered pages that require browser execution are handled via ShadowGlass headless browser automation. Sources behind login walls (trade publications, research portals) use stored credentials from the vault to authenticate before extraction. Rate limiting and polite crawling delays are enforced per-domain to respect robots.txt and avoid bans. The source library currently covers 200+ active sources across AI/ML research, oilfield industry news, tax and legal publications, cybersecurity advisories, and financial markets.',
    'Content deduplication operates at two levels: URL-based deduplication catches the same article appearing from multiple scrape sources, and content-hash deduplication catches syndicated articles that appear on multiple publications under different URLs. Only unique content enters the Knowledge Forge pipeline, keeping the index clean and ensuring relevance scores reflect genuine diversity of coverage rather than duplication. Scraped articles older than 90 days are archived to R2 cold storage while remaining queryable — the working Knowledge Forge index stays performant while the full historical corpus remains accessible.',
  ],
  gettingStarted: [
    { step: 1, title: 'Browse Available Sources', desc: 'GET /sources returns all currently monitored sources with their status, last scrape timestamp, and category. Understand what is already being scraped before adding new sources — the topic you need may already have coverage.' },
    { step: 2, title: 'View Recent Articles', desc: 'GET /articles returns recently scraped articles, filterable by category, source, date range, and search keyword. This gives you visibility into what the scraper is currently finding and at what volume.' },
    { step: 3, title: 'Add a New Source', desc: 'POST to /sources with the source URL, type (rss|web|social), category, and optional credentials (for authenticated sources). The scraper will include the new source in the next scheduled cycle. For immediate ingestion, trigger POST /scrape with source_id.' },
    { step: 4, title: 'Trigger a Manual Scrape', desc: 'POST to /scrape with an optional source_id to run an immediate scrape. Without source_id, all sources run. The job runs asynchronously — the response includes a job_id for status polling. Useful when you need fresh content before the next scheduled cycle.' },
    { step: 5, title: 'Monitor Knowledge Forge Integration', desc: 'Every successfully scraped article is automatically forwarded to Knowledge Forge for indexing. Verify integration health with GET /health, which shows the last successful Knowledge Forge push timestamp and the count of articles pending in the push queue.' },
  ],
  features: [
    { title: 'RSS Feed Scraping', desc: 'Native RSS 2.0 and Atom feed parser covering the majority of structured news sources. Handles malformed feeds gracefully with fallback parsers. Full article body is fetched from the linked URL rather than relying on RSS summary truncation.' },
    { title: 'Web Scraping with ShadowGlass', desc: 'JavaScript-rendered pages and single-page applications are handled via ShadowGlass browser automation. The scraper waits for full page hydration before extracting content, capturing dynamically loaded articles that a simple HTTP fetch would miss.' },
    { title: 'Article Extraction Engine', desc: 'Custom content extraction removes navigation, headers, footers, advertisements, and social sharing widgets to isolate the article body. Extraction quality is tuned per source domain using custom CSS selectors when the generic readability algorithm underperforms.' },
    { title: 'Metadata Enrichment', desc: 'Each article is enriched with: canonical URL, author name and bio (when available), publication timestamp (falling back to scrape time), estimated reading time, topic tags extracted via NLP, and the Knowledge Forge document ID assigned after indexing.' },
    { title: 'Content Deduplication', desc: 'Two-layer deduplication: URL normalization (canonical URL comparison after stripping UTM params and tracking suffixes) and content-hash fingerprinting (MinHash of the first 1,000 words catches syndicated duplicates). Near-duplicate articles within 12 hours of each other are merged into a single record with multiple source attributions.' },
    { title: 'Knowledge Forge Integration', desc: 'Automatic push of every scraped article to echo-knowledge-forge for full-text indexing and semantic embedding. The push includes the article body, metadata, source domain, and category tags. Articles are queryable in Knowledge Forge within 60 seconds of scraping.' },
    { title: 'Scheduled Scraping', desc: 'Cloudflare Cron Triggers run full scrape cycles every 2 hours for standard sources and every 30 minutes for high-priority sources (marked with priority: high in source config). Cron schedule is configurable per source without a Worker redeploy.' },
    { title: 'Source Management', desc: 'Full CRUD API for the source library: add sources, update scraping configuration, pause individual sources without deleting them, and delete sources with optional article archive purge. Source health is monitored with per-source failure counters and automatic pause after 5 consecutive failures.' },
    { title: 'Category Classification', desc: 'Articles are classified into 15+ categories: AI/ML, Oilfield, Tax/Legal, Cybersecurity, Financial, Technology, Energy Markets, Real Estate, and more. Classification uses a combination of source-level default category and per-article NLP classification. Multi-category articles are tagged with all relevant categories.' },
    { title: 'Authenticated Source Support', desc: 'Sources requiring login (trade publications, premium research portals, restricted databases) are accessed using credentials stored in the Echo vault. Credentials are retrieved at scrape time, never stored in the Worker code or logs. Session cookies from authenticated sources are cached in KV for the duration of their validity.' },
    { title: 'Content Summarization', desc: 'Long-form articles (>1,500 words) are summarized via Engine Runtime\'s summarization capability, generating a 3-5 sentence executive summary stored alongside the full text. Summaries appear in GET /articles responses for quick review without fetching the full article body.' },
    { title: 'Archive to R2', desc: 'Articles older than 90 days are moved from the active D1 index to R2 cold storage (echo-prime-cold-archive bucket). Archived articles remain queryable via GET /articles with historical date filters — the archive is not deleted, just moved to cheaper storage. Knowledge Forge maintains semantic embeddings for all archived articles regardless of their storage tier.' },
  ],
  apiEndpoints: [
    { method: 'GET', path: '/articles', desc: 'List scraped articles with filters: category, source_id, q (full-text search), since (ISO timestamp), until (ISO timestamp), limit (max 100, default 20). Returns array of article records with id, title, url, source, category, scraped_at, summary, and kf_doc_id.', auth: false },
    { method: 'GET', path: '/sources', desc: 'List all configured scraping sources. Returns source_id, name, url, type (rss|web|social), category, status (active|paused|error), last_scrape, articles_last_7d, failure_count, and scrape_schedule. Filter by type or category using query params.', auth: false },
    { method: 'POST', path: '/scrape', desc: 'Trigger an immediate scrape. Body: { source_id? } — omit source_id to scrape all active sources. Returns job_id for async polling via GET /jobs/:id. The scrape runs the full pipeline: fetch, extract, deduplicate, enrich, push to Knowledge Forge.', auth: true },
    { method: 'GET', path: '/categories', desc: 'List all article categories with article counts, source counts per category, and last-scraped timestamp. Returns 15+ categories sorted by article_count descending. Use to understand coverage distribution and identify under-represented domains.', auth: false },
    { method: 'POST', path: '/sources', desc: 'Add a new scraping source. Body: { name, url, type (rss|web|social), category, schedule (2h|30m|daily), priority (normal|high), credentials_vault_key? }. Returns the new source record with assigned source_id. Source is included in the next scheduled cycle.', auth: true },
    { method: 'PUT', path: '/sources/:id', desc: 'Update an existing source configuration. Body fields: name, schedule, priority, status (active|paused), category, custom_selectors (for web sources). Pausing a source stops scraping without deleting it or its historical articles.', auth: true },
    { method: 'GET', path: '/articles/:id', desc: 'Retrieve a single article by ID. Returns full article record including the complete extracted body text, all metadata fields, deduplication status (original or duplicate_of), Knowledge Forge document ID, and summarization status.', auth: false },
    { method: 'GET', path: '/health', desc: 'Worker health status including total active sources, articles scraped in last 24 hours, Knowledge Forge push queue depth, last successful cron run timestamp, and per-category article counts. Returns HTTP 200 for healthy, 503 for degraded.', auth: false },
  ],
  userGuide: [
    { id: 'scraping-pipeline', title: 'The Scraping Pipeline', content: [
      'Each scrape cycle begins with source selection: all active sources are grouped by type (RSS, web, social) and scheduled into parallel fetch batches. RSS sources are fetched concurrently with a configurable concurrency limit (default 10 simultaneous feeds) to maximize throughput while staying within Cloudflare Worker CPU limits. Web sources requiring ShadowGlass are queued with a lower concurrency (default 3) to avoid overwhelming the browser automation layer.',
      'For each source, the fetch result is passed to the article extraction engine. RSS sources yield structured entries from the feed, but the scraper follows the item link to fetch the full article body (RSS entries are typically truncated). Web sources are processed with the readability algorithm, which identifies the main content block by analyzing DOM node density, link-to-text ratio, and common article container patterns. Custom CSS selectors stored in the source configuration override the readability algorithm for sources where it underperforms.',
      'Extracted articles pass through deduplication, metadata enrichment, NLP classification, and optional summarization before being written to D1 and pushed to Knowledge Forge. The full pipeline for a single article typically takes 2-5 seconds. Failed articles are logged with the failure reason (fetch error, extraction failure, dedup collision, Knowledge Forge push failure) and are excluded from the success count in the job report.',
    ]},
    { id: 'source-management', title: 'Managing Sources', content: [
      'Sources are the core configuration object in the News Scraper. Each source has a URL (RSS feed URL or web page URL), a type, a category for article classification, a scrape schedule (30 minutes, 2 hours, or daily), and a priority flag. High-priority sources run on the 30-minute cron while normal-priority sources run every 2 hours. Daily sources run once at 08:00 UTC.',
      'Source health is monitored by a failure counter. After 5 consecutive fetch or extraction failures, a source is automatically paused and flagged with status: error. This prevents a broken source from consuming Worker CPU on every cron cycle. Review errored sources with GET /sources?status=error and diagnose the failure cause from the failure_reason field before resuming with PUT /sources/:id with status: active.',
      'For sources requiring authentication, store credentials in the Echo vault before adding the source. Create a vault entry with service name matching your source, then reference it in POST /sources with credentials_vault_key: "<service-name>". The scraper retrieves the credential at scrape time and handles login via ShadowGlass for web sources or HTTP Basic/Bearer auth for API sources.',
    ]},
    { id: 'knowledge-forge-integration', title: 'Knowledge Forge Integration', content: [
      'Every scraped article is pushed to echo-knowledge-forge for full-text indexing and semantic embedding. The push includes the article body, title, URL, author, publication date, source domain, and category tags. Knowledge Forge assigns a document ID (kf_doc_id) that is stored back on the article record, enabling direct linking from the News Scraper article to the Knowledge Forge document.',
      'Articles pushed to Knowledge Forge become immediately searchable in Knowledge Forge\'s full-text index and available for semantic search within 60 seconds (the embedding pipeline runs asynchronously). This means fresh articles scraped this morning are already queryable by Intelligence Engines this afternoon. The integration is one-way — modifications to article records in Knowledge Forge are not reflected back in the News Scraper article store.',
      'If the Knowledge Forge push fails (typically due to temporary Worker unavailability), failed articles are queued in a KV-backed retry queue with exponential backoff. The queue is drained automatically — articles in the queue will be successfully pushed in subsequent attempts. The /health endpoint exposes the current push_queue_depth field, which should be near zero under normal operation.',
    ]},
    { id: 'deduplication', title: 'Deduplication and Content Quality', content: [
      'Article deduplication is critical for a multi-source scraping system. Without it, the same Reuters article appearing on 12 news aggregators would pollute the Knowledge Forge index with 12 copies of identical content, degrading search quality and wasting embedding compute. The News Scraper applies two deduplication passes: URL normalization and content fingerprinting.',
      'URL normalization strips tracking parameters (utm_*, fbclid, gclid, etc.), normalizes protocol (http → https), and removes trailing slashes. The canonical URL is then looked up in a 30-day KV store. Content fingerprinting uses a MinHash of the first 1,000 words of the article body, tolerating minor differences between syndicated versions (different headlines, added editor\'s notes) while still detecting clear duplicates.',
      'When a duplicate is detected, the article record is stored as a duplicate with a duplicate_of field pointing to the original. Duplicate records are not pushed to Knowledge Forge. However, source attribution is tracked — if an article appears on 5 sources, all 5 source URLs are stored on the original record. This attribution data surfaces in the Knowledge Forge document metadata, providing richer provenance for heavily covered stories.',
    ]},
    { id: 'monitoring-and-ops', title: 'Monitoring and Operations', content: [
      'The /health endpoint is the primary operational health signal. Key fields to monitor: cron_last_run (should be within 3 hours of now), kf_push_queue_depth (should be <50 under normal load), sources_active (should match expected count), and articles_last_24h (should be >20 for a well-configured source library). A zero articles_last_24h reading always indicates a problem.',
      'Source-level health is visible in GET /sources via the failure_count and last_scrape fields. Sources with failure_count > 0 but < 5 are degraded but still active. Sources with failure_count >= 5 have been auto-paused. Routine source failures are most commonly caused by: anti-scraping measures being added to a source (fix: update custom_selectors or add ShadowGlass routing), paywalls being added to previously free content (fix: add credentials), or RSS feed URL changes (fix: update source URL).',
      'For high-volume debugging, POST /scrape with a specific source_id and then poll GET /jobs/:id. The job result includes per-article processing logs: fetch status, extraction status (number of words extracted), dedup outcome (unique or duplicate_of ID), enrichment status, and Knowledge Forge push status. This article-level telemetry is the fastest path to diagnosing why a specific source is not contributing expected content.',
    ]},
  ],
  aiCapabilities: [
    { capability: 'Content Extraction', desc: 'Readability-based main content identification analyzes DOM node density, paragraph-to-navigation ratio, and link density to isolate article body from page chrome. Achieves >95% extraction accuracy on standard news pages. Source-specific CSS selector overrides handle edge cases where the generic algorithm underperforms.' },
    { capability: 'Category Classification', desc: 'NLP classification assigns articles to 15+ categories using a lightweight text classification model running within the Worker. Classification combines source-level default category with per-article keyword and topic analysis. Multi-category classification assigns all relevant categories rather than forcing a single label.' },
    { capability: 'Article Summarization', desc: 'Long-form articles are summarized via Engine Runtime\'s summarization endpoint, generating 3-5 sentence executive summaries in plain language. Summaries are stored alongside the full text and surfaced in API responses for quick scanning. Summarization runs asynchronously and does not block the Knowledge Forge push.' },
    { capability: 'Content Fingerprinting', desc: 'MinHash-based near-duplicate detection tolerates minor syndication differences (different headlines, added introductory paragraphs, slightly modified body) while still correctly identifying the underlying duplicate content. Fingerprints are computed in-Worker without external API calls, completing in <5ms per article.' },
    { capability: 'Metadata Extraction', desc: 'Structured metadata extraction from article HTML: author (byline parsing with entity recognition for multi-author bylines), publication date (from og:article:published_time, datePublished JSON-LD, byline date patterns, and URL date components as fallbacks), and reading time (from word count using 200 WPM baseline).' },
    { capability: 'Source Health Scoring', desc: 'Per-source rolling health score based on fetch success rate, extraction quality (median word count of extracted articles — low counts indicate extraction failures), deduplication rate (unusually high rates may indicate the source is syndicating from already-indexed sources), and Knowledge Forge acceptance rate.' },
  ],
  troubleshooting: [
    { issue: 'Source articles not appearing in Knowledge Forge searches', solution: 'Check GET /articles?source_id=<id> to verify articles are being scraped. If articles exist in the scraper but not Knowledge Forge, check the kf_push_queue_depth field in /health — a high queue depth indicates Knowledge Forge is temporarily unavailable and articles are queued for retry. If articles have kf_push_error on their records, check Knowledge Forge health at echo-knowledge-forge.bmcii1976.workers.dev/health.' },
    { issue: 'Web source returning empty or garbled content', solution: 'The readability extraction algorithm may be failing on this source\'s page structure. Add custom CSS selectors via PUT /sources/:id with custom_selectors: { article_body: ".article-text", title: "h1.headline" }. Inspect the source page HTML to identify the correct selectors. For JavaScript-rendered sources, ensure type is set to web (not rss) to route through ShadowGlass.' },
    { issue: 'Same article appearing multiple times in search results', solution: 'If duplicates are appearing in Knowledge Forge, the content fingerprinting may not have caught the near-duplicates (possible if the syndicated versions differ significantly in wording). Manually mark duplicates via PUT /articles/:id with duplicate_of: <original_id>. Marked duplicates will be removed from Knowledge Forge on the next cleanup cycle.' },
    { issue: 'Cron scrape not running on schedule', solution: 'Check the Cloudflare Workers Cron Triggers configuration in the Cloudflare dashboard — cron triggers can be inadvertently disabled during Worker updates. Verify the cron_last_run timestamp in /health to confirm the trigger is firing. If the cron is running but articles_last_24h is zero, all sources may be paused — check GET /sources?status=active for the active source count.' },
    { issue: 'Authenticated source failing with 401 after weeks of successful scraping', solution: 'The stored session credential has likely expired. Retrieve the vault entry for the source credential (credentials_vault_key in the source record) and check the expiry. For OAuth-based sources, the refresh token may have expired — log in manually via ShadowGlass to generate a fresh token and update the vault entry.' },
  ],
  faq: [
    { q: 'How many sources are currently monitored?', a: 'The scraper currently monitors 200+ active sources across AI/ML research, oilfield industry, tax and legal publications, cybersecurity advisories, and financial markets. GET /sources returns the full list with per-source health and article volume statistics.' },
    { q: 'How long does it take for a new article to be searchable in Knowledge Forge?', a: 'Articles scraped in the current 2-hour cron cycle are pushed to Knowledge Forge immediately after extraction. Full-text search availability is immediate on push. Semantic embedding (for vector/similarity search) takes an additional 30-60 seconds as the embedding pipeline runs asynchronously. End-to-end from publication to Knowledge Forge searchability: typically 1-3 hours depending on where in the cron cycle the article was published.' },
    { q: 'Does the scraper handle paywalled sources?', a: 'Yes, for sources where we have valid credentials. Store the login credentials in the Echo vault, then add the source with credentials_vault_key referencing the vault entry. ShadowGlass handles authentication for web-based paywalls. For API-gated sources, Bearer or Basic auth headers are added to the fetch. Sources that cannot be authenticated are scraped for publicly available content only.' },
    { q: 'How is robots.txt compliance handled?', a: 'The scraper respects robots.txt for all web sources. robots.txt is fetched and cached at the start of each cron cycle. If the scraper\'s user-agent or a specific URL pattern is disallowed, the source is skipped and marked with status: robots_disallowed. This can be overridden in source configuration for sources where scraping is authorized under contract or terms of service.' },
    { q: 'How long are article records retained?', a: 'Articles stay in the active D1 index for 90 days. After 90 days, records are archived to R2 cold storage (echo-prime-cold-archive) but remain queryable via GET /articles with historical date filters. Knowledge Forge semantic embeddings are not deleted — archived articles remain searchable indefinitely via Knowledge Forge semantic search.' },
    { q: 'Can the News Scraper feed into systems other than Knowledge Forge?', a: 'Yes. In addition to the automatic Knowledge Forge push, GET /articles with a since parameter provides an incremental pull interface for any downstream consumer. This is used by Knowledge Scout to cross-reference web-scraped articles with its own discovery feed, and by the daily news digest generator. Custom webhooks for article events (new article, category threshold reached) are planned for v2.0.' },
  ],
}

export default function NewsScraperDocPage() {
  return (
    <>
      <FaqSchema faqs={data.faq} name={data.name} />
      <BreadcrumbSchema items={[
        { name: 'Home', href: '/' },
        { name: 'Docs', href: '/docs' },
        { name: data.name, href: '/docs/news-scraper' },
      ]} />
      <ProductDoc {...data} />
    </>
  )
}
