'use client'

import ProductDoc from '@/components/ProductDoc'
import FaqSchema from '@/components/FaqSchema'
import BreadcrumbSchema from '@/components/BreadcrumbSchema'

const data = {
  name: 'Echo Fleet Commander',
  tagline: 'Unified command and control for 200+ Cloudflare Workers. Fleet-wide deployment coordination, health monitoring, service discovery, and automated failure recovery — all from one interface.',
  accent: '#0ea5e9',
  productUrl: '/orchestration',
  workerUrl: 'https://echo-fleet-commander.bmcii1976.workers.dev',
  version: '3.0.0',
  overview: [
    'Echo Fleet Commander is the operational backbone of the entire Echo Worker fleet. At any given time, 200+ Cloudflare Workers are running across the Echo ecosystem — handling API requests, processing background jobs, ingesting data, running inference, serving websites, and coordinating inter-service communication. Fleet Commander knows the state of every one of them: which are healthy, which have elevated error rates, which are processing how many requests per second, which versions are deployed, and which are due for a rolling update.',
    'The platform provides three core functions. First, observability: Fleet Commander aggregates health endpoint data from every registered Worker into a unified status view, correlating anomalies across services so you can see that five Workers went unhealthy at the same time and trace the common upstream dependency causing the cascade. Second, orchestration: deployments, rollbacks, configuration pushes, and secret rotations are coordinated fleet-wide through Fleet Commander, which handles sequencing, canary releases, and automatic rollback if a deployment degrades health metrics. Third, communication: Workers that need to coordinate with each other route requests through Fleet Commander\'s relay layer rather than calling each other\'s public URLs, which enables service discovery, load balancing, circuit breaking, and topology changes without code changes.',
    'Fleet Commander integrates directly with the Cloudflare Workers API and wrangler CLI for deployment operations, the Build Orchestrator for CI/CD pipeline coordination, and the Vault API for secret distribution. It maintains a real-time service registry in D1 that every Worker can query to discover the current URL and capabilities of any other service in the fleet. The registry is the source of truth — when a Worker moves, gets renamed, or gets a new binding, the registry updates and all dependent Workers automatically resolve the new endpoint.',
  ],
  gettingStarted: [
    { step: 1, title: 'Register Your Workers', desc: 'Call POST /fleet/workers/register with your Worker name, health endpoint URL, and capability tags. Fleet Commander will begin polling your health endpoint every 30 seconds and include your Worker in fleet-wide status reports.' },
    { step: 2, title: 'Browse Fleet Status', desc: 'Navigate to /orchestration to view the real-time fleet dashboard. Workers are grouped by domain cluster (AI, Data, Security, Commerce, Communication, Infrastructure). Each card shows current status, request rate, error rate, and last deployment timestamp.' },
    { step: 3, title: 'Configure Health Thresholds', desc: 'Set custom health degradation thresholds per Worker via PATCH /fleet/workers/:id/config. Define what error rate constitutes DEGRADED vs. CRITICAL, latency thresholds for p95 response time, and minimum healthy replica count for load-balanced Workers.' },
    { step: 4, title: 'Set Up Deployment Pipeline', desc: 'Connect your GitHub repository to Fleet Commander\'s deployment webhook. When a build passes the Build Orchestrator gates, Fleet Commander takes over: deploys to 5% canary, monitors for 10 minutes, promotes to 50%, monitors again, then completes the rollout.' },
    { step: 5, title: 'Enable Inter-Service Routing', desc: 'Update Workers that call other Workers to route through Fleet Commander\'s relay endpoint instead of hardcoding Worker URLs. This enables service discovery, load balancing, and automatic failover when downstream Workers restart or move.' },
  ],
  features: [
    { title: 'Fleet-Wide Health Monitoring', desc: 'Polls /health endpoints on all registered Workers every 30 seconds. Aggregates status into three tiers: HEALTHY (all systems nominal), DEGRADED (elevated errors or latency), CRITICAL (service unavailable or below minimum replicas). Fleet-level health is the combined state of all Workers.' },
    { title: 'Deployment Coordination', desc: 'Orchestrates rolling deployments across the fleet with configurable canary percentages (5/25/50/100%), health-check gates between stages, automated rollback on degradation detection, and deployment sequencing to respect service dependency order.' },
    { title: 'Service Discovery Registry', desc: 'Maintains a real-time service registry in D1 mapping every Worker name to its current URL, capabilities, version, health status, and binding configuration. Workers query the registry at startup so they always resolve the current endpoint of any dependency.' },
    { title: 'Load Balancing', desc: 'For Workers with multiple replicas or regional deployments, Fleet Commander distributes inbound requests using weighted round-robin, least-connections, or latency-based routing. Load balancing weights update automatically based on real-time health metrics.' },
    { title: 'Inter-Worker Communication Relay', desc: 'Workers route service-to-service requests through Fleet Commander\'s relay layer. Fleet Commander handles service resolution, applies circuit-breaking rules, adds distributed tracing headers, logs the call for dependency mapping, and routes to the healthiest available instance.' },
    { title: 'Automated Restart on Failure', desc: 'When a Worker enters CRITICAL state for more than 60 seconds, Fleet Commander triggers an automatic redeploy via the Cloudflare Workers API using the last known-good version tag. Restart events are logged and alert notifications are fired to configured channels.' },
    { title: 'Deployment Rollback', desc: 'Every deployment preserves the previous version tag in the registry. Rollback to any previous version in one API call or one click in the dashboard. Fleet Commander replays the deployment pipeline in reverse, restoring configuration, secrets, and Worker code atomically.' },
    { title: 'Version Tracking Across All Workers', desc: 'Fleet Commander maintains a complete deployment history for every Worker: version tag, deployed timestamp, deploying user or CI pipeline, health metrics at deployment, and whether the deployment was promoted, rolled back, or superseded. Full audit trail for compliance.' },
    { title: 'Resource Utilization Metrics', desc: 'Aggregates CPU time, memory usage, request count, error count, and duration metrics from Cloudflare Analytics for every Worker. Surfaces per-Worker and fleet-wide utilization trends so over-provisioned Workers can be scaled down and bottlenecks can be identified before they cascade.' },
    { title: 'Fleet-Wide Configuration Management', desc: 'Push environment variable updates, binding changes, and wrangler.toml modifications to groups of Workers simultaneously. Configuration changes go through the same canary+gate pipeline as code deployments so a bad config push is automatically detected and rolled back.' },
    { title: 'Broadcast Messaging', desc: 'Send operational messages to all registered Workers or filtered subsets via POST /fleet/broadcast. Workers that have registered a /broadcast endpoint receive the message and can take action (flush caches, reload configuration, trigger self-diagnostics, gracefully drain connections).' },
    { title: 'Dependency Topology Mapping', desc: 'Fleet Commander infers the service dependency graph from relay call logs. The topology view shows which Workers call which other Workers, call frequency, latency distributions, and failure rates. Cascading failures are traceable to their origin in the topology graph.' },
  ],
  apiEndpoints: [
    { method: 'GET', path: '/fleet/status', desc: 'Returns overall fleet health summary: total Workers registered, healthy/degraded/critical counts, fleet-level uptime percentage, active incidents, and pending deployments. Includes a per-cluster breakdown with representative Workers.', auth: false },
    { method: 'GET', path: '/fleet/workers', desc: 'List all registered Workers with current status, version, health metrics (error rate, p95 latency, rps), last deployment timestamp, and capability tags. Supports filtering by status, cluster, and capability. Paginated with cursor support.', auth: true },
    { method: 'POST', path: '/fleet/deploy', desc: 'Trigger a deployment for one or more Workers. Accepts Worker name(s), version tag or latest, canary percentage, gate wait duration, and rollback threshold. Returns deployment_id for tracking progress via GET /fleet/deploy/:id/status.', auth: true },
    { method: 'POST', path: '/fleet/rollback', desc: 'Rollback a Worker to a specified previous version or to the last-known-good tag. Accepts Worker name and target version. Initiates the canary rollback pipeline and returns rollback_id. Can force-immediate rollback for CRITICAL incidents by setting force: true.', auth: true },
    { method: 'GET', path: '/fleet/health', desc: 'Retrieve the current health snapshot for all Workers or a specific Worker. For each Worker: HTTP status of last /health poll, response body, latency, error rate, consecutive failure count, and health state (HEALTHY/DEGRADED/CRITICAL/UNKNOWN).', auth: true },
    { method: 'GET', path: '/fleet/metrics', desc: 'Fetch utilization metrics aggregated from Cloudflare Analytics. Supports time range (last 1h/24h/7d/30d), per-Worker or fleet-aggregate mode, and metric selection (cpu_time, requests, errors, duration, bandwidth). Returns time-series data suitable for dashboard charting.', auth: true },
    { method: 'POST', path: '/fleet/broadcast', desc: 'Send a broadcast message to all registered Workers or a filtered subset (by cluster, capability tag, or name regex). Message payload is forwarded to each Worker\'s /broadcast endpoint. Returns delivery status per Worker with any error details.', auth: true },
    { method: 'GET', path: '/health', desc: 'Fleet Commander self-health check. Returns service status, registry Worker count, last poll cycle timestamp, deployment queue depth, and active incident count. Used by external monitoring to verify Fleet Commander itself is operational.', auth: false },
  ],
  userGuide: [
    { id: 'fleet-topology', title: 'Understanding Fleet Topology', content: [
      'The Echo Worker fleet is organized into domain clusters: AI (Engine Runtime, Doctrine Forge, Inference), Data (Knowledge Forge, Knowledge Harvester, Cognition Cloud), Security (Sentinel, Prometheus, ShadowGlass), Commerce (Payments, Stripe, Invoicing), Communication (Echo Chat, TTS, Messaging), and Infrastructure (Build Orchestrator, Fleet Commander itself, SDK Gateway). Each cluster has a designated lead Worker that other clusters route to when communicating cross-cluster.',
      'Workers within a cluster communicate via service bindings (direct Cloudflare service-to-service calls with no public internet round-trip). Workers across clusters communicate via the Fleet Commander relay layer, which provides a consistent abstraction, adds circuit breaking, and logs cross-cluster call patterns for the dependency topology map.',
      'The service registry is the single source of truth for Worker locations. Even if you know a Worker\'s URL, always resolve it through the registry so you automatically benefit from failover routing, canary routing during deployments, and load balancing. Workers that hardcode other Workers\' URLs become a deployment liability.',
    ]},
    { id: 'deployment-pipeline', title: 'The Deployment Pipeline', content: [
      'Every deployment managed by Fleet Commander follows the same pipeline: BUILD → VALIDATE → CANARY (5%) → GATE_1 (10 minutes) → PARTIAL (50%) → GATE_2 (5 minutes) → FULL (100%) → VERIFY → COMPLETE. Gates consist of health checks against configurable thresholds. If a gate fails, the deployment automatically pauses and, if not manually overridden within 5 minutes, rolls back.',
      'Canary routing during a deployment is handled transparently. Fleet Commander routes 5% of requests to the new version while 95% continue to the old version. Your monitoring dashboards will see slightly elevated error rates on the new version during testing. If the error rate on the canary exceeds the rollback threshold, the pipeline halts and all traffic reverts to the stable version.',
      'For Workers with zero-downtime requirements, Fleet Commander supports blue-green deployments: the new version is fully deployed as a parallel "green" set, traffic is cut over atomically, and the "blue" set remains on standby for 15 minutes before decommissioning. Blue-green is the default for Workers in the AI and Security clusters.',
    ]},
    { id: 'health-monitoring', title: 'Health Monitoring and Alerts', content: [
      'Fleet Commander expects every registered Worker to expose a GET /health endpoint that returns HTTP 200 with a JSON body containing at minimum { "status": "healthy|degraded|critical", "version": "semver" }. Additional fields like queue_depth, active_connections, and last_processed_at enrich the fleet health view.',
      'Health state transitions trigger configurable actions. HEALTHY→DEGRADED triggers a notification. DEGRADED→CRITICAL triggers a notification plus an automatic redeploy attempt. CRITICAL for more than 300 seconds with no recovery triggers a PagerDuty-style escalation. All thresholds are configurable per Worker and can be temporarily adjusted during known maintenance windows.',
      'The fleet health dashboard aggregates Worker health into a composite fleet score (0-100). The score weights Workers by their criticality tier (tier 1 Workers count more than tier 3). A fleet score above 95 is GREEN, 80-95 is YELLOW, below 80 is RED. The score is exposed via /fleet/status for integration with external status page monitors.',
    ]},
    { id: 'service-discovery', title: 'Service Discovery and Routing', content: [
      'Service discovery is built on the D1 registry, which stores every Worker\'s name, URL, capabilities, version, and health state. Workers call GET /registry/:name to resolve another Worker\'s current endpoint. The lookup adds ~2ms of latency compared to a hardcoded URL but provides automatic failover routing when the primary endpoint is unhealthy.',
      'Capability-based routing allows Workers to query "find me a healthy Worker with capability text_generation and domain tax" rather than referencing a specific Worker name. Fleet Commander returns the healthiest matching Worker. This enables load balancing across multiple Workers with the same capability and automatic failover to a standby Worker when the primary is down.',
      'Circuit breaking is enforced at the relay layer. If a downstream Worker has a 50%+ error rate on relay-routed requests, Fleet Commander opens the circuit: subsequent requests immediately return a 503 with a Retry-After header rather than waiting for a timeout. The circuit closes automatically when the downstream Worker\'s health recovers.',
    ]},
    { id: 'incident-response', title: 'Incident Response and Recovery', content: [
      'When Fleet Commander detects a cascading failure — multiple Workers degrading in sequence within a short window — it enters incident mode. In incident mode, Fleet Commander suppresses non-critical alerts, halts non-emergency deployments, and focuses all automated recovery actions on stabilizing the affected cluster.',
      'Automated recovery follows a three-step escalation: first, Fleet Commander attempts a warm restart (sends a /broadcast restart message and waits 30 seconds). If health does not recover, it triggers a forced redeploy using the last-known-good version. If redeploy fails or health still does not recover, it escalates to human notification with a full incident diagnostic bundle attached.',
      'Post-incident reports are generated automatically 30 minutes after health fully recovers. The report includes the incident timeline, root cause hypothesis (derived from dependency topology and error log correlation), all automated actions taken, their outcomes, and recommended follow-up actions for preventing recurrence.',
    ]},
  ],
  aiCapabilities: [
    { capability: 'Anomaly Detection in Health Metrics', desc: 'LSTM-based time-series anomaly detection on per-Worker health metrics. Fleet Commander learns the normal error rate and latency curves for each Worker across time-of-day and day-of-week cycles. Deviations from learned baselines trigger early warnings before thresholds are breached.' },
    { capability: 'Cascading Failure Prediction', desc: 'Graph neural network analyzes the dependency topology during degradation events. When a Worker enters DEGRADED state, the model predicts which downstream Workers are at risk based on their dependency on the degrading Worker and their current buffer capacity.' },
    { capability: 'Deployment Risk Scoring', desc: 'Before approving a deployment, Fleet Commander scores its risk based on the size of the code diff, the Worker\'s criticality tier, the current fleet health state, the time of day, and historical deployment success rates for this Worker. High-risk deployments require explicit override confirmation.' },
    { capability: 'Root Cause Correlation', desc: 'When multiple Workers degrade simultaneously, AI correlates error logs, dependency calls, and health metric timelines to identify the common upstream cause. The root cause hypothesis is surfaced in the incident record with a confidence score and supporting evidence.' },
    { capability: 'Capacity Trend Forecasting', desc: 'Based on historical request volume trends, Fleet Commander forecasts capacity headroom for each Worker over the next 7 and 30 days. Workers approaching capacity limits are flagged for upgrade planning before they become production incidents.' },
    { capability: 'Self-Healing Orchestration', desc: 'Fleet Commander uses reinforcement learning to optimize its recovery action sequencing. It tracks which recovery actions (warm restart vs. forced redeploy vs. traffic rerouting) are most effective for each failure mode per Worker, and preferentially applies the highest-success-rate action first in future incidents.' },
  ],
  troubleshooting: [
    { issue: 'Worker shows as UNKNOWN status in fleet dashboard', solution: 'UNKNOWN means Fleet Commander cannot reach the Worker\'s /health endpoint. Verify the health endpoint URL in the registry is correct and the endpoint returns HTTP 200. Check Cloudflare Worker status in the Cloudflare dashboard — the Worker may have hit CPU or memory limits. Re-register the Worker with the correct health URL via PATCH /fleet/workers/:id.' },
    { issue: 'Deployment stuck at CANARY stage for over 30 minutes', solution: 'The canary gate is evaluating health metrics against your configured thresholds. Check the deployment log via GET /fleet/deploy/:id/status for specific gate failure reasons. If metrics look good but the gate is still blocking, the threshold may be misconfigured — compare the current metrics against the gate thresholds in your Worker config and adjust via PATCH /fleet/workers/:id/config.' },
    { issue: 'Service discovery returning stale URLs after a Worker rename', solution: 'The registry updates on Worker re-registration. After renaming a Worker, call POST /fleet/workers/register with the new name and URL. The old registry entry will be marked DEPRECATED and removed after 24 hours. Workers still resolving the old name will get a 301 redirect to the new name during the transition window.' },
    { issue: 'Relay calls returning 503 Circuit Open errors', solution: 'The circuit breaker is open because the downstream Worker has exceeded its error threshold. Check the downstream Worker\'s health via GET /fleet/workers/:downstream_id. If the Worker is healthy again, force the circuit closed via POST /fleet/circuit/:worker_id/close. If the Worker is still unhealthy, fix the underlying issue before closing the circuit.' },
    { issue: 'Fleet health score is low but all Workers show HEALTHY', solution: 'The fleet score is weighted by Worker criticality tier. A DEGRADED tier-1 Worker (like Engine Runtime or SDK Gateway) contributes more to the score drop than ten healthy tier-3 Workers. Check which Workers are in DEGRADED state — they may be above your CRITICAL threshold but still dragging the weighted average down. Review and adjust tier assignments via the Worker registry.' },
  ],
  faq: [
    { q: 'How does Fleet Commander differ from the Build Orchestrator?', a: 'The Build Orchestrator manages the CI/CD pipeline: building code, running tests, and gate approvals. Fleet Commander takes over after a build passes all gates: it handles the actual deployment to Cloudflare, canary routing, health monitoring during rollout, and post-deployment verification. They are complementary systems in the same pipeline.' },
    { q: 'Can Fleet Commander manage Workers that are not part of the Echo ecosystem?', a: 'Yes. Any Cloudflare Worker can register with Fleet Commander by calling POST /fleet/workers/register. The only requirement is a /health endpoint that returns { "status": "healthy|degraded|critical" }. Third-party or client Workers can participate in health monitoring, service discovery, and broadcast messaging without being part of the core Echo codebase.' },
    { q: 'What happens to in-flight requests during a deployment?', a: 'Cloudflare handles graceful request draining natively. During a canary deployment, requests are routed by Fleet Commander to either the old or new version based on the canary percentage. In-flight requests to the old version complete normally. There is no dropped traffic during a standard rolling deployment.' },
    { q: 'How does Fleet Commander handle Cloudflare rate limits during fleet-wide operations?', a: 'Fleet Commander batches Cloudflare API calls and respects the 1200 req/5min Workers API rate limit by queuing operations and spacing them with adaptive delays. Large fleet operations (deploying all 200 Workers simultaneously) are automatically sequenced in batches of 20 with 10-second spacing to stay within limits.' },
    { q: 'Is Fleet Commander itself a single point of failure?', a: 'Fleet Commander runs on Cloudflare Workers with no persistent process state — all state is in D1 and R2. If the Fleet Commander Worker cold-starts or restarts, it reloads all registry state from D1 within 2 seconds. However, during that window, relay calls will fail. Workers should implement retry logic with exponential backoff for relay-routed requests.' },
    { q: 'How do I promote a deployment that is stuck waiting at a gate?', a: 'If you have verified the deployment is healthy and want to force-promote past a gate, call POST /fleet/deploy/:id/promote with force: true and a reason string. Force promotions are logged with the user identity and reason for audit purposes. Automatic rollback on subsequent health degradation still applies even after a force promotion.' },
  ],
}

export default function FleetCommanderDocPage() {
  return (
    <>
      <FaqSchema faqs={data.faq} name={data.name} />
      <BreadcrumbSchema items={[
        { name: 'Home', href: '/' },
        { name: 'Docs', href: '/docs' },
        { name: data.name, href: '/docs/fleet-commander' },
      ]} />
      <ProductDoc {...data} />
    </>
  )
}
