'use client'

import ProductDoc from '@/components/ProductDoc'

const data = {
  name: 'Echo Prometheus AI',
  tagline: 'Advanced AI surveillance and threat intelligence platform. Real-time behavioral analysis, anomaly detection, and incident response across every camera feed, access point, and sensor in your environment.',
  accent: '#dc2626',
  productUrl: '/surveillance',
  workerUrl: 'https://echo-prometheus-ai.bmcii1976.workers.dev',
  version: '2.1.0',
  overview: [
    'Echo Prometheus AI is the all-seeing eye of the Echo security ecosystem — a surveillance and threat intelligence engine that processes video feeds, access control events, sensor data, and behavioral telemetry in real time. Unlike conventional VMS (Video Management System) software that simply records footage, Prometheus actively analyzes every frame using computer vision models, correlates events across disparate sources, and constructs a dynamic threat picture that updates continuously. It does not wait for a human to notice something. It notices things humans miss.',
    'The platform is built around three analytical layers. The first is behavioral pattern analysis: Prometheus learns baseline activity patterns for each monitored zone and scores deviations as anomalies with configurable severity thresholds. The second is cross-source correlation: an alert from an access control reader, a simultaneous camera feed showing tailgating, and a badge-not-presented event at a secured door are fused into a single incident timeline rather than three unrelated alerts. The third is automated response: based on configured playbooks, Prometheus can trigger lockdowns, dispatch notifications, log incidents to D1, and generate PDF incident reports without waiting for a human command.',
    'Prometheus integrates natively with the Echo surveillance ecosystem including ShadowGlass feeds, IP camera streams via RTSP/ONVIF, access control systems via REST or Wiegand gateway, facial recognition pipelines, and vehicle plate readers. Multi-site organizations can monitor all locations through a single unified interface with geofenced policy zones that apply different rules to different areas. Every decision made by Prometheus — every anomaly score, every incident classification, every triggered response — is logged with a full audit trail for compliance and forensic review.',
  ],
  gettingStarted: [
    { step: 1, title: 'Connect Your Camera Feeds', desc: 'Navigate to /surveillance/feeds and add your IP cameras via RTSP URLs or ONVIF autodiscovery. For cloud-forwarded streams, use the RTMP ingest endpoint. Prometheus supports H.264, H.265, and MJPEG streams up to 4K resolution.' },
    { step: 2, title: 'Configure Monitoring Zones', desc: 'Define geofenced zones via POST /zones with boundary coordinates, monitoring policy, and operating hours. Each zone can have independent anomaly thresholds, alert escalation rules, and assigned response playbooks.' },
    { step: 3, title: 'Set Baseline Learning Period', desc: 'Allow Prometheus 48-72 hours of uninterrupted observation to establish behavioral baselines for each zone. During this period, the anomaly scorer calibrates to your environment so alerts reflect genuine deviations, not normal variation.' },
    { step: 4, title: 'Configure Alert Routing', desc: 'Define alert destinations in the notification hub: push notifications, SMS via Twilio, email, or webhook to your SIEM. Set severity thresholds per zone — HIGH alerts can trigger automated responses while LOW alerts queue for review.' },
    { step: 5, title: 'Integrate Access Control', desc: 'Connect your access control system via the REST integration endpoint or configure the Wiegand-to-IP bridge. Prometheus correlates badge events with camera feeds within a configurable time window to detect tailgating, piggyback entries, and door-held-open violations.' },
  ],
  features: [
    { title: 'Real-Time Threat Detection', desc: 'Computer vision models analyze every camera feed at up to 30 fps, detecting intrusion events, unattended objects, crowd density spikes, perimeter breaches, and suspicious behavior patterns. Detections fire within 200ms of the triggering event.' },
    { title: 'Behavioral Pattern Analysis', desc: 'Prometheus builds a statistical baseline for each zone by learning normal occupancy patterns, movement flows, dwell times, and activity cycles. Deviations from baseline generate anomaly scores on a 0-100 scale, with configurable alert thresholds per zone.' },
    { title: 'Anomaly Scoring Engine', desc: 'Each detected event receives an anomaly score weighted by deviation magnitude, historical frequency, time-of-day context, and cross-source correlation. Scores decay over time if no follow-up events occur, reducing alert fatigue from one-time anomalies.' },
    { title: 'Multi-Source Incident Fusion', desc: 'Events from cameras, access control readers, motion sensors, door contacts, and alarm panels are fused into unified incident timelines. A tailgating event at a door correlates with the camera feed, badge record, and floor sensor within a 30-second window.' },
    { title: 'Geofenced Monitoring Zones', desc: 'Define unlimited monitoring zones with boundary polygons, operating schedules, and zone-specific policies. Server room zones can have zero-tolerance intrusion rules while lobby zones apply looser thresholds. Zone policies update in real time without feed interruption.' },
    { title: 'Alert Management with Severity Levels', desc: 'Five-tier alert severity system: CRITICAL (immediate automated response), HIGH (immediate human notification), MEDIUM (queued notification), LOW (logged for review), INFO (telemetry only). Each severity tier has configurable response playbooks.' },
    { title: 'Facial Recognition Integration', desc: 'Connect a facial recognition pipeline via the biometric API. Prometheus correlates detected faces against watchlists, known-employee databases, and VIP registries. Matches enrich incident records with identity context. All biometric processing is performed on-premises.' },
    { title: 'Vehicle and Plate Tracking', desc: 'License plate recognition via integrated OCR pipeline. Track vehicle entry/exit times, flag unregistered vehicles in secured lots, correlate plate reads with access events, and generate vehicle activity reports for any time range.' },
    { title: 'Access Control Event Logging', desc: 'Every badge read, door open, door-held-open, door-forced-open, and failed credential event is logged with timestamp, reader ID, credential presented, and correlated camera frame. Access events feed directly into behavioral baselines.' },
    { title: 'Multi-Site Monitoring', desc: 'Monitor unlimited physical sites from a single Prometheus instance. Each site has its own camera inventory, zone definitions, and policy set. Cross-site incident correlation identifies when the same individual or vehicle appears at multiple locations.' },
    { title: 'Automated Incident Reports', desc: 'On incident close or by schedule, Prometheus generates structured PDF reports containing the incident timeline, correlated evidence (camera stills, access logs, sensor readings), anomaly score history, and recommended follow-up actions.' },
    { title: 'Forensic Replay', desc: 'Any incident can be replayed with synchronized multi-camera views, event overlays, and anomaly score timeline. Forensic replay exports are tamper-evident with SHA-256 hash chains and chain-of-custody metadata for legal admissibility.' },
  ],
  apiEndpoints: [
    { method: 'POST', path: '/analyze', desc: 'Submit a frame, video segment, or event payload for real-time analysis. Returns threat assessment with anomaly score, detected events, behavioral flags, and recommended alert level. Supports base64-encoded frame or stream URL reference.', auth: true },
    { method: 'GET', path: '/alerts', desc: 'Retrieve active and recent alerts. Filter by severity, zone, time range, or incident type. Returns alert ID, timestamp, zone, severity, triggering events, anomaly score, and current status. Supports cursor-based pagination.', auth: true },
    { method: 'GET', path: '/incidents', desc: 'List incidents with full timeline data. Each incident record includes correlated event sequence, contributing sources (cameras, access control, sensors), anomaly score trajectory, responder actions, and current disposition.', auth: true },
    { method: 'POST', path: '/zones', desc: 'Create or update a monitoring zone. Accepts boundary polygon, zone name, operating schedule, anomaly threshold, alert routing rules, and response playbook ID. Returns zone_id and computed coverage statistics.', auth: true },
    { method: 'GET', path: '/feeds', desc: 'List all connected camera and sensor feeds with status, resolution, frame rate, last analysis timestamp, and anomaly event count for the last 24 hours. Includes health indicators for each feed connection.', auth: true },
    { method: 'GET', path: '/anomalies', desc: 'Query the anomaly log for a zone or feed. Returns time-series anomaly score data, detected event types, baseline deviation metrics, and correlation with access control events. Supports time range and zone filtering.', auth: true },
    { method: 'POST', path: '/reports', desc: 'Generate an incident report for a specified incident ID or time range. Accepts format (PDF/JSON), evidence inclusion flags, and distribution list. Returns report URL in R2 or streams PDF directly.', auth: true },
    { method: 'GET', path: '/health', desc: 'Returns system health status including active feed count, analysis latency (p50/p95/p99), alert queue depth, incident backlog, and per-zone status summary. No authentication required.', auth: false },
  ],
  userGuide: [
    { id: 'understanding-surveillance', title: 'Understanding the Surveillance Model', content: [
      'Prometheus operates on a continuous analysis loop: ingest → analyze → correlate → score → alert. Every video frame from every connected feed is passed through the detection pipeline. Detected objects (persons, vehicles, packages) are tracked across frames with unique track IDs so the system knows whether the person who entered the lobby 45 minutes ago is the same person still standing near the server room entrance.',
      'The behavioral baseline is the foundation of anomaly detection. Prometheus does not use static rules like "alert if a person is present after 10pm." It learns that in your environment, the cleaning crew arrives at 11pm every weekday, so a person in the lobby at 11pm Monday is NORMAL while the same event at 3am Sunday is ANOMALOUS. The baseline adapts continuously with a configurable learning rate.',
      'Incident fusion is what separates Prometheus from a simple motion-detection system. A person lingering near a door for 8 minutes (camera event), a failed badge read on that door (access control event), and a door-held-open alarm 2 minutes later (sensor event) are fused into a single incident with a complete narrative. Responders see the full picture immediately, not three unrelated alerts.',
    ]},
    { id: 'zone-configuration', title: 'Configuring Monitoring Zones', content: [
      'Zones are the primary policy container in Prometheus. A zone is a geographic boundary (floor plan polygon or GPS bounding box for outdoor areas) with associated rules. You can define as many overlapping zones as needed — a camera feed can belong to multiple zones with different policies applied to different areas of its field of view.',
      'Each zone has an anomaly sensitivity setting (1-10 scale) that scales the alert threshold. Sensitivity 10 means any deviation from baseline triggers a notification. Sensitivity 1 means only extreme deviations (anomaly score > 90) generate alerts. Start at sensitivity 5 and adjust based on the false-positive rate during the first week.',
      'Operating schedules define when a zone is actively monitored vs. in passive logging mode. Server rooms run at maximum sensitivity 24/7. Office areas might drop to passive mode during business hours and activate full monitoring after 7pm. Schedule overrides can be triggered manually or by an external API call (useful for lockdown events).',
    ]},
    { id: 'alert-management', title: 'Managing Alerts and Incidents', content: [
      'Alerts and incidents are distinct objects in Prometheus. An alert is a single detection event with a severity level. An incident is a correlated group of alerts that share a timeline and contribute to a common threat narrative. Prometheus automatically groups alerts into incidents based on temporal proximity, zone overlap, and shared entity tracking IDs.',
      'Alert disposition workflow: new alerts arrive in the ACTIVE queue, get acknowledged by a responder (changes status to ACKNOWLEDGED), receive a response action (RESPONDED), and are closed with a resolution category (FALSE_POSITIVE, RESOLVED, ESCALATED). Each status transition is logged with the responder ID and timestamp.',
      'Alert fatigue is managed through three mechanisms: anomaly score decay (scores drop if the event is not sustained), auto-dismiss rules (low-severity alerts in high-traffic zones during peak hours can be auto-dismissed after 30 minutes with no escalation), and noise suppression periods (during known high-activity events like move-in days, sensitivity can be temporarily reduced).',
    ]},
    { id: 'integrations', title: 'Connecting External Systems', content: [
      'Prometheus exposes a webhook subscription system for outbound integration. Subscribe to event types (alert.created, incident.updated, report.generated) and Prometheus will POST structured JSON payloads to your SIEM, SOC platform, or ticketing system within 2 seconds of the triggering event. Webhooks include retry logic with exponential backoff.',
      'Inbound integration uses the /analyze endpoint for custom sensor data and the /zones endpoint for dynamic zone management. If you have a smart building platform that raises occupancy events, pipe them into Prometheus via /analyze with source_type: "occupancy_sensor" and Prometheus will incorporate them into its correlation engine alongside camera data.',
      'For facial recognition, Prometheus does not perform biometric computation internally — it accepts enriched events from a biometric pipeline. Configure your facial recognition system to POST match results to /events/biometric with track_id, match_confidence, and identity_ref. Prometheus links these to the corresponding camera track and enriches incident records automatically.',
    ]},
    { id: 'forensics-compliance', title: 'Forensics and Compliance', content: [
      'Every incident in Prometheus generates a tamper-evident evidence package: camera frames at key moments (stored in R2), the complete access control event sequence, sensor readings, anomaly score time series, and all alert objects with their full metadata. The package is SHA-256 hashed and the hash is logged to D1 with a timestamp.',
      'Prometheus supports chain-of-custody workflows for evidence exported for legal proceedings. Export packages include a custody log showing every access to the evidence data, the identities of users who accessed it, the export timestamp, and the file hash. These packages meet evidentiary standards in most jurisdictions.',
      'For compliance with GDPR, CCPA, and similar privacy regulations, Prometheus implements configurable data retention policies per zone. Video frames are purged from R2 after the configured retention period (default 30 days, configurable per zone). Access logs retain for 12 months by default. Biometric data retention follows stricter defaults per applicable law.',
    ]},
  ],
  aiCapabilities: [
    { capability: 'Computer Vision Detection', desc: 'YOLO-based object detection models identify persons, vehicles, packages, weapons, and 40+ object classes in real time across all connected feeds. Models are fine-tuned for indoor security environments with high accuracy under low-light and partially-occluded conditions.' },
    { capability: 'Behavioral Baseline Modeling', desc: 'Time-series anomaly detection using LSTM networks trained on each zone\'s historical activity. The model captures daily, weekly, and seasonal patterns so anomaly scores reflect genuine deviations rather than expected variation. Models retrain incrementally with each new day of data.' },
    { capability: 'Cross-Source Event Correlation', desc: 'Graph-based correlation engine links events from disparate sources (cameras, access control, sensors) that share a common entity (person, vehicle), time window, and physical proximity. The correlation graph powers incident fusion and narrative construction.' },
    { capability: 'Threat Classification', desc: 'Detected incidents are classified into threat categories (intrusion, tailgating, loitering, abandoned object, access violation, perimeter breach, crowd event) using a multi-class classifier trained on security industry incident datasets. Classification confidence scores are included in every incident record.' },
    { capability: 'Predictive Escalation', desc: 'Based on incident trajectory — how fast anomaly scores are rising, how many correlated events have occurred in the last 5 minutes — Prometheus predicts whether an incident is likely to escalate and pre-stages responder notifications before the threshold is officially crossed.' },
    { capability: 'Natural Language Incident Narration', desc: 'Every incident is accompanied by an AI-generated narrative in plain English: "At 02:14 UTC, an unrecognized individual approached Door 7 (Server Room B). Two failed badge reads were recorded at 02:14:23 and 02:14:41. The door was held open for 14 seconds at 02:15:02 by an authorized employee. The individual entered. Camera 12 confirmed both persons inside." Narratives are generated from structured event data, not LLM hallucination.' },
  ],
  troubleshooting: [
    { issue: 'Camera feed shows as OFFLINE in /feeds', solution: 'Verify the RTSP URL is accessible from the Prometheus Worker egress IP. Check camera firewall rules. For ONVIF devices, confirm the ONVIF service is enabled and credentials are correct. Re-add the feed via /feeds/reconnect to trigger a fresh connection attempt with extended timeout.' },
    { issue: 'Excessive false-positive alerts flooding the queue', solution: 'Reduce zone sensitivity from the default 5 to 3 or 2. Extend the baseline learning window to 7 days. Enable auto-dismiss for LOW severity alerts during known high-traffic periods. Review your zone boundaries — overlapping camera angles can cause the same person to generate duplicate track IDs.' },
    { issue: 'Incident fusion not grouping related alerts', solution: 'Check that fusion_window_seconds is set appropriately for your environment (default 300s). Ensure all cameras and access control readers in the same physical area are assigned to the same zone. Cross-source correlation requires events to share a zone assignment — events from different zones do not fuse by default.' },
    { issue: 'Anomaly scores are always 0 or always high', solution: 'Score 0 means no baseline exists yet — allow the 48-hour learning period to complete. Consistently high scores during known quiet periods mean the baseline was established during an atypical period (construction, event). Clear the baseline via /zones/:id/baseline/reset and allow a fresh learning period during normal operations.' },
    { issue: 'Incident reports fail to generate', solution: 'Reports require at least one evidence artifact (camera frame or access log entry) to be attached to the incident. Verify R2 storage connectivity via /health. If the incident is older than the video retention window, only access control and sensor logs will be available — reports will still generate but will note that video evidence has expired.' },
  ],
  faq: [
    { q: 'Does Prometheus store raw video footage?', a: 'Prometheus does not store continuous video streams. It stores analysis frames — specific video frames captured at moment of detection events — along with the structured event metadata. Raw RTSP streams remain on your on-premises DVR/NVR. Frame retention in R2 follows the zone retention policy (default 30 days).' },
    { q: 'How does the anomaly score differ from a simple motion detection trigger?', a: 'Motion detection fires any time pixels change. Anomaly scoring fires when pixel change (or any other event type) deviates from the learned baseline for that zone at that time of day. A cleaning crew triggering motion at midnight in an office that has a cleaning crew every midnight gets an anomaly score near zero. An unknown person triggering motion at 3am in a zone that has never had activity at 3am gets a score near 100.' },
    { q: 'Can Prometheus monitor outdoor areas with variable lighting?', a: 'Yes. The detection models include low-light compensation and the baseline learns seasonal and time-of-day lighting patterns. For outdoor areas with high weather variability, enable adaptive_threshold: true on the zone configuration so rain, wind-blown debris, and lighting changes do not generate anomaly spikes.' },
    { q: 'Is facial recognition performed on Cloudflare infrastructure?', a: 'No. Prometheus does not perform biometric computation. It accepts enriched events from your own facial recognition pipeline via the /events/biometric endpoint. This keeps biometric processing on your controlled infrastructure and keeps Prometheus compliant with jurisdictions that restrict cloud biometric processing.' },
    { q: 'How long does baseline learning take?', a: 'A minimum of 48 hours is required for Prometheus to build a functional baseline. 7 days is recommended to capture full weekly patterns including weekday vs. weekend behavior. 30 days is ideal for environments with monthly cycles. The zone will flag its baseline as PROVISIONAL until the minimum threshold is met.' },
    { q: 'What happens to Prometheus during a Worker cold start?', a: 'Prometheus state — zone definitions, active incidents, feed configurations — is persisted in D1 and R2. A cold start or Worker restart reloads state from persistent storage within 2-3 seconds. In-flight analysis frames are retried automatically. No incidents or alerts are lost during Worker lifecycle events.' },
  ],
}

export default function PrometheusAIDocPage() {
  return <ProductDoc {...data} />
}
