'use client'

import ProductDoc, { ProductDocProps } from '@/components/ProductDoc'

const data: ProductDocProps = {
  name: 'Echo Recruiting',
  tagline: 'Full-cycle ATS with AI resume screening, customizable pipelines, scorecards, offer management, and talent pools.',
  accent: '#0891b2',
  productUrl: '/recruiting',
  workerUrl: 'https://echo-recruiting.bmcii1976.workers.dev',
  version: '1.0.0',

  overview: [
    'Echo Recruiting is a full applicant tracking system built to manage every stage of the hiring process — from job posting and public careers page to offer letter and onboarding handoff. With a public careers page at your branded URL, fully customizable pipeline stages per job, and an AI resume screening engine that scores candidates 0–100 against job requirements, Echo Recruiting gives hiring teams the speed and intelligence to hire the best people faster.',
    'The AI screening layer is powered by the Echo Engine Runtime — candidates are scored using a trained model that analyzes resume content against the job description, required skills, and experience level. Unlike keyword matching, the AI understands semantic equivalence (e.g., "Python" and "machine learning" connect) and assesses the depth of experience described, not just its presence. Hiring managers see a ranked candidate list with AI reasoning for each score, cutting resume review time by up to 80%.',
    'Interview scorecards standardize evaluation across your hiring team, eliminating bias from unstructured feedback. Offer management with configurable approval chains ensures compensation decisions are reviewed before going out. Talent pools let you bank qualified candidates for future roles. Pipeline insights give you live metrics on time-to-fill, source effectiveness, and stage conversion rates — the data you need to continuously improve your hiring process.',
  ],

  gettingStarted: [
    { step: 1, title: 'Configure Your Careers Page', desc: 'Set up your public careers page in Settings > Careers Page. Add your company logo, brand colors, company description, and benefits highlights. Your careers page URL is careers.echo-ept.com/your-company-slug or can be configured as a custom domain (careers.yourcompany.com on Enterprise). All open jobs with public visibility post here automatically.' },
    { step: 2, title: 'Create Your First Job', desc: 'Navigate to Jobs > New Job. Fill in job title, department, location (on-site/remote/hybrid), employment type (full-time/part-time/contract), compensation range, and a detailed job description. The job description is used by the AI screening engine, so the more specific you are about required skills and experience, the more accurate the candidate scoring will be.' },
    { step: 3, title: 'Customize the Pipeline', desc: 'Each job gets its own pipeline — a sequence of stages candidates move through from application to offer. Start from a template (Technical, Sales, Executive, Customer Service) and customize stage names, order, and properties. Configure which stages trigger automatic emails to candidates and which require interview scheduling.' },
    { step: 4, title: 'Set Up Interview Scorecards', desc: 'Create scorecard templates for each interview stage — define the competencies being evaluated, the rating scale (1–5 or 1–10), and optional rubric descriptions for each score level. Assign scorecards to specific stages so interviewers always know what to evaluate. Scorecards are filled out in Echo Recruiting immediately after each interview.' },
    { step: 5, title: 'Invite Your Hiring Team', desc: 'Add team members as recruiters, hiring managers, or interviewers. Assign each team member to specific jobs. Configure notification preferences — who gets notified for new applications, scorecard submissions, and stage changes. Set up interview panels for stages that require multiple interviewers.' },
    { step: 6, title: 'Start Sourcing and Reviewing', desc: 'Share your job posting URL, post to job boards via the one-click integrations, or import candidates from CSV/LinkedIn. As applications come in, the AI screen runs automatically and ranks candidates in your pipeline. Review AI-scored candidates, schedule interviews for top prospects, and move them through your pipeline to offer.' },
  ],

  features: [
    { title: 'Public Careers Pages', desc: 'Branded public careers page at your configured slug showing all open jobs with descriptions, location, and compensation ranges. Each job has a dedicated application page with a customizable application form. SEO-optimized with structured data markup for Google Jobs indexing. Mobile-optimized for candidates applying from any device.' },
    { title: 'Customizable Pipeline Stages', desc: 'Every job has its own independently configurable pipeline with as many stages as your hiring process requires. Common configurations include: Application → Phone Screen → Technical Assessment → First Interview → Final Interview → Reference Check → Offer. Stages can have required fields, automatic emails, and SLA timers that alert when candidates sit too long in a stage.' },
    { title: 'AI Resume Screening (0-100 Scoring)', desc: 'The AI screening engine analyzes each resume against the job description using the Echo Engine Runtime. Scoring considers skills match (both explicit and semantically inferred), experience level (years and seniority signals), education alignment, career trajectory, and domain-specific expertise depth. Each score comes with AI reasoning — a short explanation of what factors drove the score up or down.' },
    { title: 'Interview Scheduling', desc: 'Schedule interviews from inside the candidate record. Generate shareable scheduling links (powered by Echo Calendar integration) or manually book interviews. Automatically send interview invitations with location, format (video/phone/in-person), and preparation materials. Calendar events sync to interviewer calendars. Send automatic interview confirmation and reminder emails to candidates.' },
    { title: 'Interview Scorecards', desc: 'Standardized interview evaluation forms tied to specific pipeline stages. Define competencies (problem-solving, technical depth, communication, culture add), rating scale, and rubric descriptions. Interviewers fill out scorecards directly in Echo Recruiting. Score aggregation shows consensus and outlier ratings across the panel. Scorecard history is attached to the candidate record permanently.' },
    { title: 'Offer Management', desc: 'Generate offer letters from configurable templates with variable substitution: candidate name, role, compensation, start date, reporting manager, benefits summary. Configure approval workflows — offers above a compensation threshold require additional approvals before sending. Track offer status: draft, pending approval, sent, accepted, declined, or expired. Digital acceptance is supported.' },
    { title: 'Talent Pools', desc: 'Bank qualified candidates who are not right for the current role but should be considered for future openings. Assign candidates to named talent pools (e.g., "Senior Engineers," "Enterprise Sales," "Marketing Managers") with notes and a quality score. When a new role opens, search talent pools first before sourcing externally. Email talent pool candidates directly from Echo Recruiting for new opportunity outreach.' },
    { title: 'Hiring Teams', desc: 'Assign structured roles to each job: recruiter (owns the process), hiring manager (makes the final call), interviewers (conduct specific stages). Each role has different notification settings and access levels. Hiring managers see candidate scores and advance summaries. Interviewers only see the candidates assigned to their stage. Collaboration notes are shared across the team.' },
    { title: 'Pipeline Insights', desc: 'Real-time analytics per job and across your hiring operation: applications per job, source effectiveness (which job boards drive the most hires), stage conversion rates (what percentage of candidates advance from each stage), time-in-stage averages, total time-to-fill, offer acceptance rate, and diversity funnel metrics. Export all reports to CSV for deeper analysis.' },
    { title: 'Application Forms', desc: 'Customizable application forms per job with standard fields (resume upload, name, email, phone, LinkedIn URL) plus custom questions (open text, select, checkbox, file upload). Form builder supports conditional logic — show a question only if a previous answer meets a condition. Built-in spam filtering rejects form spam before it reaches the recruiter queue.' },
    { title: 'Candidate Communications', desc: 'Send emails to candidates from within Echo Recruiting using customizable templates. Automated stage-transition emails notify candidates when they advance or are declined. Personal outreach emails go directly from the recruiter\'s configured email address. All communications are logged in the candidate activity timeline. Mass email to talent pools or filtered candidate lists supported.' },
    { title: 'CSV and LinkedIn Import', desc: 'Bulk import candidates via CSV with field mapping for resume data. LinkedIn Recruiter export files are supported directly. Paste a LinkedIn profile URL to create a candidate record via browser extension (Enterprise). Each imported candidate goes through the same AI screening process against the assigned job\'s description. Duplicate detection prevents the same candidate from appearing twice.' },
  ],

  apiEndpoints: [
    { method: 'GET', path: '/api/jobs', desc: 'List all jobs with status (draft/open/closed/filled), department, location, application count, and pipeline stage counts. Filter by status, department, and location.', auth: true },
    { method: 'POST', path: '/api/jobs', desc: 'Create a new job posting. Provide title, department, location, employment type, compensation, description, requirements, and pipeline template ID.', auth: true },
    { method: 'GET', path: '/careers/:slug', desc: 'Public careers page for the company. Lists all open jobs with titles, locations, and apply links. SEO-optimized HTML. No auth required.', auth: false },
    { method: 'POST', path: '/careers/:slug/:job-id/apply', desc: 'Public job application submission. Accepts multipart/form-data with resume file and all application form fields. Returns application confirmation. No auth required.', auth: false },
    { method: 'GET', path: '/api/candidates', desc: 'List all candidates across all jobs with AI score, current stage, source, and application date. Filter by job, stage, score range, and source.', auth: true },
    { method: 'GET', path: '/api/candidates/:id', desc: 'Retrieve full candidate profile: resume text, AI score with reasoning, stage history, interview scorecards, communications log, and notes.', auth: true },
    { method: 'POST', path: '/api/candidates/:id/move', desc: 'Move a candidate to a specific pipeline stage. Triggers stage-transition email if configured. Logs the move with the acting user and timestamp.', auth: true },
    { method: 'POST', path: '/api/candidates/:id/scorecard', desc: 'Submit an interview scorecard for a candidate. Provide stage_id, competency ratings array, summary notes, and recommendation (advance/decline/hold).', auth: true },
    { method: 'POST', path: '/api/candidates/:id/offer', desc: 'Create an offer for a candidate. Provide offer template ID, variable values, and optional approval_required flag. Returns offer record with status and sharing link.', auth: true },
    { method: 'GET', path: '/api/analytics/pipeline', desc: 'Pipeline analytics across all jobs: stage conversion rates, time-in-stage averages, source effectiveness, offer acceptance rate, and time-to-fill by department.', auth: true },
  ],

  userGuide: [
    {
      id: 'pipeline-configuration',
      title: 'Designing Your Hiring Pipeline',
      content: [
        'A well-designed pipeline is the backbone of an efficient recruiting operation. Echo Recruiting ships with four pipeline templates — Technical (adds coding assessment stage), Sales (adds role play stage), Executive (adds additional interview rounds), and General (basic 5-stage process) — which you can use as starting points or build from scratch. The right pipeline depends on the role: over-engineering a pipeline for junior roles slows hiring and frustrates candidates; too few stages for senior roles risks bad hires.',
        'Each pipeline stage has configurable properties. Stage type determines what actions are available: "screening" stages show the AI score prominently, "interview" stages link to scheduling and scorecards, "assessment" stages can include a test link and submission deadline, and "offer" stages trigger the offer management workflow. Stage SLA settings alert the hiring team when a candidate has been in a stage longer than acceptable — for competitive roles, this prevents top candidates from going cold while awaiting decisions.',
        'Stage-transition emails maintain candidate communication automatically. Configure email templates for each stage: an "Application Received" email when they apply, an "Advancing to Interview" email with scheduling instructions when they pass screening, and a professional decline email for candidates who are not moving forward. All emails use your configured company name and recruiter identity. Candidates who receive timely, professional communication are more likely to accept offers and refer others.',
      ],
    },
    {
      id: 'ai-screening',
      title: 'Understanding AI Resume Screening',
      content: [
        'The AI resume screening engine processes every application automatically within 30–60 seconds of submission. The score (0–100) reflects how well the candidate\'s background matches the job requirements as described in the job posting. This is why a detailed, specific job description produces significantly more accurate scores — vague descriptions give the AI less signal to work with. Include specific technologies, years of experience, domain keywords, and concrete responsibility descriptions in your job postings for best results.',
        'Each AI score comes with a reasoning summary viewable by expanding the candidate card. The reasoning explains the top positive signals (what impressed the AI) and the top negative signals (what was missing or misaligned). Common positive signals include direct skill matches, relevant domain experience, appropriate seniority level, and progression trajectory. Common negative signals include skill gaps in required areas, significant over- or under-qualification, and mismatched domain background.',
        'AI scores are a starting point, not a final decision. The AI is calibrated to have high recall (minimizing false negatives — qualified candidates who score low) at a slight cost to precision, meaning a small percentage of low-scoring candidates may still be worth reviewing. Use the score as a prioritization tool: review the top 20% of scored candidates first, then work down the list based on your time. Hire data feeds back into the model over time, improving accuracy for your specific job types as the system learns what "good" looks like at your company.',
      ],
    },
    {
      id: 'interview-process',
      title: 'Running Structured Interviews with Scorecards',
      content: [
        'Structured interviews — where all candidates for a role are evaluated on the same competencies by the same interviewers using the same rating criteria — produce significantly better hiring outcomes than unstructured "have a chat" interviews. Echo Recruiting\'s scorecard system makes structured interviewing easy to execute consistently. Define your competency framework once per role type, link scorecards to specific pipeline stages, and every interviewer works from the same template.',
        'After each interview, the interviewer opens the candidate record in Echo Recruiting and fills out the assigned scorecard. Ratings are entered for each competency (e.g., Problem-Solving: 4/5), with optional notes per competency and an overall summary. The recommendation field captures a clear hire/no-hire/strong-hire signal. Scorecards are submitted immediately after the interview before the next candidate is evaluated, preventing recall bias from conflating candidates.',
        'The aggregate scorecard view for any candidate shows all interviewer ratings side by side, highlights where interviewers diverged significantly (an indicator of either a genuine borderline candidate or evaluation criteria misalignment), and calculates an overall panel recommendation. Use the debrief meeting workflow to bring the panel together asynchronously in the comments thread or live in the hiring team Slack channel to make the final decision with full data in view.',
      ],
    },
    {
      id: 'offer-management',
      title: 'Managing Offers and Approvals',
      content: [
        'When a candidate is ready for an offer, navigate to the Offer tab on their candidate record and click "Create Offer." Select an offer letter template, fill in the variable values (compensation, start date, equity, signing bonus if applicable), and review the generated offer letter before routing for approval. Offer letter templates are managed in Settings > Offer Templates and support all standard offer letter components including compensation, benefits summary, and confidentiality language.',
        'Approval workflows ensure compensation decisions are reviewed before they go out. Configure approval tiers in Settings > Offer Approvals: for example, offers with base salary under $80K route to the hiring manager only; offers between $80K–$150K require hiring manager and HR director approval; offers above $150K require hiring manager, HR director, and CFO. Approvers are notified by email and in-app and can approve, request changes, or reject with comments directly from the notification.',
        'Once approved, share the offer with the candidate via a secure link that displays the formatted offer letter in their browser. The candidate can accept with a digital signature, decline (with an optional decline reason for your data), or request a conversation before deciding. Acceptance is recorded with the candidate\'s IP address and timestamp. The accepted offer PDF is stored in the candidate record permanently and triggers the onboarding handoff workflow if configured.',
      ],
    },
    {
      id: 'talent-pools-sourcing',
      title: 'Building Talent Pools and Sourcing Strategy',
      content: [
        'Talent pools convert your recruiting effort from a transactional cost center into a strategic asset. Every candidate who reaches the interview stage but doesn\'t get the current role is a potential future hire — they\'ve already passed your bar. Add them to the appropriate talent pool with notes on their strengths, the role they interviewed for, why they weren\'t selected now (timing, compensation, role fit), and a re-engagement date for when to reach out.',
        'When a new role opens, the first step before posting externally should be a talent pool search. Navigate to Talent Pools, filter by relevant skills, experience level, and last-contact date, and review the candidates already in your pipeline. Reaching out to a previous finalist with a new relevant role has a significantly higher response and acceptance rate than cold sourcing — these candidates already know your company and have demonstrated interest.',
        'Source tracking is built into every application. When candidates apply from different job boards (LinkedIn, Indeed, ZipRecruiter), referrals, or your careers page directly, the source is captured automatically. The source effectiveness report in Pipeline Insights shows cost-per-hire, time-to-hire, offer acceptance rate, and 90-day retention rate by source. This data is essential for optimizing your recruiting budget — cutting spend on sources with poor quality-adjusted ROI and doubling down on high performers.',
      ],
    },
  ],

  aiCapabilities: [
    { capability: 'AI Resume Screening via Engine Runtime', desc: 'The primary AI capability — every submitted resume is scored 0–100 against the job description using the Echo Engine Runtime\'s trained language model. The scoring model understands semantic relationships between skills (not just exact keyword matches), assesses experience depth from contextual signals, evaluates career trajectory and progression, and computes an overall qualification fit score with a human-readable reasoning summary.' },
    { capability: 'Candidate Quality Prediction', desc: 'Beyond screening score, the AI predicts likelihood of offer acceptance, first-year retention, and performance quartile based on signals in the application and interview data. These predictions are surfaced as confidence indicators on the candidate profile, helping hiring managers prioritize candidates who are not only qualified but likely to join and succeed in the role long-term.' },
    { capability: 'Interview Question Generation', desc: 'Given a job description and the specific competencies on a scorecard, the AI generates a tailored question bank for each interview stage. Questions are competency-specific, open-ended, and include follow-up probes and what a strong vs. weak answer looks like. Reduces the prep time for new interviewers and ensures consistent quality of questions across the panel.' },
    { capability: 'Pipeline Bottleneck Analysis', desc: 'Continuously monitors stage conversion rates and time-in-stage across all active jobs to identify bottlenecks in your hiring process. Flags stages where conversion drops sharply (indicating an evaluation criteria problem or interview experience issue), stages where candidates sit too long (indicating interviewer scheduling friction), and jobs where offer acceptance rate is below benchmark (indicating a compensation or process problem).' },
    { capability: 'Compensation Benchmarking', desc: 'Analyzes offer data, accepted vs. declined reasons, and market benchmarks to provide compensation recommendations for new roles. Flags offers at risk of decline based on the gap between offered compensation and candidate expectations signals detected during the interview process. Recommends compensation range adjustments when rejection patterns suggest the range is below market for the role and location.' },
    { capability: 'Talent Pool Match Recommendations', desc: 'When a new job opens, the AI automatically searches your talent pools and surfaced the top matching candidates based on semantic skill matching, experience alignment, and time since last contact. Generates a personalized outreach message draft for each recommended talent pool candidate, reducing the time to first contact from days to minutes.' },
  ],

  troubleshooting: [
    { issue: 'AI screening scores seem inaccurate or all candidates scoring similarly', solution: 'AI scoring accuracy is directly proportional to job description quality. If your job description is very short, vague, or uses generic language, the model has little signal to differentiate candidates. Expand your job description to at least 400 words, including specific required skills (list individual technologies, tools, and methodologies), concrete responsibilities (not just "manage projects"), experience level signals (years in role, scale of prior work), and domain-specific keywords. Re-run screening on the existing candidate pool from the job\'s Screening tab after updating the description.' },
    { issue: 'Application form not appearing on the public careers page', solution: 'Verify the job status is set to "Open" and the visibility is set to "Public" in job settings — draft or internal jobs do not appear on the public careers page. If the job shows on the careers page but the Apply button doesn\'t open the form, check that the application form has at least one required field configured and has been published (not left in draft state). Clear your browser cache as careers pages are CDN-cached with a 5-minute TTL.' },
    { issue: 'Scorecard submissions not visible to hiring manager', solution: 'Scorecard visibility is role-based. Ensure the hiring manager\'s account has the "Hiring Manager" role on the specific job (not just a global account role). Interviewers can only see their own submitted scorecards by default — this is intentional to prevent score anchoring. Hiring managers see all scorecards once submitted. If a scorecard is still not visible after submission, verify the scorecard was submitted (not just saved as draft) — the status should show "Submitted" on the Interviews tab.' },
    { issue: 'Candidate not receiving application confirmation email', solution: 'Verify the candidate\'s email address is correctly captured in their record — typos during application are common. Check your email delivery settings to confirm the application confirmation email template is enabled for the relevant pipeline\'s first stage. If the email template is enabled but not being sent, check Settings > Email Delivery for any bounce or block on the candidate\'s email domain. Manually resend the confirmation from the candidate\'s Communications tab if needed.' },
    { issue: 'Offer approval workflow not routing to the correct approvers', solution: 'Verify the offer approval tier in Settings > Offer Approvals covers the compensation range of the offer being created. Check that each approver in the chain has an active Echo Recruiting account with the correct email address configured. If an approver is out of office, configure a delegation rule in their account settings so approvals route to their backup. Approval routing issues can also occur if the offer template uses a compensation variable that doesn\'t parse to a number — ensure compensation fields are numeric, not formatted with currency symbols.' },
  ],

  faq: [
    { q: 'How does the AI resume screening score candidates?', a: 'The AI screening engine analyzes resume content against the job description using the Echo Engine Runtime\'s language model. It evaluates skills match (explicit and semantically inferred — it understands that "React" implies "JavaScript"), experience depth (context signals around each skill, not just presence), career progression and trajectory, education alignment, and domain expertise. Scores range from 0–100 and each score includes a brief reasoning summary explaining the top positive and negative factors. The model improves accuracy over time as you provide feedback by hiring candidates and declining others.' },
    { q: 'Can we use Echo Recruiting for high-volume hourly hiring?', a: 'Yes. Echo Recruiting supports high-volume hiring workflows with bulk application processing, automated screening thresholds (auto-advance candidates above score X, auto-decline below score Y), bulk email communications, and express pipeline templates with fewer stages. For very high volume (1,000+ applications per month per role), enable the "auto-decline below threshold" feature in job settings to automatically send decline notifications to candidates below your minimum score threshold, significantly reducing manual review workload.' },
    { q: 'How many custom pipeline stages can we create?', a: 'There is no limit on pipeline stages per job. You can create as many stages as your hiring process requires. Most roles use 5–8 stages; complex executive or technical searches may use 10–12. Each stage can have a unique name, email templates, SLA timer, and scorecard assignment. Pipeline templates can be saved and reused across similar job types to reduce setup time for new postings.' },
    { q: 'Does Echo Recruiting integrate with HRIS or payroll systems?', a: 'Echo Recruiting integrates with BambooHR, Workday, ADP, and Rippling via webhook-based onboarding triggers — when an offer is accepted, candidate data can be pushed to your HRIS to initiate onboarding workflows. For systems not natively supported, the REST API and webhook events allow custom integration with any HRIS or payroll platform. Candidate export to CSV is also available for manual data transfer workflows.' },
    { q: 'How are job boards connected?', a: 'Echo Recruiting offers one-click posting to LinkedIn Jobs, Indeed, ZipRecruiter, and Glassdoor for Pro and Enterprise plans. Each integration uses the respective platform\'s employer API for posting and receives application data back into Echo Recruiting automatically — no manual import needed. Job board billing is handled directly by each platform (Echo Recruiting does not mark up job board costs). Free plans support manual job board posting with a tracked application link for source attribution.' },
    { q: 'Is candidate data handled compliantly for GDPR and EEOC?', a: 'Echo Recruiting is designed for GDPR and EEOC compliance. Candidate data is processed only for recruitment purposes per the privacy notice shown during application. Data retention policies are configurable — set automatic deletion of unsuccessful candidate records after your defined retention period (commonly 1 year in the EU). EEOC voluntary disclosure fields (gender, race/ethnicity, veteran status, disability status) are collected on a separate, anonymous form unlinked from the reviewable application to prevent screening bias. GDPR data access and deletion requests can be processed from Settings > Data Privacy.' },
  ],
}

export default function EchoRecruitingDocsPage() {
  return <ProductDoc {...data} />
}
