'use client'

import ProductDoc from '@/components/ProductDoc'

const data = {
  name: 'Echo SDK Gateway',
  tagline: 'The single entry point for the entire Echo ecosystem — unified auth, intelligent routing, rate limiting, and client SDKs for every Worker and service in the fleet.',
  accent: '#6366f1',
  productUrl: '/sdk',
  workerUrl: 'https://echo-sdk-gateway.bmcii1976.workers.dev',
  version: '3.0.0',
  overview: [
    'The Echo SDK Gateway is the unified API front door for the entire Echo ecosystem. Rather than exposing dozens of individual Worker URLs to client applications, every external request enters through the Gateway at echo-sdk-gateway.bmcii1976.workers.dev. The Gateway handles API key authentication, per-key rate limiting, request routing to the correct backend Worker via service bindings, response normalization into a consistent envelope format, and structured request logging. From the client perspective, there is exactly one URL, one authentication scheme, and one response format — regardless of which of the 200+ backend Workers handles the request.',
    'Routing logic is defined in a versioned routing table stored in KV (workers_registry.json). Each route entry maps a path prefix to a Worker service binding, an auth requirement level (public, api_key, bearer_token, internal), a rate limit tier, and an optional request transformer. When a new Worker is deployed and registered, its routes are added to the registry and become available through the Gateway immediately — no Gateway redeploy required. The v1 API prefix ensures backward compatibility: existing client integrations continue working as the routing table evolves.',
    'The Gateway ships with official client SDKs for TypeScript and Python. Both SDKs wrap every Gateway endpoint with typed methods, automatic retry with exponential backoff, response deserialization, and streaming support for chat and query endpoints. The TypeScript SDK is published as @echo-prime/sdk and is used throughout the echo-ept.com frontend. The Python SDK is available via pip and is used in all backend automation scripts and CC session tooling. An OpenAPI 3.1 specification is served live at /v1/docs for any SDK or client generator.',
  ],
  gettingStarted: [
    { step: 1, title: 'Get Your API Key', desc: 'Navigate to echo-ept.com/sdk to access the SDK dashboard. Create an API key with the permission scopes your application needs (read, write, engines, chat, knowledge). Keys are displayed once at creation — store them in your vault immediately.' },
    { step: 2, title: 'Install the SDK', desc: 'For TypeScript/JavaScript: npm install @echo-prime/sdk. For Python: pip install echo-prime-sdk. Both SDKs auto-configure against the Gateway URL and handle all auth headers, retries, and response parsing.' },
    { step: 3, title: 'Make Your First Request', desc: 'TypeScript: const echo = new EchoClient({ apiKey }); const engines = await echo.engines.list(). Python: client = EchoClient(api_key=key); engines = client.engines.list(). Both return fully typed response objects matching the OpenAPI spec.' },
    { step: 4, title: 'Explore the Endpoint Catalog', desc: 'GET /v1/docs returns the live OpenAPI 3.1 specification with every available endpoint, request schemas, response models, and example payloads. GET /v1/status shows real-time health of all registered backend Workers the Gateway routes to.' },
    { step: 5, title: 'Register Your Worker (for internal builders)', desc: 'When deploying a new Worker that needs Gateway exposure, POST to /v1/registry with the route prefix, Worker binding name, auth level, and rate limit tier. The route becomes active on the next Gateway config refresh (within 60 seconds).' },
  ],
  features: [
    { title: 'Unified API Endpoint', desc: 'All Echo services accessible at a single domain. Clients configure one base URL and one API key for access to Engine Runtime, Knowledge Forge, Shared Brain, Chat, Landman Pipeline, Arcanum, and every other registered service.' },
    { title: 'Intelligent Worker Routing', desc: 'Path-based routing to 200+ backend Workers via Cloudflare service bindings. Routing table stored in KV and hot-reloaded every 60 seconds — new Workers become routable without a Gateway redeploy.' },
    { title: 'API Key Authentication', desc: 'Per-key permission scopes (read, write, engines, chat, knowledge, admin). Keys are hashed with BLAKE3 before storage. Invalid or revoked keys return 401 in <1ms. Keys can be scoped to specific path prefixes for least-privilege integrations.' },
    { title: 'Rate Limiting', desc: 'KV-backed rate limiting with four tiers: Free (100 req/hour), Standard (1,000 req/hour), Professional (10,000 req/hour), Enterprise (unlimited). Rate limit headers (X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset) included on every response.' },
    { title: 'Request & Response Logging', desc: 'Every request logged to D1 with: timestamp, api_key_hash, route, backend_worker, latency_ms, status_code, and request_id. Logs are queryable via GET /v1/logs for debugging and usage auditing. PII is never logged.' },
    { title: 'TypeScript SDK', desc: 'Full-featured TypeScript SDK (@echo-prime/sdk) with typed clients for every registered service, streaming support for chat endpoints, automatic retry with jitter, request deduplication, and response caching for read-only endpoints.' },
    { title: 'Python SDK', desc: 'pip-installable Python SDK (echo-prime-sdk) with sync and async clients, Pydantic response models, streaming generator support, and a CLI entry point (echo-prime query --engine TX01 "your question") for interactive use from shell scripts.' },
    { title: 'Versioned API', desc: 'v1 prefix on all routes with semantic versioning guarantees. Breaking changes always increment the major version and old versions remain live for 12 months. Version negotiation via Accept header is supported for gradual migration.' },
    { title: 'OpenAPI Specification', desc: 'Live OpenAPI 3.1 spec at /v1/docs auto-generated from the routing table and each Worker\'s own schema definitions. Compatible with all major API client generators including openapi-typescript, openapi-python-client, and Postman collections.' },
    { title: 'Health Aggregation', desc: 'GET /v1/health pings all registered backend Workers concurrently and returns a unified health report in <500ms. Each Worker\'s health status, latency, and last-checked timestamp are included. Unhealthy Workers are flagged for ops alerting.' },
    { title: 'Request Transformation', desc: 'Per-route request transformers can inject headers, rewrite paths, or modify payloads before forwarding to the backend Worker. Useful for adding internal auth tokens, normalizing legacy request formats, or fanning out a single request to multiple backends.' },
    { title: 'CORS and Preflight Handling', desc: 'Fully configured CORS for the echo-ept.com domain with support for custom allowed origins per API key. Preflight OPTIONS requests are handled at the Gateway layer without touching backend Workers, reducing latency for browser-based clients.' },
  ],
  apiEndpoints: [
    { method: 'GET', path: '/v1/engines', desc: 'List all Intelligence Engines available through the Gateway. Proxied to echo-engine-runtime. Supports pagination, domain filter, and tier filter. Returns engine_id, name, domain, doctrine_count, pricing_tier, and status.', auth: false },
    { method: 'POST', path: '/v1/query', desc: 'Query an Intelligence Engine with natural language. Body: { query, engine_id?, domain?, confidence_min?, options }. Proxied to echo-engine-runtime. Returns grounded answer with doctrine citations and confidence stratification.', auth: true },
    { method: 'GET', path: '/v1/knowledge', desc: 'Search the Knowledge Forge index. Query params: q (search text), domain, limit, offset. Returns ranked knowledge documents with excerpts, source metadata, and relevance scores. Proxied to echo-knowledge-forge.', auth: false },
    { method: 'POST', path: '/v1/chat', desc: 'Send a chat message to Echo Chat (Sentinel AI, Trinity, Cortex, Bree personalities). Body: { message, session_id?, personality?, context? }. Supports Server-Sent Events streaming via Accept: text/event-stream header.', auth: true },
    { method: 'GET', path: '/v1/health', desc: 'Aggregate health check across all registered backend Workers. Returns per-worker health status, latency_ms, last_checked, and overall system status. Runs concurrent pings to all Workers — completes in <500ms.', auth: false },
    { method: 'GET', path: '/v1/status', desc: 'Detailed system status including routing table version, total registered Workers, requests served in the last hour, p50/p95/p99 latency, and per-Worker request distribution. For dashboards and monitoring integrations.', auth: false },
    { method: 'GET', path: '/v1/docs', desc: 'Live OpenAPI 3.1 specification auto-generated from the current routing table and Worker schema definitions. Returns JSON by default; pass Accept: text/html for the Swagger UI interactive explorer.', auth: false },
    { method: 'POST', path: '/v1/registry', desc: 'Register a new route in the Gateway routing table. Body: { path_prefix, worker_binding, auth_level, rate_limit_tier, description }. Requires admin API key scope. Changes are hot-reloaded within 60 seconds.', auth: true },
  ],
  userGuide: [
    { id: 'authentication', title: 'Authentication and API Keys', content: [
      'Every request to a protected Gateway endpoint must include the header X-Echo-API-Key: <your_key>. Keys are created in the SDK dashboard at echo-ept.com/sdk with one or more permission scopes: read (GET endpoints), write (POST/PUT/DELETE), engines (engine query access), chat (chat session access), knowledge (knowledge base access), admin (registry modification and log access).',
      'Keys are hashed with BLAKE3 before storage — the plaintext is shown exactly once at creation time and cannot be retrieved afterward. If a key is lost, revoke it and create a new one. Key revocation takes effect within 60 seconds (one KV cache refresh cycle). Revoked keys receive 401 responses immediately after revocation propagates.',
      'For server-to-server integrations, use API keys with tightly scoped permissions. For frontend applications (React, Vue, mobile), use short-lived bearer tokens generated by your backend from the master API key. The Gateway supports both auth methods on all protected endpoints. Never embed API keys directly in frontend code.',
    ]},
    { id: 'routing-table', title: 'How Routing Works', content: [
      'The Gateway\'s routing table maps URL path prefixes to backend Worker service bindings. When a request arrives, the Gateway performs a longest-prefix match against the routing table and forwards the request to the matched Worker via a Cloudflare service binding (direct Worker-to-Worker communication, zero network hop, no public URL exposure).',
      'Path matching is hierarchical: /v1/query routes to echo-engine-runtime, /v1/chat routes to echo-chat, /v1/knowledge routes to echo-knowledge-forge, and so on. Custom routes added via the registry API follow the same matching logic. The routing table is stored in Cloudflare KV and cached in memory for 60 seconds, allowing hot reloads without Worker restarts.',
      'Routing decisions are logged with the matched prefix, target Worker, and routing latency (typically <0.5ms). This telemetry is available in GET /v1/logs filtered by request_id. If a request is reaching the wrong backend, the routing logs are the first place to check — they show exactly which prefix was matched and which Worker received the forwarded request.',
    ]},
    { id: 'rate-limiting', title: 'Rate Limiting', content: [
      'Rate limits are enforced at the API key level using a sliding window algorithm implemented in Cloudflare KV. The four tiers are: Free (100 requests/hour), Standard (1,000 requests/hour), Professional (10,000 requests/hour), and Enterprise (configurable, default unlimited). Tier assignment happens at key creation time and can be changed by an admin.',
      'Every response includes three rate limit headers: X-RateLimit-Limit (your tier\'s hourly ceiling), X-RateLimit-Remaining (requests left in the current window), and X-RateLimit-Reset (Unix timestamp when the window resets). When the limit is exceeded, the Gateway returns 429 Too Many Requests with a Retry-After header indicating how many seconds to wait.',
      'High-frequency batch workloads should monitor X-RateLimit-Remaining and implement client-side throttling before hitting the limit. The official SDKs include built-in rate limit awareness — they read the headers and automatically backoff when remaining drops below 10% of the limit. For sustained high-volume use cases, request a Professional or Enterprise key from the SDK dashboard.',
    ]},
    { id: 'typescript-sdk', title: 'TypeScript SDK Usage', content: [
      'Install with npm install @echo-prime/sdk. Initialize the client with your API key: const echo = new EchoClient({ apiKey: process.env.ECHO_API_KEY }). The client is safe to use as a singleton across your application. In Next.js server components and API routes, initialize once at module level and reuse across requests.',
      'The SDK provides typed clients for each Gateway service: echo.engines (engine catalog and queries), echo.chat (chat sessions and streaming), echo.knowledge (knowledge search and ingestion), echo.landman (title investigation), and echo.health (system status). Each client method accepts a typed request object and returns a typed response, with TypeScript generics for discriminated union response types.',
      'Streaming is supported on echo.chat.stream() and echo.engines.queryStream(). Both return AsyncIterables of typed chunk objects. Use for...await...of to consume the stream: for await (const chunk of echo.chat.stream({ message: "..." })) { process(chunk.delta) }. Streaming responses are fully typed and include role, delta, finish_reason, and usage fields.',
    ]},
    { id: 'python-sdk', title: 'Python SDK Usage', content: [
      'Install with pip install echo-prime-sdk. The package provides both synchronous and async clients. Sync: from echo_prime import EchoClient; client = EchoClient(api_key=os.environ["ECHO_API_KEY"]). Async: from echo_prime.async_client import AsyncEchoClient. All async methods are awaitable and compatible with asyncio, Trio, and AnyIO.',
      'Response models are Pydantic v2 BaseModel subclasses, providing attribute access, .model_dump() serialization, and JSON schema generation. All optional fields default to None and are annotated accordingly. The CLI entry point (echo-prime) installed by the package accepts subcommands: echo-prime query, echo-prime chat, echo-prime knowledge, echo-prime health — all reading the ECHO_API_KEY environment variable.',
      'For high-throughput batch processing, use the async client with asyncio.gather() to parallelize requests. The client\'s internal httpx session is shared across requests and handles connection pooling automatically. Rate limit headers from each response are exposed as client.last_rate_limit (RateLimitInfo dataclass) for application-level throttling logic.',
    ]},
  ],
  aiCapabilities: [
    { capability: 'Intelligent Route Selection', desc: 'Beyond simple prefix matching, the Gateway analyzes request content when multiple routes could match and selects the most specific backend. A query containing "IRC section 179" is routed to echo-engine-runtime with domain: "TX" pre-injected, bypassing the more generic /v1/query handler.' },
    { capability: 'Request Normalization', desc: 'Inconsistent request formats from different client SDK versions are normalized at the Gateway before forwarding. Legacy v2 request shapes are automatically translated to v3 format, enabling SDK version upgrades to roll out independently of backend Worker changes.' },
    { capability: 'Adaptive Rate Limiting', desc: 'Rate limit windows are per-key and per-endpoint tier, not global. A key with both engines and chat scopes has independent rate limit windows for each service type. Burst patterns (10 rapid requests then quiet) are handled gracefully without penalizing the next hour\'s window.' },
    { capability: 'Health Scoring', desc: 'The health aggregator uses weighted scoring across all backend Workers. Workers marked as critical (engine-runtime, chat) have higher weight in the overall system health score. A single non-critical Worker being down does not degrade the overall status to unhealthy.' },
    { capability: 'Response Caching', desc: 'Cacheable GET endpoints (engines list, knowledge search, health) use Cache-Control headers and Cloudflare\'s edge cache. Frequently requested engine lists are served from cache in <5ms globally. Cache is invalidated on registry updates and engine data changes.' },
    { capability: 'Error Intelligence', desc: 'When a backend Worker returns a 5xx error, the Gateway retries once after 200ms before returning the error to the client. The error response includes a correlation request_id, the backend Worker that failed, and a suggested retry_after time based on the error type (transient vs. persistent).' },
  ],
  troubleshooting: [
    { issue: 'API key returning 401 on all requests', solution: 'Verify the key is being sent in the X-Echo-API-Key header, not Authorization: Bearer. Check that the key has not been revoked in the SDK dashboard. If the key was just created, allow up to 60 seconds for KV propagation across Cloudflare\'s edge network before testing.' },
    { issue: 'Requests routing to wrong backend Worker', solution: 'Check GET /v1/logs for the request_id and review the matched_prefix and target_worker fields. If the wrong prefix is matching, the routing table may have a conflicting entry. Review the registry with GET /v1/registry and adjust the path specificity — more specific prefixes always win in longest-prefix matching.' },
    { issue: 'Rate limit hit unexpectedly', solution: 'Check X-RateLimit-Remaining on recent responses to see how quickly the window is depleting. If usage is legitimately high, upgrade the key tier in the SDK dashboard. If usage seems lower than the limit, check whether multiple application instances are sharing the same API key — rate limits are global per key, not per instance.' },
    { issue: 'TypeScript SDK TypeScript errors on response types', solution: 'Ensure you are on the latest SDK version (npm update @echo-prime/sdk). Type definitions are versioned with the SDK and are updated when new Gateway endpoints are added. Running npx @echo-prime/sdk codegen regenerates local type stubs from the live OpenAPI spec at /v1/docs.' },
    { issue: 'Streaming responses not working', solution: 'Streaming requires the Accept: text/event-stream header (handled automatically by SDK stream methods). If using raw fetch(), ensure you are not buffering the response body — stream it with response.body.getReader(). Cloudflare Workers requires the cf-cache-status header to be absent on streaming routes; ensure no cache middleware is intercepting the request.' },
  ],
  faq: [
    { q: 'Why use the SDK Gateway instead of calling Workers directly?', a: 'Direct Worker URLs expose internal service topology, require managing multiple base URLs per client, require custom auth per Worker, and bypass centralized rate limiting and logging. The Gateway provides a single integration point that remains stable as the backend evolves. For internal Worker-to-Worker communication, service bindings are used directly — the Gateway is for external clients.' },
    { q: 'What is the Gateway\'s latency overhead?', a: 'Routing overhead is typically 0.3-0.8ms. Service bindings (Worker-to-Worker) add <0.5ms. Total Gateway latency for a cached route is under 1ms. For uncached routes requiring KV lookup, add 1-3ms. End-to-end latency is dominated by the backend Worker, not the Gateway layer.' },
    { q: 'How are multiple environments (dev, staging, production) handled?', a: 'Each environment has its own Gateway deployment with its own routing table and API key namespace. The SDK accepts an optional baseUrl parameter to point at a non-production Gateway. Environment-specific keys are scoped to their environment\'s Gateway and cannot cross-authenticate.' },
    { q: 'Can I use the Gateway for webhooks or incoming callbacks?', a: 'Yes. Register a route with method: "POST" pointing to a Worker that handles the webhook payload. The Gateway forwards the full request including headers (useful for HMAC signature verification). Rate limiting is bypassed for registered webhook routes to prevent callback drops.' },
    { q: 'How are breaking API changes communicated?', a: 'Version increments in the v1 path prefix signal breaking changes. A 12-month deprecation window is maintained — v1 routes remain active after v2 launches. Deprecation notices are surfaced as X-API-Deprecation headers on affected endpoints starting 60 days before removal.' },
    { q: 'Is the OpenAPI spec machine-readable for code generation?', a: 'Yes. GET /v1/docs returns a fully standards-compliant OpenAPI 3.1 JSON document. It is compatible with openapi-typescript (tsc-compatible type generation), openapi-generator-cli (multi-language SDK generation), and Postman collection import. The spec is regenerated on every routing table update.' },
  ],
}

export default function SDKGatewayDocPage() {
  return <ProductDoc {...data} />
}
