'use client'

import ProductDoc from '@/components/ProductDoc'

const data = {
  name: 'Echo Forge Marketplace',
  tagline: 'The app store for AI expertise. Browse, compare, and subscribe to 5,500+ domain-specific Intelligence Engines — from tax law to oilfield drilling to cybersecurity — with previews, ratings, and instant deployment.',
  accent: '#eab308',
  productUrl: '/engines/marketplace',
  workerUrl: 'https://echo-forge-marketplace.bmcii1976.workers.dev',
  version: '1.3.0',
  overview: [
    'Echo Forge Marketplace is the discovery and commerce layer on top of the Echo Engine Runtime — the storefront where professionals, developers, and enterprises find and subscribe to the exact AI intelligence engines they need. With 5,500+ engines across 200+ domain categories, finding the right engine without a guided discovery experience would be overwhelming. The Marketplace solves this with rich filtering, side-by-side comparison tools, live preview queries, user ratings, detailed capability descriptions, and a subscription management interface that gives you fine-grained control over which engines your applications can call.',
    'Every engine in the Marketplace is documented with its domain scope, doctrine count (the number of indexed authoritative source blocks backing its answers), confidence stratification behavior, version history, sample queries with real answers, user reviews, and performance statistics (average latency, queries served, uptime). Before committing to a subscription, you can run up to 5 preview queries against any engine at no charge to verify it handles your specific question types correctly. This eliminates the guesswork that plagues most API marketplace purchases.',
    'The Marketplace is also the commercial interface for the Echo engine ecosystem. Engines are priced across four tiers — Supreme, Critical, Engineering, and Standard — based on domain complexity, professional liability, and doctrine density. Enterprise customers negotiate custom pricing, volume discounts, and SLA agreements directly through the Marketplace interface. Usage is tracked per engine at the query level so you always know exactly which engine is consuming quota and can optimize your subscription portfolio to minimize cost while maintaining coverage.',
  ],
  gettingStarted: [
    { step: 1, title: 'Browse the Marketplace', desc: 'Navigate to /engines/marketplace to see the full engine catalog. Use the domain category filters on the left to narrow to your industry: Tax, Legal, Land & Minerals, Cybersecurity, Medical, Financial, Drilling, Forensics, and 190+ more. The default view shows featured engines sorted by usage and rating.' },
    { step: 2, title: 'Preview an Engine', desc: 'Click any engine listing and scroll to the Preview section. Enter up to 5 sample queries relevant to your use case and run them for free. The preview returns the actual engine output — the answer, confidence level, and doctrine citations — so you can judge quality before subscribing.' },
    { step: 3, title: 'Compare Engines', desc: 'Use the Compare button on up to 4 engine listings simultaneously. The comparison table shows doctrine count, pricing tier, average latency, uptime, user rating, confidence level distribution, and sample query results side by side. Comparison is the fastest way to choose between similar engines.' },
    { step: 4, title: 'Subscribe', desc: 'Click Subscribe on your chosen engine. Select your subscription tier (Starter, Professional, Enterprise) which determines monthly query quota and SLA. After subscribing, your API key is automatically granted access to the engine via the Engine Runtime. Queries start working immediately.' },
    { step: 5, title: 'Monitor Usage', desc: 'Check your subscription dashboard at /engines/marketplace/subscriptions for per-engine usage metrics: queries used vs. quota, average latency, error rate, and cost-to-date. Usage resets monthly. Set usage alerts to notify you before hitting quota limits.' },
  ],
  features: [
    { title: 'Engine Catalog with 5,500+ Engines', desc: '5,500+ active Intelligence Engines indexed and searchable with full metadata: domain category, doctrine count, pricing tier, version, last updated date, user rating, and performance statistics. The catalog grows daily as new engines are built and published to the Marketplace.' },
    { title: 'Domain Filtering (200+ Categories)', desc: 'Hierarchical domain taxonomy with 200+ categories organized into industry verticals. Filter by top-level industry (Tax, Legal, Oilfield, Finance, Cybersecurity, Medical, Construction, Manufacturing, Real Estate, Transportation) and then by sub-domain specialization for precision discovery.' },
    { title: 'Pricing Tiers (Supreme/Critical/Engineering/Standard)', desc: 'Four pricing tiers aligned to domain complexity and professional liability. Supreme covers tax law, legal analysis, and regulatory compliance where errors have highest consequence. Critical covers cybersecurity, medical, and financial analysis. Engineering covers technical domains like drilling and construction. Standard covers general business and IT domains.' },
    { title: 'Engine Preview with Sample Queries', desc: 'Run up to 5 live queries against any engine before subscribing, at no charge. Previews return full engine output: the answer, confidence stratification, doctrine citations, and performance metrics. Preview results are logged to your account so you can revisit them when comparing options.' },
    { title: 'User Ratings and Reviews', desc: 'Verified subscribers rate engines on answer quality (1-5 stars), citation accuracy (1-5 stars), and latency (1-5 stars). Written reviews include the reviewer\'s professional role and primary use case. Ratings are verified — only subscribers who have executed at least 10 queries can post reviews.' },
    { title: 'Subscription Management', desc: 'Manage all active subscriptions from a single dashboard. View per-subscription query usage vs. quota, monthly cost, renewal date, and usage trend. Upgrade, downgrade, or cancel subscriptions at any time. Canceled subscriptions remain active until the end of the billing period.' },
    { title: 'Usage Tracking per Engine', desc: 'Per-engine usage telemetry at query granularity: timestamp, query text, response confidence level, latency, tokens consumed, and cost. Usage logs are available for export and searchable for billing verification, cost optimization analysis, and workflow debugging.' },
    { title: 'Engine Comparison Tool', desc: 'Select up to 4 engines and compare them in a structured side-by-side table. Comparison dimensions include doctrine count, pricing, latency (p50/p95), uptime, confidence level distribution (what percentage of queries return DEFENSIBLE vs. lower confidence), user rating, and sample query responses.' },
    { title: 'Category Browsing', desc: 'Browse engines by clicking into category nodes in the domain taxonomy. Each category page shows the top engines by usage, average rating, and doctrine density. Category pages include a narrative description of what kinds of questions the engines in that category are best suited for.' },
    { title: 'Featured Engines', desc: 'Curated featured engine collections: Editor\'s Picks (highest quality engines in each major category), Rising Stars (new engines with strong early ratings), Most Powerful (highest doctrine count), and Fastest (lowest latency for real-time applications). Featured collections are updated weekly.' },
    { title: 'New Engine Alerts', desc: 'Subscribe to category alerts to receive notifications when new engines are published in your domains of interest. Alerts are delivered via email, push notification, or webhook. Alert subscriptions are free and independent from engine subscriptions.' },
    { title: 'Bulk Subscription Discounts', desc: 'Organizations subscribing to 10+ engines simultaneously qualify for volume discounts: 10-24 engines (15% off), 25-49 engines (25% off), 50+ engines (custom enterprise pricing). Bulk subscriptions are managed under a single billing account with consolidated usage reporting and invoicing.' },
  ],
  apiEndpoints: [
    { method: 'GET', path: '/marketplace/engines', desc: 'List engines in the Marketplace catalog. Supports filtering by category, pricing_tier, min_rating, min_doctrine_count, sort (rating, usage, newest, latency). Returns paginated engine listings with summary metadata. Default sort is featured + rating combined score.', auth: false },
    { method: 'GET', path: '/marketplace/engines/:id', desc: 'Get full engine detail: domain, category, doctrine count, version history, performance statistics (latency p50/p95/p99, uptime, queries served), pricing tiers, user ratings breakdown, recent reviews, sample queries with cached responses, and related engine suggestions.', auth: false },
    { method: 'GET', path: '/marketplace/categories', desc: 'Retrieve the full domain category taxonomy. Returns hierarchical category tree with engine count per node, average category rating, top 3 engines per category, and category description. Use category codes for filtering /marketplace/engines results.', auth: false },
    { method: 'POST', path: '/marketplace/subscribe', desc: 'Subscribe to an engine. Accepts engine_id, subscription_tier (starter/professional/enterprise), and billing_cycle (monthly/annual). Returns subscription_id, activation timestamp, query quota, and confirmation of API key grant. Immediate activation for standard tiers.', auth: true },
    { method: 'GET', path: '/marketplace/subscriptions', desc: 'List all active subscriptions for the authenticated account. Returns per-subscription details: engine_id, tier, queries_used, queries_quota, renewal_date, monthly_cost, usage_trend (last 30 days chart data), and status (ACTIVE/PAUSED/CANCELLED/EXPIRED).', auth: true },
    { method: 'POST', path: '/marketplace/preview', desc: 'Run a preview query against an engine without a subscription. Accepts engine_id and query text. Returns full engine response: answer, confidence level, doctrine citations, and performance metrics. Limited to 5 previews per engine per account. Response is identical to a live subscribed query.', auth: true },
    { method: 'GET', path: '/marketplace/featured', desc: 'Get the current featured engine collections: editor_picks (5 engines), rising_stars (5 engines), highest_doctrine_count (5 engines), lowest_latency (5 engines), and newest (5 engines). Collections are updated weekly. No authentication required.', auth: false },
    { method: 'GET', path: '/health', desc: 'Forge Marketplace service health. Returns catalog size (engine and category counts), subscription system status, Engine Runtime connectivity, preview execution latency, and any active alerts on the billing or subscription infrastructure. No authentication required.', auth: false },
  ],
  userGuide: [
    { id: 'engine-selection', title: 'Selecting the Right Engine', content: [
      'Engine selection is a two-step process: first narrow by domain, then evaluate by quality metrics. Domain filtering is straightforward — if you need tax analysis, filter by the TX category. If you need something more specific like oil and gas royalty taxation, drill into TX → TX-MINERALS. The more specific the sub-category, the higher the doctrine density for that specific topic and the more accurate the answers.',
      'Once you have a shortlist of 3-5 candidate engines in your domain, evaluate them on four dimensions: doctrine count (more doctrines generally means better coverage), confidence distribution (engines where >60% of queries return DEFENSIBLE are suitable for professional work product), latency (for interactive applications, p95 < 2s is a practical threshold), and user ratings (focus on ratings from users in your professional role).',
      'Preview queries are the single most important evaluation tool. Do not subscribe based on doctrine count and ratings alone. Run 3-5 of your actual production queries against the engine in preview mode. If the engine handles your real questions correctly — citing relevant sources, producing DEFENSIBLE confidence levels, and catching the nuances that matter in your domain — it is likely a good fit. If previews produce HIGH_RISK confidence on your standard questions, look for an engine with denser doctrine coverage in your sub-domain.',
    ]},
    { id: 'pricing-tiers', title: 'Understanding Pricing Tiers', content: [
      'The four pricing tiers reflect the resource intensity, domain expertise, and professional liability associated with each engine category. Supreme tier engines (Tax, Legal, Medical-Clinical, Financial-Regulatory) involve domains where errors have severe professional and legal consequences. They carry the highest doctrine density, the strictest citation requirements, and the highest pricing to reflect the accuracy engineering required.',
      'Critical tier engines (Cybersecurity, Medical-General, Financial-Analytics, Forensics) address domains with significant but slightly lower-stakes consequence for errors. Engineering tier (Drilling, Construction, Manufacturing, Chemical) covers technical domains where accuracy is essential but consequences are bounded to specific technical decisions. Standard tier covers general business, IT operations, HR, marketing, and similar domains where quality matters but professional liability is lower.',
      'Subscription tiers within each engine (Starter, Professional, Enterprise) control query quota, SLA guarantees, and support level. Starter is for evaluation and low-volume production use. Professional covers most production workloads with a 99.5% uptime SLA and priority support. Enterprise provides unlimited queries, 99.9% uptime, dedicated support, and custom contract terms. Annual subscriptions receive a 20% discount vs. monthly.',
    ]},
    { id: 'subscription-management', title: 'Managing Your Subscriptions', content: [
      'The subscription dashboard at /engines/marketplace/subscriptions is your command center for all active engine subscriptions. The dashboard shows real-time usage meters for each subscription — you can see at a glance which engines are consuming quota quickly and which are underutilized. Underutilized subscriptions are candidates for tier downgrade or cancellation; over-utilized subscriptions (approaching quota) need immediate tier upgrade to avoid query rejections.',
      'Usage alerts prevent surprise quota exhaustion. Set an alert threshold (default 80% of monthly quota) per subscription. When usage crosses the threshold, you receive a notification with current usage rate, projected end-of-period usage, and a direct link to upgrade the subscription tier. Alerts can be routed to email, push, or webhook.',
      'Subscription changes (upgrades, downgrades, cancellations) take effect immediately for upgrades and at the end of the current billing period for downgrades and cancellations. Mid-month upgrades are prorated. You will never lose access to a subscribed engine mid-billing-period due to a tier change — the new tier takes effect only when the billing period resets.',
    ]},
    { id: 'reviews-ratings', title: 'Writing and Interpreting Reviews', content: [
      'Reviews are the most valuable community resource in the Marketplace. When reading reviews, prioritize those from reviewers whose professional role matches yours — a tax attorney\'s review of a tax engine is more relevant to another tax attorney than a developer\'s review of the same engine. The reviewer\'s role and use case are displayed with each review to facilitate this filtering.',
      'When writing a review, describe your specific use case, the types of questions you asked, and whether the confidence levels matched your professional expectation for those questions. "The engine returned DEFENSIBLE confidence on basic IRC section analysis but dropped to AGGRESSIVE on complex multi-entity structuring questions" is a far more useful review than "great engine, 5 stars." Detailed reviews receive upvotes from the community and are surfaced more prominently.',
      'The aggregate star rating visible on engine listings is a weighted average that gives more weight to recent reviews (last 90 days) and reviews from verified high-usage subscribers (those with 100+ queries on the engine). This weighting prevents stale reviews from distorting ratings and ensures that the people who have tested engines most thoroughly have the greatest influence on the score.',
    ]},
    { id: 'enterprise-licensing', title: 'Enterprise Licensing and Custom Engines', content: [
      'Enterprise customers with subscriptions to 50+ engines or monthly query volumes exceeding 100K receive access to the Enterprise portal within the Marketplace. The Enterprise portal provides consolidated billing across all subscriptions, custom contract terms with SLA guarantees up to 99.99%, dedicated account management, and early access to new engine releases before public launch.',
      'The Marketplace is also the interface for procuring custom engines. If no existing engine covers your specialized domain (e.g., Permian Basin mineral rights conveyance law specific to Texas Panhandle jurisdictions), you can submit a custom engine request. Custom engine builds are scoped and priced based on the doctrine ingestion volume, domain complexity, and required confidence tier.',
      'White-label deployment is available for Enterprise customers who want to expose engine capabilities through their own branded interface. The Marketplace API supports white-label mode where the response envelope omits Echo branding and substitutes your organization\'s identity. Custom domains for white-label deployments are configured through the Cloudflare account and verified via DNS TXT record.',
    ]},
  ],
  aiCapabilities: [
    { capability: 'Semantic Engine Discovery', desc: 'Natural language search queries for engines are embedded and matched against the catalog using the same vector search infrastructure as Tool Discovery. Searching "analyze IRC section 199A pass-through deduction eligibility" finds the correct tax engine even without knowing the engine code, category, or exact keywords from its description.' },
    { capability: 'Preview Quality Assessment', desc: 'Preview responses are automatically scored for answer completeness, citation count, confidence appropriateness (are high-confidence answers actually well-supported?), and response length adequacy. The quality scores are surfaced alongside preview results so you can compare engines objectively rather than relying solely on subjective impression.' },
    { capability: 'Subscription Optimization Engine', desc: 'AI analyzes your query history across all subscriptions to identify optimization opportunities: engines with very low usage that could be replaced by a cheaper tier or a single cross-domain engine, domains where your queries are routing to sub-optimal engines and a higher-quality option exists, and usage patterns that would be cheaper under annual vs. monthly billing.' },
    { capability: 'Recommendation Based on Query Patterns', desc: 'When you add an engine subscription, the recommendation engine analyzes the topics of your recent queries across all subscriptions and recommends related engines you likely need. If you subscribe to a corporate tax engine and your query history includes partnership taxation questions, the engine recommends the partnership taxation specialist engine.' },
    { capability: 'Review Sentiment Analysis', desc: 'All text reviews are sentiment-analyzed and topic-tagged automatically. Topic tags (citation accuracy, latency, domain coverage, edge cases, professional use cases) allow you to filter reviews by the dimension you care most about. Sentiment analysis detects when review sentiment diverges from star rating — a 5-star review that is actually ambivalent is flagged for moderation.' },
    { capability: 'Engine Quality Monitoring', desc: 'Continuous monitoring of engine answer quality using a held-out test set of golden queries per engine. If an engine\'s answers on the test set degrade (lower confidence, fewer citations, lower accuracy on verifiable facts), the engine\'s quality score drops and it receives a lower ranking in search results until the issue is resolved by the engine maintainer.' },
  ],
  troubleshooting: [
    { issue: 'Preview queries return no results or empty answers', solution: 'The engine may not have doctrine coverage for your specific sub-topic. Check the engine\'s doctrine count and domain scope in the listing — a low doctrine count for a broad domain means sparse coverage. Try rephrasing your preview query to be more general. If the engine consistently fails to answer your specific question type, it is not the right engine for your use case — check related engines in the same category.' },
    { issue: 'Subscribed engine returning "quota exceeded" errors', solution: 'Your subscription has hit its monthly query quota. Upgrade your subscription tier via POST /marketplace/subscribe with the new tier. The upgrade is immediate and the additional quota is available within seconds. To prevent recurrence, enable usage alerts at 80% threshold and review your usage dashboard to identify the highest-volume query patterns — these may be candidates for caching at your application layer.' },
    { issue: 'Engine not appearing in search results after subscribing', solution: 'Subscription grants API access via the Engine Runtime, not enhanced search ranking. Your subscribed engine should be discoverable via search whether or not you are subscribed. If an engine is missing from search results, it may be temporarily marked UNAVAILABLE due to maintenance. Check the engine listing directly via GET /marketplace/engines/:id to see its current status.' },
    { issue: 'User reviews showing for wrong engine or appearing blank', solution: 'Reviews are cached at CDN level for performance. New reviews may take up to 5 minutes to appear. Review filtering by role or use case tag may exclude all reviews if the filter is too narrow — clear all filters to see the full unfiltered review list. If you believe a review is appearing on the wrong engine, report it via the listing\'s flag review link.' },
    { issue: 'Comparison tool not showing accurate latency data', solution: 'Latency data in comparisons is based on the last 24 hours of execution telemetry. If an engine has very few queries in the last 24 hours (common for new engines or highly specialized ones), the latency data may be missing or based on a single sample. Preview queries do count toward latency statistics — running 5 preview queries before comparing will populate latency data for engines with no recent history.' },
  ],
  faq: [
    { q: 'What is the difference between the Marketplace and the Engine Runtime?', a: 'The Engine Runtime is the execution layer — it runs your queries against doctrine blocks and returns answers. The Marketplace is the discovery and commerce layer — it helps you find the right engines, evaluate them before subscribing, and manage your subscriptions. You interact with the Marketplace to choose and subscribe to engines, then interact with the Engine Runtime to actually query them.' },
    { q: 'How are engines priced? What determines a Supreme vs. Standard tier engine?', a: 'Pricing tiers are set by the engine builder based on domain complexity, the professional liability associated with errors, and the resource cost of maintaining high-quality doctrine coverage. Supreme tier requires the most rigorous sourcing (primary law, settled case law, official regulatory text) and carries the highest per-query price. Standard tier uses lower-stakes sources and has more tolerance for advisory-level authority.' },
    { q: 'Can I get a refund if an engine does not meet my needs after subscribing?', a: 'Subscriptions can be canceled at any time. Monthly subscriptions that have been active for less than 7 days with fewer than 10 queries used are eligible for a full refund by contacting support. Annual subscriptions are non-refundable after 30 days but can be downgraded to a lower tier with prorated credit for the difference. This is why we strongly recommend running preview queries before subscribing.' },
    { q: 'How often are engine doctrine blocks updated?', a: 'Update frequency varies by engine and domain. Tax engines are updated quarterly and whenever major legislative changes occur (like year-end tax legislation). Cybersecurity engines are updated weekly to capture new CVEs and framework updates. Case law engines ingest new decisions as they are published. Each engine listing shows its last_updated date and update_frequency in the engine detail page.' },
    { q: 'Can I build my own engine and list it in the Marketplace?', a: 'Yes. Engine publication is available to Enterprise customers and approved third-party developers. You build the doctrine blocks and provide the authoritative sources, and the Echo Engine Runtime handles indexing, querying, confidence stratification, and API exposure. Published engines go through a quality review process before being listed publicly. Revenue sharing for third-party engines is negotiated in the developer agreement.' },
    { q: 'What happens to my subscriptions if I reach the end of a billing period with unused quota?', a: 'Unused query quota does not roll over. Each billing period starts with a fresh quota allocation. If you consistently use less than 50% of your quota, consider downgrading to a lower subscription tier or canceling and switching to per-query pay-as-you-go billing (available on Standard and Engineering tier engines). The usage dashboard shows your 3-month average utilization per subscription to help you right-size.' },
  ],
}

export default function ForgeMarketplaceDocPage() {
  return <ProductDoc {...data} />
}
