'use client'

import ProductDoc from '@/components/ProductDoc'

const data = {
  name: 'Title Intelligence',
  tagline: 'AI-powered chain of title research, mineral rights analysis, and run sheet generation across 254 Texas counties — expanding nationwide.',
  accent: '#f59e0b',
  productUrl: '/title-intelligence',
  workerUrl: 'https://echo-landman-pipeline.bmcii1976.workers.dev',
  version: '3.1.0',
  overview: [
    'Title Intelligence is Echo Prime\'s landman and title research platform. It automates the entire chain-of-title workflow — from county record search through gap detection to run sheet generation — using a combination of direct courthouse portal integrations, knowledge graph traversal, and domain-specific AI engines. Instead of spending weeks manually searching grantor-grantee indexes and assembling ownership histories, Title Intelligence completes a full title chain investigation in hours.',
    'The platform connects directly to Texas county clerk offices through TexasFile, GovOS, Tyler Technologies, and Odyssey courthouse portals via ShadowGlass scraping. It covers 98 Texas counties today with expansion planned to all 254 Texas counties and then nationwide. When you submit a property query (legal description, section/block/survey, or party name), the system searches live courthouse records, traverses 16M+ pre-indexed instruments, classifies 59 instrument types across 6 categories, and builds a complete ownership chain from sovereignty to present.',
    'Every title investigation produces a professional run sheet with current NMA/NRI calculations using exact rational arithmetic (never floating-point rounding), a chronological instrument index with book/page references, probate family trees, gap analysis with severity scoring and curative recommendations, and confidence stratification — DEFENSIBLE, AGGRESSIVE, DISCLOSURE, or HIGH_RISK — so landmen and title examiners know exactly how reliable each link in the chain is. Reports export as interactive HTML, downloadable DOCX, and structured JSON via API.',
  ],
  gettingStarted: [
    { step: 1, title: 'Submit a Property Query', desc: 'Navigate to echo-ept.com/title-intelligence and enter a county name, section/block/survey identifiers, abstract number, or party name. The system also accepts raw legal descriptions — the parser handles the rest.' },
    { step: 2, title: 'Monitor the Investigation', desc: 'Title chain investigations run asynchronously because courthouse portal searches take time. Monitor real-time progress as the system searches records, assembles the chain, runs gap analysis, and generates the report. Typical turnaround is 2 to 8 hours depending on chain complexity.' },
    { step: 3, title: 'Review the Run Sheet', desc: 'When the investigation completes, review the full run sheet with five tabs: Summary (ownership overview), Run Sheet (NMA/NRI tables), Ownership (current interest holders), Gaps (breaks with curative recommendations), and Full Report (complete instrument index and chain).' },
    { step: 4, title: 'Export or Integrate', desc: 'Download the report as DOCX for client deliverables or consume the structured JSON via API for integration with your project management, GIS, or lease management systems. Webhook callbacks notify your systems when async jobs complete.' },
    { step: 5, title: 'Run Batch Searches', desc: 'Professional and Enterprise plans support batch processing — submit 100+ title searches in a single request. The pipeline parallelizes across courthouse portals and delivers all results within 24 to 48 hours.' },
  ],
  features: [
    { title: 'Automated Chain Construction', desc: 'Build gap-free chains of title from sovereignty to present. AI traverses grantor-grantee indexes, resolves name variations, and links instruments across decades — in hours, not weeks. Knowledge graph traversal ensures no link is missed.' },
    { title: 'Probate & Heirship Resolution', desc: 'Automatically track multi-generation intestate succession. Apply Texas Estates Code Chapter 201 intestacy rules, calculate fractional shares with exact rational arithmetic, and detect missing heirs. Family tree visualization included in every probate tract.' },
    { title: 'Fractional Interest Calculator', desc: 'NMA, NRI, working interest, ORRI, and overconveyance analysis. Every calculation uses exact fractions — never floating-point rounding. Verify 8/8ths balance across all ownership lines. Detects overconveyances where granted interests exceed the mineral estate.' },
    { title: '59 Instrument Types', desc: 'Classify and extract data from 59+ instrument types across 6 categories: Conveyance (18 types), Lease (8), Encumbrance (10), Easement & ROW (7), Probate & Succession (10), and Miscellaneous (12). From general warranty deeds to division orders — every instrument is typed and indexed.' },
    { title: 'Direct Courthouse Access', desc: 'ShadowGlass connects to 98 Texas county clerk portals including GovOS, Tyler Technologies, TexasFile, and Odyssey systems. No middlemen, no third-party data vendors. Live portal searches fill gaps that pre-indexed records miss.' },
    { title: 'Gap Detection & Curative', desc: 'AI identifies breaks in the chain: missing probates, unrecorded transfers, overconveyances, orphan instruments, and recording gaps longer than statutory thresholds. Each gap receives a severity score (critical, moderate, minor) and a specific curative recommendation.' },
    { title: 'Async Job Processing', desc: 'Title chain investigations are long-running operations — courthouse searches and chain assembly can take hours. The platform uses async job processing with real-time progress updates polled every 3 seconds. Submit and monitor via API or the web interface.' },
    { title: 'Professional Run Sheets', desc: 'Gold-standard HTML and DOCX reports with ownership tables, family trees, timeline visualization, instrument index, confidence scores, and legal theory analysis. Reports meet the standards expected by oil and gas operators and title companies.' },
    { title: 'Confidence Stratification', desc: 'Every chain link and ownership conclusion carries a confidence level: DEFENSIBLE (strong authority), AGGRESSIVE (reasonable but higher risk), DISCLOSURE (requires notification), or HIGH_RISK (thin authority). Landmen know exactly how much weight to place on each finding.' },
    { title: '16M+ Pre-Indexed Records', desc: 'The system maintains a pre-indexed database of 16 million+ courthouse instruments. Searches first hit the index for instant results, then supplement with live portal scraping for gaps. This hybrid approach delivers both speed and completeness.' },
    { title: 'Multi-Domain Engine Integration', desc: 'Title Intelligence draws on 5,486+ domain engines with 697K+ doctrine blocks spanning oil and gas law, property law, environmental compliance, and mineral rights. Edge cases are resolved against real legal authority, not probabilistic guesses.' },
    { title: 'Batch Processing', desc: 'Submit 100+ title searches in a single batch request. The pipeline parallelizes across courthouse portals and engine clusters. Results are delivered within 24 to 48 hours with per-title status tracking and webhook notifications.' },
  ],
  apiEndpoints: [
    { method: 'POST', path: '/search', desc: 'Search county courthouse records by keyword, party name, or legal description. Returns matching instruments with grantor, grantee, instrument type, book/page, and filing date. Supports pagination and county filtering.', auth: true },
    { method: 'POST', path: '/title-chain', desc: 'Start a full chain-of-title investigation. Provide county, section, block, abstract, or party name. Returns a job_id for async progress tracking. The pipeline searches records, builds the chain, runs gap analysis, and generates a professional run sheet.', auth: true },
    { method: 'GET', path: '/jobs/:id', desc: 'Get the progress and status of an async title investigation job. Returns current phase (searching, assembling, analyzing, reporting), percentage complete, intermediate findings, and the final result when the job completes.', auth: true },
    { method: 'GET', path: '/counties', desc: 'List all supported counties with their portal type (GovOS, Tyler, TexasFile, Odyssey), record count in the pre-indexed database, and availability status. Use this to check coverage before submitting a search.', auth: false },
    { method: 'GET', path: '/health', desc: 'Health check endpoint returning system status, uptime, active job count, courthouse portal connectivity, and database statistics.', auth: false },
    { method: 'POST', path: '/batch', desc: 'Submit a batch of title investigations (up to 100 per request). Each item specifies county, section, block, and optional party name. Returns an array of job_ids for individual progress tracking.', auth: true },
    { method: 'GET', path: '/jobs/:id/report', desc: 'Download the completed investigation report in the requested format (HTML, DOCX, or JSON). Only available after the job status is "complete". The JSON format returns the full structured chain data for programmatic consumption.', auth: true },
    { method: 'GET', path: '/stats', desc: 'System-wide statistics: total records indexed, counties covered, jobs completed, average chain length, average turnaround time, and portal uptime per county.', auth: false },
  ],
  userGuide: [
    { id: 'chain-of-title', title: 'Understanding Chain of Title', content: [
      'A chain of title is the complete ownership history of a property from the original land grant (sovereignty) to the present owner. In Texas oil and gas, the chain must trace both surface and mineral rights separately because they can be severed by deed. A break in the chain — a missing conveyance, unrecorded probate, or ambiguous legal description — can cloud title and delay leasing or drilling operations.',
      'Title Intelligence builds chains automatically by searching county records, classifying each instrument (deed, lease, lien, easement, probate), extracting grantor-grantee relationships, and linking them into a directed graph. The system resolves common complications: name variations (Bobby vs. Robert, maiden vs. married names), fractional conveyances (1/2 of 1/4 of the mineral estate), and multi-generation intestate succession under Texas Estates Code Chapter 201.',
      'The resulting chain is visualized as a timeline with each instrument plotted by recording date. Branches show where mineral and surface rights diverge. Probate tracts include family tree diagrams showing the succession path. Every link in the chain carries a confidence score based on the strength of the underlying instrument and the completeness of the supporting records.',
    ]},
    { id: 'mineral-rights', title: 'Mineral Rights & Interest Calculations', content: [
      'Mineral rights in Texas can be severed from surface rights and further divided into net mineral acres (NMA), net revenue interest (NRI), working interest (WI), and overriding royalty interest (ORRI). Title Intelligence calculates all of these using exact rational arithmetic — never floating-point approximations that introduce rounding errors in fractional mineral interests.',
      'For example, if a 640-acre section is split between four heirs each receiving 1/4, and one heir subsequently conveys 1/2 of their mineral interest, the system computes that grantee\'s NMA as 640 * 1/4 * 1/2 = 80 NMA exactly. It then verifies that all interests in the section sum to the full mineral estate (8/8ths). Overconveyances — where the total granted interest exceeds the estate — are flagged automatically.',
      'Division order analysis is built into the pipeline. When a lease is in place, the system calculates each interest holder\'s decimal share and generates a draft division order table. This is particularly valuable for operators preparing to pay royalties and landmen who need to verify existing division orders against the actual chain of title.',
    ]},
    { id: 'courthouse-portals', title: 'Courthouse Portal Integration', content: [
      'Title Intelligence connects directly to county clerk recording portals across Texas. The four major portal systems are GovOS (used by many West Texas counties), Tyler Technologies, TexasFile, and Odyssey. Each has a different search interface, record format, and access pattern.',
      'ShadowGlass, our headless browser engine, handles the portal-specific differences. It navigates each portal\'s search forms, submits queries by party name, date range, and instrument type, extracts the results, and normalizes them into a common schema. For TexasFile portals specifically, the system handles column misalignment issues where recorded dates and party names appear in unexpected fields.',
      'Live portal searches are triggered automatically when the pre-indexed database has gaps for a specific property or time period. The system queues portal searches in the background, and results are merged into the chain as they arrive. Portal search results are cached and added to the pre-indexed database so subsequent searches for the same county are faster.',
    ]},
    { id: 'gap-analysis', title: 'Gap Detection & Curative Recommendations', content: [
      'Gap analysis is the most critical quality check in a title examination. Title Intelligence identifies five categories of gaps: missing conveyances (a property appears to transfer without a recorded deed), unrecorded probates (an owner dies without a will or affidavit of heirship on file), overconveyances (total interests granted exceed the mineral estate), orphan instruments (recorded documents that cannot be linked to the chain), and recording gaps (extended periods with no activity that may indicate unrecorded transfers).',
      'Each gap receives a severity classification. Critical gaps — like a missing link in the chain or an overconveyance — must be resolved before a title opinion can be issued. Moderate gaps — such as a missing release of lien or an unfiled probate for a small fractional interest — may be curable with an affidavit or corrective instrument. Minor gaps — like a recording delay or a name variation that resolves with additional context — are flagged for awareness but typically do not block title clearance.',
      'For every gap, the system generates a specific curative recommendation: file an affidavit of heirship, obtain a corrective deed, record a missing probate, or request a release from a lienholder. These recommendations cite the relevant Texas Property Code sections and are designed to be actionable by the landman or title attorney reviewing the report.',
    ]},
    { id: 'async-pipeline', title: 'Async Pipeline & Job Monitoring', content: [
      'Title chain investigations are inherently long-running. Searching courthouse portals, assembling complex chains, running gap analysis, and generating professional reports can take 2 to 8 hours. Title Intelligence uses an async job pipeline so you can submit a search and check back for results rather than waiting with an open connection.',
      'When you POST to /title-chain, the system returns a job_id immediately. Poll GET /jobs/:id every few seconds to monitor progress. The response includes the current phase (searching, assembling, analyzing, reporting), percentage complete, and any intermediate findings discovered so far. The web interface polls automatically every 3 seconds and displays a live progress dashboard.',
      'Jobs can complete in one of four statuses: "complete" (success — results are ready for download), "failed" (an unrecoverable error occurred — check the error field), "cancelled" (the job was manually cancelled), or "timeout" (the investigation exceeded the maximum allowed duration). Failed jobs include diagnostic information to help you adjust the query and retry.',
    ]},
    { id: 'confidence-levels', title: 'Confidence Levels for Title Findings', content: [
      'DEFENSIBLE: The chain link is backed by a recorded instrument with clear legal descriptions, matching grantor-grantee names, and no conflicting records. Safe for title opinions, division order analysis, and lease execution. This is the standard expected by operators and title companies.',
      'AGGRESSIVE: A reasonable interpretation that relies on secondary evidence — such as an affidavit rather than a recorded deed, or a name match that requires inference (e.g., initials vs. full names). Supportable but carries higher challenge risk in a title dispute.',
      'DISCLOSURE: The finding relies on circumstantial evidence, like a recording gap filled by inference from surrounding instruments, or a probate resolved using genealogy records rather than a filed determination of heirship. Must be disclosed in the title opinion with a description of the supporting evidence.',
      'HIGH_RISK: Thin or conflicting evidence. Multiple instruments may claim the same interest, or a critical link depends on an unrecorded document. Title opinions based on HIGH_RISK findings should include full disclaimers and recommend additional curative work before proceeding.',
    ]},
  ],
  aiCapabilities: [
    { capability: 'Instrument Classification', desc: 'AI classifies 59+ instrument types across 6 categories by analyzing document text, legal descriptions, and recording metadata. The classifier handles non-standard formatting, abbreviations, and county-specific recording conventions.' },
    { capability: 'Name Resolution', desc: 'Grantor and grantee name matching handles variations: nicknames (Bobby/Robert), maiden vs. married names, middle initials, suffixes (Jr./Sr./III), and common misspellings. The system uses fuzzy matching combined with genealogical context to link records across decades.' },
    { capability: 'Chain Graph Traversal', desc: 'A knowledge graph engine links instruments by grantor-grantee relationships and legal descriptions. Graph traversal algorithms identify the shortest path from sovereignty to present, detect branches where mineral and surface rights diverge, and flag orphan instruments with no chain connection.' },
    { capability: 'Fractional Arithmetic', desc: 'All mineral interest calculations use exact rational number arithmetic — never floating-point. Fractions like 1/3 * 1/4 * 1/2 are computed as exact ratios, ensuring that ownership tables always balance to 8/8ths and overconveyances are detected precisely.' },
    { capability: 'Probate Succession Engine', desc: 'AI applies Texas Estates Code Chapter 201 intestacy rules to determine heirs and fractional shares when a property owner dies without a will. Multi-generation succession is tracked automatically, with family tree diagrams generated for each probate tract.' },
    { capability: 'Gap Severity Scoring', desc: 'Detected gaps are scored by severity (critical, moderate, minor) based on the type of break, the size of the affected interest, the availability of curative options, and the impact on the overall chain confidence. Curative recommendations are generated automatically.' },
  ],
  troubleshooting: [
    { issue: 'Investigation shows "searching" phase for a long time', solution: 'Courthouse portal response times vary by county and time of day. Some county portals are significantly slower during business hours. If a job stays in the searching phase for more than 2 hours, check /counties to verify the target county\'s portal is online. If the portal is down, the system will retry automatically when it comes back up.' },
    { issue: 'Records returned but chain is incomplete', solution: 'The most common cause is an uncommon name variation that the fuzzy matcher did not link. Try resubmitting with additional party name spellings or initials in the party field. You can also specify a broader date range or add abstract/survey identifiers to help narrow the geographic match.' },
    { issue: 'Overconveyance detected in the chain', solution: 'An overconveyance means the total interests granted from a single owner exceed their estate. This usually indicates a missing reservation clause in a deed, an error in the original conveyance, or a fractional calculation error in a prior title examination. Review the flagged instruments in the gap analysis and compare against the original recorded documents.' },
    { issue: 'Job completed but report shows "insufficient records"', solution: 'The target county may not have full digital records for the time period covered by the chain. Many Texas counties only have digital records back to the 1980s or 1990s. For older chains, the system relies on pre-indexed records from manual digitization projects. If coverage is insufficient, the report will note the date boundary and recommend a manual courthouse search for the gap period.' },
    { issue: 'TexasFile results show garbled party names', solution: 'TexasFile portals have a known column misalignment issue where party names appear in the legal description field. Title Intelligence normalizes this automatically, but very long party lists may truncate. If you see garbled names, click through to the original instrument record for the correct data.' },
  ],
  faq: [
    { q: 'How does AI chain of title analysis work?', a: 'The system ingests raw courthouse records — deeds, leases, probates, liens — and uses a knowledge graph to link grantor-grantee relationships from sovereignty to present. AI classifies 59 instrument types, resolves name variations, tracks mineral/surface splits, and calculates fractional interests using exact rational arithmetic. The result is a gap-free chain with confidence scores on every link.' },
    { q: 'Which Texas counties are covered?', a: 'We currently cover 98 Texas counties through direct connections to GovOS, Tyler Technologies, TexasFile, and Odyssey courthouse portals. Coverage is strongest in the Permian Basin (Reeves, Loving, Ward, Winkler, Pecos, Crane, Upton, Midland, Ector, Andrews) and extends across all major oil and gas producing regions. Expansion to all 254 Texas counties is underway.' },
    { q: 'What is the typical turnaround time?', a: 'A standard single-tract title search completes in 2 to 8 hours depending on chain complexity and county portal response times. Simple chains with clean conveyance history finish in under 3 hours. Multi-generation probate tracts with heirship issues may take up to 8 hours. Batch jobs of 100+ titles are processed in parallel within 24 to 48 hours.' },
    { q: 'How accurate are the fractional interest calculations?', a: 'All calculations use exact rational arithmetic — never floating-point. Fractions like 1/3 * 1/4 * 1/2 are computed as exact ratios. The system verifies that all interests in a section sum to the full mineral estate (8/8ths) and flags overconveyances automatically. This eliminates the rounding errors common in spreadsheet-based calculations.' },
    { q: 'Can I integrate Title Intelligence with my existing tools?', a: 'Yes. Professional and Enterprise plans include full REST API access. POST to /title-chain with a legal description or section/block/survey identifiers and receive structured JSON with the complete chain, ownership tables, and gap analysis. Webhook callbacks notify your systems when async jobs complete. The API integrates with any project management, GIS, or lease management platform.' },
    { q: 'What confidence level should I use for title opinions?', a: 'Use DEFENSIBLE findings for title opinions and division order work. AGGRESSIVE findings are appropriate for internal research where some risk tolerance is acceptable. DISCLOSURE and HIGH_RISK findings should be flagged in any title opinion with a description of the supporting evidence and recommended curative actions.' },
    { q: 'How does gap detection work?', a: 'The AI compares every link in the chain against expected conveyance patterns. It flags missing probates, unrecorded transfers, overconveyances, orphan instruments, and recording gaps longer than statutory thresholds. Each gap receives a severity score — critical, moderate, or minor — along with a specific curative recommendation citing relevant Texas Property Code sections.' },
  ],
}

export default function TitleIntelligenceDocPage() {
  return <ProductDoc {...data} />
}
