'use client'

import ProductDoc from '@/components/ProductDoc'
import FaqSchema from '@/components/FaqSchema'
import BreadcrumbSchema from '@/components/BreadcrumbSchema'

const data = {
  name: 'Echo Tool Discovery',
  tagline: 'Discover, search, and execute 37,475+ MCP tools across 1,873 servers. Semantic capability matching, automatic tool recommendation, and a unified execution proxy — the index for the entire Echo tool ecosystem.',
  accent: '#14b8a6',
  productUrl: '/mega-gateway',
  workerUrl: 'https://echo-tool-discovery.bmcii1976.workers.dev',
  version: '1.5.0',
  overview: [
    'Echo Tool Discovery is the intelligence layer on top of the MEGA Gateway — the index, search engine, and execution broker for 37,475+ MCP (Model Context Protocol) tools registered across 1,873 servers. The MEGA Gateway routes MCP calls; Tool Discovery tells you what tools exist, what they do, which ones match your current need, and how to call them. Without Tool Discovery, finding the right tool in a catalog of 37,000+ requires either memorizing tool names or exhaustive manual search. With Tool Discovery, you describe what you want to do and it surfaces the top candidates ranked by semantic relevance, usage popularity, and server health.',
    'The platform indexes every registered MCP server\'s tool manifest, extracting tool names, descriptions, parameter schemas, return types, and example invocations. These are embedded into a vector space so semantic search can find tools by conceptual description rather than exact keyword match. "Send a message to a Slack channel" finds the correct Slack tools even if your query doesn\'t use the word "Slack". The recommendation engine goes further: given your current task context, it proactively suggests tools you haven\'t asked for but are statistically likely to need next based on what similar task sequences have used.',
    'Tool Discovery doubles as a health-monitoring service for the server fleet. Every server\'s availability, response latency, error rate, and tool count is tracked continuously. Tools from servers that are offline, degraded, or consistently slow are ranked lower in search results and flagged in the tool record. Server health data feeds into capacity planning, alerting practitioners when a server they depend on is at risk. Usage analytics are aggregated per tool, per server, and per category — the top-50 most-used tools, the fastest-growing server clusters, and the categories with the most unreliable servers are all visible in the analytics dashboard.',
  ],
  gettingStarted: [
    { step: 1, title: 'Search for Tools', desc: 'Call GET /tools/search?q=your+description to find tools matching your task. The search engine combines semantic similarity, keyword matching, and usage popularity to rank results. Start with a high-level description and refine with more specific terms if you get too many results.' },
    { step: 2, title: 'Review Tool Details', desc: 'Call GET /tools/:id to get the full tool spec: parameter schema, return type definition, example call, server hosting it, health status, and usage statistics. Use the parameter schema to construct your call payload before executing.' },
    { step: 3, title: 'Get AI Recommendations', desc: 'For complex tasks requiring multiple tools, call GET /tools/recommend?context=your+task+description. Tool Discovery returns an ordered sequence of recommended tools with rationale for each recommendation, covering the full workflow from start to finish.' },
    { step: 4, title: 'Execute via Proxy', desc: 'Call POST /tools/execute with the tool_id and parameters. Tool Discovery routes the call through the MEGA Gateway to the appropriate MCP server, handles authentication, logs the execution, and returns the result. No need to know the server URL or MCP protocol details.' },
    { step: 5, title: 'Monitor Tool Health', desc: 'Subscribe to tool health notifications for your critical tools via the notification hub. When a tool\'s server goes offline or its latency spikes above your configured threshold, you\'ll receive an alert before it impacts your workflows.' },
  ],
  features: [
    { title: '37,475+ Indexed MCP Tools', desc: 'The complete catalog of tools registered across all MEGA Gateway MCP servers, indexed and searchable in real time. The index updates automatically as servers register new tools or deprecate old ones. Tool count displayed in the dashboard reflects the live index state.' },
    { title: '1,873 Server Catalog', desc: 'Every MCP server registered to the MEGA Gateway is cataloged with its name, category, tool count, hosting environment, health status, SLA tier, and contact information. Server records include the full tool manifest so you can browse a server\'s capabilities without calling it directly.' },
    { title: 'Semantic Tool Search', desc: 'Vector embedding-based search understands natural language descriptions of what you want to do and maps them to the most relevant tools. Search handles synonyms, paraphrases, and domain-specific terminology. Queries like "extract text from PDF" and "parse PDF content" return the same top results.' },
    { title: 'Capability Matching', desc: 'Input a structured capability requirement (action: "send", target: "email", constraints: ["HTML format", "attachment support"]) and Tool Discovery returns tools that satisfy all constraints, ranked by how completely they match and how healthy their hosting server is.' },
    { title: 'Tool Recommendation Engine', desc: 'Given a task context, the recommendation engine suggests a complete toolchain in execution order: the primary tool for the task plus supporting tools for common follow-on actions. Recommendations are personalized based on your historical tool usage patterns.' },
    { title: 'Unified Execution Proxy', desc: 'Execute any indexed tool via POST /tools/execute without knowing the MCP server URL, authentication method, or protocol version. Tool Discovery handles all server-side complexity: authentication, protocol negotiation, timeout management, retry logic, and result normalization.' },
    { title: 'Tool Categorization', desc: '200+ tool categories organized in a hierarchical taxonomy: Communication (Email, SMS, Slack, Discord, Telegram), Data (Databases, Spreadsheets, Storage), Web (Browser, Scraping, APIs), AI (LLM, Image, Audio, Embeddings), Productivity (Calendar, Files, Search), Security (Scanning, Auth, Encryption), and many more.' },
    { title: 'Server Health Tracking', desc: 'Continuous polling of every registered MCP server at 60-second intervals. Health metrics: HTTP status, tool manifest checksum (detects silent tool changes), response latency, error rate on last 100 calls, and uptime percentage. Tools from degraded servers are ranked lower in search results.' },
    { title: 'Usage Analytics', desc: 'Execution counts per tool, per server, and per category. Trending tools (fastest usage growth in last 7 days), most popular tools by category, and tool reliability scores derived from execution success rate. Analytics help identify which tools are production-ready vs. experimental.' },
    { title: 'Tool Version Management', desc: 'Tools with multiple versions are tracked separately. The latest version is returned by default in search results; older versions remain searchable and executable for backward compatibility. When a tool\'s parameter schema changes between versions, Tool Discovery flags the breaking change in the tool record.' },
    { title: 'Automatic New Tool Discovery', desc: 'When a new MCP server registers with the MEGA Gateway, Tool Discovery automatically crawls its tool manifest within 5 minutes, embeds all tool descriptions into the vector index, categorizes them, and makes them searchable. New tools appear in search results without any manual configuration.' },
    { title: 'Tool Compatibility Checking', desc: 'For tools that call other tools (compound tools), Tool Discovery validates that all dependencies are healthy before surfacing the compound tool in search results. A compound tool is only marked AVAILABLE if every tool in its dependency chain is healthy on a currently-online server.' },
  ],
  apiEndpoints: [
    { method: 'GET', path: '/tools/search', desc: 'Semantic search across all 37,475+ indexed tools. Query parameter q accepts natural language descriptions. Optional filters: category (tool category code), server_id, health_status (HEALTHY/DEGRADED only), min_usage_count. Returns ranked list of tools with relevance scores and server health indicators.', auth: false },
    { method: 'GET', path: '/tools/:id', desc: 'Get full tool specification: name, description, parameter JSON schema, return type definition, example invocation, hosting server details, health status, version history, execution count, success rate, and average latency. Also returns related tools (same server or category).', auth: false },
    { method: 'GET', path: '/servers', desc: 'List all registered MCP servers with name, category, tool count, health status, uptime percentage, average latency, and last manifest update. Supports filtering by health status and category. Includes per-server tool count breakdown by category.', auth: false },
    { method: 'POST', path: '/tools/execute', desc: 'Execute a tool via the unified proxy. Accepts tool_id and parameters JSON matching the tool\'s parameter schema. Tool Discovery routes to the correct MCP server, handles authentication, enforces timeouts, retries transient failures, logs execution, and returns the normalized result.', auth: true },
    { method: 'GET', path: '/tools/categories', desc: 'List all tool categories in the hierarchical taxonomy. Returns category code, display name, parent category, tool count, and top 5 tools by usage. Category codes are used as filter values in /tools/search. Includes category health score derived from server availability.', auth: false },
    { method: 'GET', path: '/tools/recommend', desc: 'Get AI-powered tool recommendations for a task. Query parameter context accepts a natural language task description. Returns ordered list of recommended tools with rationale, estimated execution order, and parameter hints. Optional history parameter accepts recent tool execution IDs for personalization.', auth: true },
    { method: 'GET', path: '/tools/stats', desc: 'System-wide statistics: total indexed tools, total registered servers, tools added in last 24h/7d/30d, top 10 tools by execution count, top 10 growing tools, category distribution, average server health score, and total executions served. No authentication required.', auth: false },
    { method: 'GET', path: '/health', desc: 'Tool Discovery service health. Returns service status, index size (tool and server counts), last index update timestamp, vector search latency, proxy execution success rate for last hour, and any server fleet health warnings. No authentication required.', auth: false },
  ],
  userGuide: [
    { id: 'search-strategies', title: 'Effective Search Strategies', content: [
      'Semantic search performs best with descriptive natural language phrases rather than single keywords. "Find tools to scrape a website and extract structured data" returns more relevant results than "scraper". The embedding model understands intent — "monitor a URL for changes" and "detect website updates" return the same top results because they represent the same intent.',
      'When your initial search returns too many results, use category filters to narrow scope. Search for "send notification" and you\'ll get 400+ results across Communication, Monitoring, and Automation categories. Add category: "communication" and results collapse to the relevant subset. Categories are hierarchical — filtering by "communication" includes all subcategories (email, SMS, push, etc.).',
      'For highly specific tools, combine keyword search with health filtering. If you need a tool for production use, add health_status: "HEALTHY" and min_usage_count: 100 to your search parameters. This filters out experimental tools with low usage and tools on degraded servers. For research and exploration, remove these filters to see the full catalog.',
    ]},
    { id: 'tool-execution', title: 'Executing Tools via the Proxy', content: [
      'The execution proxy abstracts all MCP protocol complexity. You call POST /tools/execute with a tool_id and a parameters object. Tool Discovery validates your parameters against the tool\'s JSON schema before forwarding to the MCP server — schema violations return a 400 with a detailed error message showing exactly which parameter is invalid and what value is expected.',
      'Proxy execution adds a small latency overhead (typically 10-50ms) compared to calling the MCP server directly. This overhead buys you authentication handling, retry logic (up to 3 retries with exponential backoff on transient failures), result normalization (all tools return a consistent response envelope), and execution logging for audit and analytics.',
      'For latency-sensitive workflows, use the bulk execution endpoint POST /tools/execute/batch to submit multiple tool calls in a single request. The proxy executes non-dependent calls in parallel and dependent calls in sequence based on the dependency graph you provide. Batch results are returned when all executions complete or on the first failure (configurable via fail_fast parameter).',
    ]},
    { id: 'recommendations', title: 'Using the Recommendation Engine', content: [
      'The recommendation engine is most powerful when you provide rich context. Instead of context: "I need to send an email", try context: "I am processing a customer support ticket. The ticket has been resolved. I need to notify the customer, update the CRM record, and close the ticket in the helpdesk system." This multi-step context produces a complete toolchain recommendation covering all three actions in the correct order.',
      'Recommendations are personalized based on your execution history. After 20+ tool executions through the proxy, the recommendation engine learns your preferred tool choices when multiple options are available (e.g., you consistently prefer Sendgrid over Mailgun for email) and weights recommendations accordingly. Personalization improves over 30-90 days of active use.',
      'After a recommendation is executed, provide feedback via POST /tools/recommend/feedback with the recommendation_id and outcome (success, failure, used_different_tool). Feedback directly improves recommendation quality for your account and contributes to aggregate recommendation tuning for all users.',
    ]},
    { id: 'server-health', title: 'Understanding Server Health', content: [
      'Server health is the most important signal when choosing between tools with similar functionality. A tool on a 99.9% uptime server is preferable to a functionally superior tool on a 90% uptime server for production workflows. The health indicator on every tool search result reflects the current state of its hosting server, not the tool itself.',
      'Health polling runs every 60 seconds per server. Health state transitions: HEALTHY (< 1% error rate, p95 latency < 2s), DEGRADED (1-10% error rate or p95 latency 2-10s), CRITICAL (> 10% error rate or p95 > 10s or server unreachable). Transitions from HEALTHY to CRITICAL are immediate; recovery from CRITICAL to HEALTHY requires 5 consecutive healthy polls.',
      'The proxy automatically avoids routing to CRITICAL servers. If you call POST /tools/execute for a tool on a CRITICAL server, the proxy returns a 503 with an alternative tool suggestion from the same category on a healthy server. This automatic fallback can be disabled by passing strict_server: true if you specifically require that tool on that server.',
    ]},
    { id: 'catalog-management', title: 'Contributing to the Catalog', content: [
      'The tool catalog grows through two channels: automatic discovery from registered MCP servers, and manual submissions for external tools not connected to the MEGA Gateway. To add a new MCP server to the MEGA Gateway, submit a server registration request with your server\'s manifest URL, capability description, and SLA tier commitment. The Tool Discovery indexer will crawl your manifest and include all tools in the searchable catalog within 5 minutes.',
      'Tool descriptions that are indexed well produce better search results. MCP server operators should write tool descriptions that include: what the tool does in plain language, common use cases with concrete examples, any prerequisite context or resources needed, and the format of key return values. The vector embedder extracts meaning from these descriptions — richer descriptions produce higher-quality search matches.',
      'The analytics dashboard shows you which of your server\'s tools are most searched and executed, which searches are failing to find your tools (helping you identify description gaps), and how your server\'s health score compares to others in the same category. Use this data to improve your tool descriptions and prioritize server reliability investments.',
    ]},
  ],
  aiCapabilities: [
    { capability: 'Semantic Vector Embedding', desc: 'All 37,475+ tool descriptions are embedded using a domain-adapted sentence transformer model. The embedding space is optimized for tool-capability semantics rather than general language similarity. Tools that perform the same function cluster together in the vector space regardless of how their descriptions are worded.' },
    { capability: 'Intent-Based Query Understanding', desc: 'Queries are not searched as literal strings — they are embedded and matched against the tool vector space. The model understands that "extract data from a web page" and "web scraping" and "HTML parsing" all represent similar intents and will return similar results. Misspellings and domain jargon are handled gracefully.' },
    { capability: 'Sequential Recommendation Modeling', desc: 'The recommendation engine is trained on tool execution sequences — sequences of tools used together to complete common tasks. Given the first tool in a sequence, the model predicts the next N tools needed with probabilities. This powers the toolchain recommendations that suggest complete workflows rather than individual tools.' },
    { capability: 'Personalization with Collaborative Filtering', desc: 'User preference models combine collaborative filtering (users with similar tool usage patterns tend to prefer similar tools) with content-based filtering (your preference for specific tool characteristics). After sufficient usage history, recommendations reflect your individual preferences, not just global popularity.' },
    { capability: 'Health-Aware Ranking', desc: 'Search ranking is not purely semantic. The ranking model combines semantic relevance, usage popularity (log-scaled to prevent monopolization by old tools), server health score, and tool reliability score (execution success rate). Newer but highly relevant tools on healthy servers can outrank older but unreliable tools.' },
    { capability: 'Anomaly Detection on Tool Behavior', desc: 'Execution telemetry is monitored for behavioral anomalies: sudden latency spikes, unusual error patterns, unexpected parameter failures on previously successful calls. Anomaly alerts are generated before a server\'s health metrics degrade to CRITICAL, giving operators a head start on investigation.' },
  ],
  troubleshooting: [
    { issue: 'Search returns no results for a specific task', solution: 'The tool you need may not be indexed yet, or the description in the catalog may not semantically match your query. Try alternative phrasings of your task. Check GET /tools/categories to ensure a category for your task type exists. If you believe a tool should exist but is not found, search GET /servers for servers in the relevant category and browse their tool manifests directly.' },
    { issue: 'Tool execution returns "Server Unavailable"', solution: 'The tool\'s hosting server is in CRITICAL health state. Check the server status via GET /servers/:id. If the server is owned by your organization, investigate the server health via Fleet Commander. For third-party servers, the proxy will automatically suggest an alternative tool from the same category via the fallback mechanism. If no alternative exists, the tool is unavailable until the server recovers.' },
    { issue: 'Proxy execution succeeds but returns unexpected results', solution: 'Tool behavior is controlled by the MCP server, not by Tool Discovery. Unexpected results indicate either incorrect parameter values (verify your parameters against the tool\'s JSON schema via GET /tools/:id) or a change in the tool\'s behavior on the server side. Check the tool\'s version history for recent updates and compare the parameter schema between versions.' },
    { issue: 'Recommendations are not relevant to my task', solution: 'Recommendation quality depends heavily on context richness. Provide 2-3 sentences describing the full task, not just the immediate action needed. Include the domain (e.g., "for a tax compliance workflow"), the upstream input (e.g., "given a PDF document"), and the desired output (e.g., "stored in our CRM"). Also ensure your execution history is accumulating — personalization requires 20+ historical executions.' },
    { issue: 'New tools I added to my MCP server are not appearing in search', solution: 'New tool indexing runs every 5 minutes via the automatic discovery cycle. If tools are not appearing after 10 minutes, verify the server is registered and HEALTHY via GET /servers. Check that the tool descriptions in your manifest are valid strings (not null or empty). Trigger a manual re-index via POST /servers/:id/reindex to force immediate crawling of your manifest.' },
  ],
  faq: [
    { q: 'What is an MCP tool?', a: 'MCP (Model Context Protocol) is a standard for exposing callable functions to AI agents. An MCP tool is a named function with a defined parameter schema and return type, hosted on an MCP server. Tools can do anything: call external APIs, read and write files, execute code, interact with databases, control browsers, send messages, or perform complex multi-step workflows. The MEGA Gateway aggregates 37,475 such tools from 1,873 servers into one callable endpoint.' },
    { q: 'Do I need to understand MCP protocol to use Tool Discovery?', a: 'No. The execution proxy handles all MCP protocol details. You interact with Tool Discovery through a standard REST API — search for tools, get their parameter schemas, and execute them via POST /tools/execute. The response you receive is a normalized JSON envelope, regardless of what protocol the underlying MCP server uses.' },
    { q: 'How quickly does the catalog update when new tools are added?', a: 'New tool discovery is triggered automatically when an MCP server registers or re-registers with the MEGA Gateway. The indexing pipeline runs within 5 minutes of server registration and makes new tools searchable immediately after indexing completes. Server operators can also manually trigger re-indexing via POST /servers/:id/reindex for immediate updates.' },
    { q: 'Can Tool Discovery find tools that require authentication?', a: 'Yes. Tool Discovery indexes all tools including those requiring authentication. The tool record flags whether authentication is required and what type (API key, OAuth, JWT, custom header). When executing an authenticated tool via the proxy, you provide your credentials in the execution request — Tool Discovery never stores credentials for tools on external servers.' },
    { q: 'How does Tool Discovery handle duplicate tools across multiple servers?', a: 'Tools with identical names on different servers are tracked as separate records (identified by server_id + tool_name composite key). In search results, duplicates are deduplicated by default: only the highest-health instance is shown unless you set include_duplicates: true. This prevents search results from being dominated by copies of the same tool on multiple servers.' },
    { q: 'Is there a rate limit on the /tools/execute proxy?', a: 'The proxy itself enforces a 1000 req/min rate limit per API key. This limit is separate from the rate limits of the underlying MCP servers, which vary per server. If you are hitting the proxy rate limit, consider using the batch execution endpoint which counts as one API call regardless of how many tools are executed in the batch.' },
  ],
}

export default function ToolDiscoveryDocPage() {
  return (
    <>
      <FaqSchema faqs={data.faq} name={data.name} />
      <BreadcrumbSchema items={[
        { name: 'Home', href: '/' },
        { name: 'Docs', href: '/docs' },
        { name: data.name, href: '/docs/tool-discovery' },
      ]} />
      <ProductDoc {...data} />
    </>
  )
}
